# Addressing Reviewer Comments 1

This notebook contains the code to replicate select results from the [paper on arxiv](https://arxiv.org/abs/2504.06195).

# old code

## imports & load data

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression, Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.cross_decomposition import PLSRegression

from sklearn.svm import SVR
from sklearn.neural_network import MLPRegressor
from xgboost import XGBRegressor
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd
from sklearn.metrics import mean_squared_error, r2_score

import optuna
import warnings
warnings.filterwarnings('ignore')

from sklearn.decomposition import PCA

from tqdm import tqdm
import scipy.stats as stats

from whecho.whecho import whecho_simple
import pickle
import os

### load matrices

In [2]:
# TiTE
all_data = {}
all_data["Ti_TE"] = pd.read_excel("../p04_TE_TM_1D_compare/Ti_TE_matrix.xlsx", header=None).transpose()
all_data["Ti_TE"].columns = [f"feature_{i+1}" for i in range(all_data["Ti_TE"].shape[1])]
all_data["Ti_TE"]["target"] = list(range(1, all_data["Ti_TE"].shape[0] + 1))

In [3]:
all_data["Ti_TE"].shape

(101, 10001)

In [4]:
for dat in ["Si_TE", "Si_TM", "Ti_TM"]:
    all_data[dat] = pd.read_excel(f"../p06_multvar_SI_fitting/{dat}_matrix.xlsx", header=None).transpose()
    all_data[dat].columns = [f"feature_{i+1}" for i in range(all_data[dat].shape[1])]
    all_data[dat]["target"] = list(range(1, all_data[dat].shape[0] + 1))

### build the 5-fold cross validation groups and construct PCs

In [5]:
# split the data into 5-folds cross validation
kf = KFold(n_splits=5, shuffle=True, random_state=19890417)
#kf = KFold(n_splits=5, shuffle=True, random_state=42)
PC_folds = {}
folds = {} # this will not use PC to reduce the data

for dat in all_data.keys():
    PC_folds[dat] = []
    folds[dat] = []
    full_data = all_data[dat].copy()
    for train_index, test_index in kf.split(all_data[dat]):
        # because this doesn't check for out of range values we need to make sure that we move any 0 or 100 index values from test to train
        # if 0 in test_index:
        #     test_index = np.delete(test_index, np.where(test_index == 0)[0][0])
        #     train_index = np.append(train_index, 0)
        # if 100 in test_index:
        #     test_index = np.delete(test_index, np.where(test_index == 100)[0][0])
        #     train_index = np.append(train_index, 100)
        # train_index.sort()
        # print(f"train: {train_index}, test: {test_index}")
        train_data = full_data.iloc[train_index]
        test_data = full_data.iloc[test_index]
        # first put the raw data into the folds
        folds[dat].append((train_data.drop(columns=["target"]), train_data["target"].values, test_data.drop(columns=["target"]), test_data["target"].values))
        # now we also want to dimensionally reduce the data into 80 PCs following the training data
        pca = PCA(n_components=80, svd_solver='full', random_state=19890417)
        # first standardize the data according to the training data
        scaler = StandardScaler()
        scaler.fit(train_data.drop(columns=["target"]))
        train_data_scaled = scaler.transform(train_data.drop(columns=["target"]))
        test_data_scaled = scaler.transform(test_data.drop(columns=["target"]))
        pca.fit(train_data_scaled)
        train_data_pca = pca.transform(train_data_scaled)
        test_data_pca = pca.transform(test_data_scaled)
        PC_folds[dat].append((train_data_pca, train_data["target"].values, test_data_pca, test_data["target"].values))

## Identify best single variate performer for each dataset

In [6]:
# first check if the results_dfs.pickle file exists and if so load it
if os.path.exists("results_dfs.pickle"):
    with open("results_dfs.pickle", "rb") as f:
        results_dfs = pickle.load(f)
        print("Loaded existing results_dfs from pickle file.")
else:
    results_dfs = {}
    for dat in ["Ti_TM", "Ti_TE", "Si_TE", "Si_TM"]:
        result_list = []
        fold_i = 0
        for train_data_pca, train_target, test_data_pca, test_target in folds[dat]:
            for feat_i in tqdm(range(train_data_pca.shape[1])):
                X_train = train_data_pca[f"feature_{feat_i+1}"].to_numpy()
                y_train = train_target
                X_test = test_data_pca[f"feature_{feat_i+1}"].to_numpy()
                y_test = test_target
                # Fit a linear regression model
                model = LinearRegression()
                model.fit(X_train.reshape(-1, 1), y_train)
                # Make predictions
                y_pred = model.predict(X_test.reshape(-1, 1))
                # Calculate MSE, R2, RMSE, MAE
                mse = mean_squared_error(y_test, y_pred)
                r2 = r2_score(y_test, y_pred)
                rmse = np.sqrt(mse)
                mae = np.mean(np.abs(y_test - y_pred))
                # now calculate the same metrics on the training data
                y_train_pred = model.predict(X_train.reshape(-1, 1))
                mse_train = mean_squared_error(y_train, y_train_pred)
                r2_train = r2_score(y_train, y_train_pred)
                rmse_train = np.sqrt(mse_train)
                mae_train = np.mean(np.abs(y_train - y_train_pred))
                # Append results to the list
                result_list.append({
                    "feature": f"feature_{feat_i+1}",
                    "mse": mse,
                    "r2": r2,
                    "rmse": rmse,
                    "mae": mae,
                    "fold": fold_i,
                    "mse.train": mse_train,
                    "r2.train": r2_train,
                    "rmse.train": rmse_train,
                    "mae.train": mae_train,
                })
            fold_i += 1
        results_dfs[dat] = pd.DataFrame(result_list)
    # save results_dfs to a pickle file
    with open("results_dfs.pickle", "wb+") as f:
        pickle.dump(results_dfs, f)

Loaded existing results_dfs from pickle file.

In [7]:
# for each dataset we want to print the mean and std of the metrics for the best feature
# also save them to a lookup table
best_results = {}
for dat in ["Ti_TM", "Ti_TE", "Si_TE", "Si_TM"]:
    print(f"Dataset: {dat}")
    # first group by feature to find the feature with lowest mean mse
    mean_results = results_dfs[dat].groupby("feature").agg({
        "mse": ["mean","std"],
        "r2": ["mean","std"],
        "rmse": ["mean","std"],
        "mae": ["mean","std"],
        "mse.train": ["mean","std"],
        "r2.train": ["mean","std"],
        "rmse.train": ["mean","std"],
        "mae.train": ["mean","std"],
    })
    mean_results.columns = ["_".join(col).strip() for col in mean_results.columns.values]
    mean_results = mean_results.reset_index()
    # now we want to find the feature with the lowest mean mse for training
    best_feature_idx = mean_results["mse.train_mean"].idxmin()
    best_feature = mean_results.iloc[best_feature_idx]
    print(f"Best feature: {best_feature['feature']} (train MSE: {best_feature['mse.train_mean']:.4f} std ({best_feature['mse.train_std']:.4f}))")
    print(f"Mean MSE: {best_feature['mse_mean']:.4f} std ({best_feature['mse_std']:.4f})")
    print(f"Mean R2: {best_feature['r2_mean']:.4f} std ({best_feature['r2_std']:.4f})")
    print(f"Mean RMSE: {best_feature['rmse_mean']:.4f} std ({best_feature['rmse_std']:.4f})")
    print(f"Mean MAE: {best_feature['mae_mean']:.4f} std ({best_feature['mae_std']:.4f})")
    print()
    # save the best feature to the lookup table
    best_results[dat] = {
        "feature": best_feature["feature"],
        "mse_mean": best_feature["mse_mean"],
        "mse_std": best_feature["mse_std"],
        "r2_mean": best_feature["r2_mean"],
        "r2_std": best_feature["r2_std"],
        "rmse_mean": best_feature["rmse_mean"],
        "rmse_std": best_feature["rmse_std"],
        "mae_mean": best_feature["mae_mean"],
        "mae_std": best_feature["mae_std"],
        "mse.train_mean": best_feature["mse.train_mean"],
        "mse.train_std": best_feature["mse.train_std"], 
        "r2.train_mean": best_feature["r2.train_mean"],
        "r2.train_std": best_feature["r2.train_std"],
        "rmse.train_mean": best_feature["rmse.train_mean"],
        "rmse.train_std": best_feature["rmse.train_std"],
        "mae.train_mean": best_feature["mae.train_mean"],
        "mae.train_std": best_feature["mae.train_std"],
    }

Dataset: Ti_TM
Best feature: feature_5094 (train MSE: 0.4017 std (0.0247))
Mean MSE: 0.4462 std (0.1050)
Mean R2: 0.9994 std (0.0002)
Mean RMSE: 0.6636 std (0.0855)
Mean MAE: 0.5234 std (0.0653)

Dataset: Ti_TE
Best feature: feature_4956 (train MSE: 0.0628 std (0.0038))
Mean MSE: 0.0655 std (0.0150)
Mean R2: 0.9999 std (0.0000)
Mean RMSE: 0.2547 std (0.0284)
Mean MAE: 0.2151 std (0.0306)

Dataset: Si_TE
Best feature: feature_390 (train MSE: 0.2336 std (0.0204))
Mean MSE: 0.2416 std (0.0866)
Mean R2: 0.9997 std (0.0001)
Mean RMSE: 0.4853 std (0.0873)
Mean MAE: 0.4001 std (0.0558)

Dataset: Si_TM
Best feature: feature_1206 (train MSE: 0.1355 std (0.0089))
Mean MSE: 0.1417 std (0.0378)
Mean R2: 0.9998 std (0.0001)
Mean RMSE: 0.3736 std (0.0509)
Mean MAE: 0.3097 std (0.0525)

## Now Evaluate the performance when the entire peak is used (Figure 7)

In [8]:
results_entire_wave_dfs = {}
for dat in ["Ti_TM", "Ti_TE", "Si_TE", "Si_TM"]:
    result_list = []
    fold_i = 0
    for train_data_pca, train_target, test_data_pca, test_target in PC_folds[dat]:
        # now we want to use the entire wave data
        # Fit a linear regression model
        model = LinearRegression()
        model.fit(train_data_pca, train_target)
        # Make predictions
        y_pred = model.predict(test_data_pca)
        # Calculate MSE, R2, RMSE, MAE
        mse = mean_squared_error(test_target, y_pred)
        r2 = r2_score(test_target, y_pred)
        rmse = np.sqrt(mse)
        mae = np.mean(np.abs(test_target - y_pred))
        # Append results to the list
        result_list.append({
            "mse": mse,
            "r2": r2,
            "rmse": rmse,
            "mae": mae,
            "fold": fold_i,
        })
        fold_i += 1
    results_entire_wave_dfs[dat] = pd.DataFrame(result_list)

# for each dataset we want to print the mean and std of the metrics for the best feature
for dat in ["Ti_TM", "Ti_TE", "Si_TE", "Si_TM"]:
    print(f"Dataset: {dat}")
    # first group by feature to find the feature with lowest mean mse
    mean_results = results_entire_wave_dfs[dat].agg({
        "mse": ["mean","std"],
        "r2": ["mean","std"],
        "rmse": ["mean","std"],
        "mae": ["mean","std"],
    })
    # mean_results.columns = ["_".join(col).strip() for col in mean_results.columns.values]
    
    # just print the mean and std
    # calculate the fold improvement for mse compared to the best feature
    fold_improvement = (mean_results["mse"].values[0] / best_results[dat]["mse_mean"])**-1
    print(f"Mean MSE: {mean_results['mse'].values[0]:.4e} std ({mean_results['mse'].values[1]:.4e}). {fold_improvement:.2f}x fold improvement")
    fold_improvement = (mean_results["r2"].values[0] / best_results[dat]["r2_mean"])**-1
    print(f"Mean R2: {mean_results['r2'].values[0]:.4f} std ({mean_results['r2'].values[1]:.4f}). {fold_improvement:.2f}x fold improvement")
    fold_improvement = (mean_results["rmse"].values[0] / best_results[dat]["rmse_mean"])**-1
    print(f"Mean RMSE: {mean_results['rmse'].values[0]:.4f} std ({mean_results['rmse'].values[1]:.4f}). {fold_improvement:.2f}x fold improvement")
    fold_improvement = (mean_results["mae"].values[0] / best_results[dat]["mae_mean"])**-1
    print(f"Mean MAE: {mean_results['mae'].values[0]:.4f} std ({mean_results['mae'].values[1]:.4f}). {fold_improvement:.2f}x fold improvement")
    print()

Dataset: Ti_TM
Mean MSE: 6.6233e-05 std (2.1992e-05). 6736.42x fold improvement
Mean R2: 1.0000 std (0.0000). 1.00x fold improvement
Mean RMSE: 0.0080 std (0.0014). 82.52x fold improvement
Mean MAE: 0.0066 std (0.0010). 79.74x fold improvement

Dataset: Ti_TE
Mean MSE: 1.0488e-04 std (6.4012e-05). 624.73x fold improvement
Mean R2: 1.0000 std (0.0000). 1.00x fold improvement
Mean RMSE: 0.0099 std (0.0031). 25.82x fold improvement
Mean MAE: 0.0072 std (0.0016). 29.84x fold improvement

Dataset: Si_TE
Mean MSE: 2.4732e-02 std (9.9685e-03). 9.77x fold improvement
Mean R2: 1.0000 std (0.0000). 1.00x fold improvement
Mean RMSE: 0.1547 std (0.0314). 3.14x fold improvement
Mean MAE: 0.1257 std (0.0288). 3.18x fold improvement

Dataset: Si_TM
Mean MSE: 1.0345e-01 std (2.1553e-01). 1.37x fold improvement
Mean R2: 0.9999 std (0.0003). 1.00x fold improvement
Mean RMSE: 0.2035 std (0.2785). 1.84x fold improvement
Mean MAE: 0.0871 std (0.0670). 3.56x fold improvement

## check the sv Si when using the peak shifts 1D datasets (Table 1)

In [9]:
Si_TE_1D = pd.read_excel("../p07_1D_SI_fitting/Si_TE_1Dfitting_4peaks.xlsx", header=None)
Si_TE_1D.columns = ["target","feature_1", "feature_2", "feature_3", "feature_4"]

Si_TM_1D = pd.read_excel("../p07_1D_SI_fitting/Si_TM_1Dfitting_4peaks.xlsx", header=None)
Si_TM_1D.columns = ["target","feature_1", "feature_2", "feature_3", "feature_4"]

Si_TE_1D_results = []
Si_TM_1D_results = []
# perform 5-fold cross validation on the 1D data
fold_i = 0
for train_index, test_index in kf.split(Si_TE_1D):
    for df, result in zip([Si_TE_1D, Si_TM_1D],[Si_TE_1D_results, Si_TM_1D_results]):
        train_data = df.iloc[train_index]
        test_data = df.iloc[test_index]
        for feat_name in [f"feature_{i+1}" for i in range(4)]:
            X_train = train_data[feat_name].to_numpy()
            y_train = train_data["target"].values
            X_test = test_data[feat_name].to_numpy()
            y_test = test_data["target"].values
            # Fit a linear regression model
            model = LinearRegression()
            model.fit(X_train.reshape(-1, 1), y_train)
            # Make predictions
            y_pred = model.predict(X_test.reshape(-1, 1))
            # Calculate MSE, R2, RMSE, MAE
            mse = mean_squared_error(y_test, y_pred)
            r2 = r2_score(y_test, y_pred)
            rmse = np.sqrt(mse)
            mae = np.mean(np.abs(y_test - y_pred))
            # now calculate the same metrics on the training data
            y_train_pred = model.predict(X_train.reshape(-1, 1))
            mse_train = mean_squared_error(y_train, y_train_pred)
            r2_train = r2_score(y_train, y_train_pred)
            rmse_train = np.sqrt(mse_train)
            mae_train = np.mean(np.abs(y_train - y_train_pred))
            # Append results to the list
            result.append({
                "feature": feat_name,
                "mse": mse,
                "r2": r2,
                "rmse": rmse,
                "mae": mae,
                "fold": fold_i,
                "mse.train": mse_train,
                "r2.train": r2_train,
                "rmse.train": rmse_train,
                "mae.train": mae_train,
            })
        # now we also want to try using all 4 features
        X_train = train_data.drop(columns=["target"]).to_numpy()
        y_train = train_data["target"].values
        X_test = test_data.drop(columns=["target"]).to_numpy()
        y_test = test_data["target"].values
        # Fit a linear regression model
        model = LinearRegression()
        model.fit(X_train, y_train)
        # Make predictions
        y_pred = model.predict(X_test)
        # Calculate MSE, R2, RMSE, MAE
        mse = mean_squared_error(y_test, y_pred)
        r2 = r2_score(y_test, y_pred)
        rmse = np.sqrt(mse)
        mae = np.mean(np.abs(y_test - y_pred))
        # now calculate the same metrics on the training data
        y_train_pred = model.predict(X_train)
        mse_train = mean_squared_error(y_train, y_train_pred)
        r2_train = r2_score(y_train, y_train_pred)
        rmse_train = np.sqrt(mse_train)
        mae_train = np.mean(np.abs(y_train - y_train_pred))
        # Append results to the list
        result.append({
            "feature": "all_features",
            "mse": mse,
            "r2": r2,
            "rmse": rmse,
            "mae": mae,
            "fold": fold_i,
            "mse.train": mse_train,
            "r2.train": r2_train,
            "rmse.train": rmse_train,
            "mae.train": mae_train,
        })
    fold_i += 1
Si_TE_1D_result_df = pd.DataFrame(Si_TE_1D_results)
Si_TM_1D_result_df = pd.DataFrame(Si_TM_1D_results)

In [10]:
# recall the best result using the entire wave data
# Dataset: Si_TE
# Mean MSE: 0.02473 std (9.9685e-03). ~22.7x fold improvement
# Mean R2: 1.0000 std (0.0000). 1.00x fold improvement
# Mean RMSE: 0.1547 std (0.0314). 3.14x fold improvement
# Mean MAE: 0.1257 std (0.0288). 3.18x fold improvement

Si_TE_1D_result_df.groupby("feature").agg({
    "mse": ["mean","std"],
    "r2": ["mean","std"],
    "rmse": ["mean","std"],
    "mae": ["mean","std"],
    "mse.train": ["mean","std"],
    "r2.train": ["mean","std"],
    "rmse.train": ["mean","std"],
    "mae.train": ["mean","std"],
})

                    mse                  r2                rmse            \
                   mean       std      mean       std      mean       std
feature
all_features   0.135694  0.026329  0.999824  0.000021  0.366952  0.036061
feature_1     10.035007  1.843891  0.986622  0.003594  3.157665  0.283188
feature_2      1.822854  0.590767  0.997550  0.000949  1.336948  0.210429
feature_3      2.907157  0.638258  0.996132  0.001105  1.697132  0.183369
feature_4      0.562897  0.073247  0.999250  0.000174  0.749018  0.048342

                   mae           mse.train            r2.train            \
                  mean       std      mean       std      mean       std
feature
all_features  0.296414  0.037559  0.121764  0.006810  0.999856  0.000008
feature_1     2.729086  0.278675  8.801394  0.272485  0.989567  0.000602
feature_2     1.125622  0.127932  1.554510  0.100828  0.998158  0.000142
feature_3     1.436463  0.196374  2.599922  0.108381  0.996920  0.000161
feature_4     0.604117  0.032712  0.512121  0.016505  0.999392  0.000044

             rmse.train           mae.train
                   mean       std      mean       std
feature
all_features   0.348838  0.009749  0.280877  0.010746
feature_1      2.966428  0.046052  2.568578  0.061155
feature_2      1.246267  0.040747  1.057536  0.034875
feature_3      1.612147  0.033630  1.369071  0.052450
feature_4      0.715551  0.011602  0.582389  0.008291

In [11]:
# Recall the best result using the entire wave data
# Dataset: Si_TM
# Mean MSE: 0.1034 std (2.1553e-01). ~5x fold worsensing
# Mean R2: 0.9999 std (0.0003). ~20% worse
# Mean RMSE: 0.2035 std (0.2785). ~20% worse
# Mean MAE: 0.0871 std (0.0670). ~2x fold improvement ?

Si_TM_1D_result_df.groupby("feature").agg({
    "mse": ["mean","std"],
    "r2": ["mean","std"],
    "rmse": ["mean","std"],
    "mae": ["mean","std"],
    "mse.train": ["mean","std"],
    "r2.train": ["mean","std"],
    "rmse.train": ["mean","std"],
    "mae.train": ["mean","std"],
})

                   mse                  r2                rmse            \
                  mean       std      mean       std      mean       std
feature
all_features  0.004556  0.001969  0.999994  0.000003  0.065996  0.015823
feature_1     0.791981  0.165257  0.998944  0.000304  0.886253  0.090394
feature_2     5.897534  1.077055  0.992177  0.001999  2.421099  0.211578
feature_3     0.755887  0.109434  0.998999  0.000221  0.867713  0.060837
feature_4     0.029436  0.006827  0.999961  0.000012  0.170650  0.019834

                   mae           mse.train            r2.train                \
                  mean       std      mean       std      mean           std
feature
all_features  0.053686  0.012416  0.004328  0.000483  0.999995  7.940732e-07
feature_1     0.754197  0.086529  0.692697  0.027480  0.999179  5.231713e-05
feature_2     2.103621  0.170806  5.226674  0.179268  0.993809  2.495997e-04
feature_3     0.736634  0.057786  0.668325  0.015962  0.999208  2.993195e-05
feature_4     0.137132  0.014416  0.027322  0.001810  0.999968  3.098957e-06

             rmse.train           mae.train
                   mean       std      mean       std
feature
all_features   0.065707  0.003633  0.051843  0.003193
feature_1      0.832152  0.016579  0.710209  0.019945
feature_2      2.285918  0.039535  2.005111  0.052579
feature_3      0.817464  0.009800  0.696552  0.014512
feature_4      0.165218  0.005523  0.132627  0.004225

## save the actual and fitted values for the best ML model for each dataset (Figure 8)

In [12]:
pred_fitted_results_entire_wave_dfs = {}
for dat in ["Ti_TM", "Ti_TE", "Si_TE", "Si_TM"]:
    result_df = None
    fold_i = 0
    for train_data_pca, train_target, test_data_pca, test_target in PC_folds[dat]:
        # now we want to use the entire wave data
        # Fit a linear regression model
        model = LinearRegression()
        model.fit(train_data_pca, train_target)
        # Make predictions
        y_pred = model.predict(test_data_pca)
        
        # now I want to create a dataframe with the true, predicted, and train/test labels
        pred_fitted_test_df = pd.DataFrame({
            "true": test_target,
            f"predicted_fold{fold_i}": y_pred,
            f"train/test_fold{fold_i}": ["test"] * len(test_target),
        })
        # now I want to create a dataframe with the true, predicted, and train/test labels for the training data
        pred_fitted_train_df = pd.DataFrame({
            "true": train_target,
            f"predicted_fold{fold_i}": model.predict(train_data_pca),
            f"train/test_fold{fold_i}": ["train"] * len(train_target),
        })
        # now I want to concatenate the two dataframes
        pred_fitted_df = pd.concat([pred_fitted_train_df, pred_fitted_test_df])
        fold_i += 1
        if result_df is None:
            result_df = pred_fitted_df
        else:
            result_df = result_df.merge(pred_fitted_df, on="true", how="outer")
    pred_fitted_results_entire_wave_dfs[dat] = result_df

In [13]:
# save the pred_fitted_results_entire_wave_dfs to a xlsx file one to a sheet
with pd.ExcelWriter("pred_fitted_results_entire_wave_dfs.xlsx") as writer:
    for dat in pred_fitted_results_entire_wave_dfs.keys():
        pred_fitted_results_entire_wave_dfs[dat].to_excel(writer, sheet_name=dat, index=False)

In [14]:
whecho_simple("starting section about the reviewer comments")

# Reviewer #1 Comment about Cross-Validation

In [15]:
# commenting to speed up nb (but all this cell does is produce the supplemental table 1 comparing the train-test splitting)
# suppl_table1_sheets = {}
# for dat in ["Ti_TM", "Ti_TE", "Si_TE", "Si_TM"]:
#     sheet_columns = []
#     level1 = [f"Fold {i}" for i in range(1, 6) for _ in range(3)]
#     level2 = ["training mean (std)", "testing mean (std)", "Pvalue"]*5
#     columns = pd.MultiIndex.from_arrays([level1, level2], names=['fold', 'stat'])
#     indices = ["target"] + [f"feature {i+1}" for i in range(1, 10001)]
#     for train_data, train_target, test_data, test_target in folds[dat]:
#         # Compute mean and std for each feature in train and test
#         train_means = train_data.mean(axis=0)
#         train_stds = train_data.std(axis=0)
#         test_means = test_data.mean(axis=0)
#         test_stds = test_data.std(axis=0)
#         # t-test for each feature
#         ttest_pvals = []
#         for col in train_data.columns:
#             t_stat, p_val = stats.ttest_ind(train_data[col], test_data[col], equal_var=False)
#             ttest_pvals.append(p_val)
#         col1 = ["{:.2e} ({:.2e})".format(m,s) for m,s in zip(train_means.values, train_stds.values)]
#         col2 = ["{:.2e} ({:.2e})".format(m,s) for m,s in zip(test_means.values, test_stds.values)]
#         col3 = ["{:.4f}".format(p) if p > 1e-4 else "<0.0001" for p in ttest_pvals]
#         # add the mean and variance and p-value of the target value to the front of the column lists
#         col1.insert(0, "{:.2e} ({:.2e})".format(train_target.mean(), train_target.std()))
#         col2.insert(0, "{:.2e} ({:.2e})".format(test_target.mean(), test_target.std()))
#         target_pval = stats.ttest_ind(train_target, test_target, equal_var=False)[1]
#         col3.insert(0, "<0.0001" if target_pval < 1e-4 else "{:.4f}".format(target_pval))
#         sheet_columns.append(col1)
#         sheet_columns.append(col2)
#         sheet_columns.append(col3)
#     suppl_table1_sheets[dat] = pd.DataFrame(np.array(sheet_columns).T, columns=columns, index=indices)

In [17]:
# # Write with MultiIndex headers preserved using openpyxl
# df = suppl_table1_sheets[dat]

# with pd.ExcelWriter(f"suppl_table1.xlsx", engine='openpyxl') as writer:
#     for dat in suppl_table1_sheets.keys():
#         # Write the DataFrame to the specified sheet
#         suppl_table1_sheets[dat].to_excel(writer, sheet_name=f"{dat} 5-fold stats", index=True)

# Reviewer #1 Comment about best single predictor

In [18]:
with pd.ExcelWriter(f"suppl_table2.xlsx", engine='openpyxl') as writer:
    for dat in ["Ti_TM", "Ti_TE", "Si_TE", "Si_TM"]:
        print(f"Dataset: {dat}")
        # first group by feature to find the feature with lowest mean mse
        mean_results = results_dfs[dat].groupby("feature").agg({
            "mse": ["mean","std"],
            "r2": ["mean","std"],
            "rmse": ["mean","std"],
            "mae": ["mean","std"],
            "mse.train": ["mean","std"],
            "r2.train": ["mean","std"],
            "rmse.train": ["mean","std"],
            "mae.train": ["mean","std"],
        })
        mean_results.sort_values(by=("mse","mean")).to_excel(writer, sheet_name=f"{dat} single predictor results", index=True)

Dataset: Ti_TM
Dataset: Ti_TE
Dataset: Si_TE
Dataset: Si_TM

# Reviewer #2 Comment on number of principal components

refer to the notebook in: `code\p06_multvar_SI_fitting\single_pred_vs_mult_PC.ipynb`

In [19]:
# in powershell I want to copy the file from code/p06_multvar_SI_fitting/all_PCs_mean_results.xlsx to code/p10_consolidating_reviewer_feedback/suppl_table3.xlsx
! powershell Copy-Item -Path "../p06_multvar_SI_fitting/all_PCs_mean_results.xlsx" -Destination "suppl_table3.xlsx"

# Reviewer #1 & #2 Comment about non-linear modeling

This will be difficult to respond to. Reviewer 2 highlights the following models

In [20]:
# SVR with RBF kernel
results_svr_dfs = {}
for dat in ["Ti_TM", "Ti_TE", "Si_TE", "Si_TM"]:
    result_list = []
    fold_i = 0
    for train_data_pca, train_target, test_data_pca, test_target in PC_folds[dat]:
        # No scaling needed for PCA data - PCs are already standardized
        
        # Fit SVR model with RBF kernel
        model = SVR(kernel='rbf', C=1.0, gamma='scale')
        model.fit(train_data_pca, train_target)
        # Make predictions
        y_pred = model.predict(test_data_pca)
        # Calculate metrics
        mse = mean_squared_error(test_target, y_pred)
        r2 = r2_score(test_target, y_pred)
        rmse = np.sqrt(mse)
        mae = np.mean(np.abs(test_target - y_pred))
        # Append results
        result_list.append({
            "mse": mse,
            "r2": r2,
            "rmse": rmse,
            "mae": mae,
            "fold": fold_i,
        })
        fold_i += 1
    results_svr_dfs[dat] = pd.DataFrame(result_list)

In [21]:
results_svr_dfs["Ti_TM"]

          mse        r2       rmse        mae  fold
0  245.085322  0.674030  15.655201  10.692680     0
1  242.413224  0.763716  15.569625  11.554959     1
2  168.415246  0.774668  12.977490   7.741769     2
3  116.399698  0.815047  10.788869   5.604096     3
4  385.938850  0.466513  19.645326  13.190922     4

In [22]:
results_entire_wave_dfs["Ti_TM"]

        mse   r2      rmse       mae  fold
0  0.000076  1.0  0.008709  0.007681     0
1  0.000042  1.0  0.006449  0.005393     1
2  0.000082  1.0  0.009061  0.007027     2
3  0.000088  1.0  0.009380  0.007056     3
4  0.000044  1.0  0.006607  0.005666     4

In [23]:
# Neural Network (MLP Regressor)
results_nn_dfs = {}
for dat in ["Ti_TM", "Ti_TE", "Si_TE", "Si_TM"]:
    result_list = []
    fold_i = 0
    for train_data_pca, train_target, test_data_pca, test_target in PC_folds[dat]:
        # No scaling needed for PCA data
        
        # Fit Neural Network model
        model = MLPRegressor(hidden_layer_sizes=(50,25), max_iter=1000, random_state=19890417)
        model.fit(train_data_pca, train_target)
        # Make predictions
        y_pred = model.predict(test_data_pca)
        # Calculate metrics
        mse = mean_squared_error(test_target, y_pred)
        r2 = r2_score(test_target, y_pred)
        rmse = np.sqrt(mse)
        mae = np.mean(np.abs(test_target - y_pred))
        # Append results
        result_list.append({
            "mse": mse,
            "r2": r2,
            "rmse": rmse,
            "mae": mae,
            "fold": fold_i,
        })
        fold_i += 1
    results_nn_dfs[dat] = pd.DataFrame(result_list)

In [24]:
results_nn_dfs["Ti_TM"]

        mse        r2      rmse       mae  fold
0  0.541053  0.999280  0.735563  0.583354     0
1  0.303976  0.999704  0.551341  0.443369     1
2  1.136061  0.998480  1.065862  0.868900     2
3  0.720975  0.998854  0.849102  0.687366     3
4  1.305240  0.998196  1.142471  0.833141     4

In [25]:
# XGBoost
results_xgb_dfs = {}
for dat in ["Ti_TM", "Ti_TE", "Si_TE", "Si_TM"]:
    result_list = []
    fold_i = 0
    for train_data_pca, train_target, test_data_pca, test_target in PC_folds[dat]:
        # Fit XGBoost model
        model = XGBRegressor(n_estimators=100, random_state=19890417, verbosity=0)
        model.fit(train_data_pca, train_target)
        # Make predictions
        y_pred = model.predict(test_data_pca)
        # Calculate metrics
        mse = mean_squared_error(test_target, y_pred)
        r2 = r2_score(test_target, y_pred)
        rmse = np.sqrt(mse)
        mae = np.mean(np.abs(test_target - y_pred))
        # Append results
        result_list.append({
            "mse": mse,
            "r2": r2,
            "rmse": rmse,
            "mae": mae,
            "fold": fold_i,
        })
        fold_i += 1
    results_xgb_dfs[dat] = pd.DataFrame(result_list)

In [26]:
results_xgb_dfs["Ti_TM"]

        mse        r2      rmse       mae  fold
0  2.536346  0.996627  1.592591  1.414469     0
1  1.634298  0.998407  1.278397  1.113264     1
2  3.402285  0.995448  1.844528  1.510601     2
3  3.116517  0.995048  1.765366  1.494625     3
4  4.639960  0.993586  2.154057  1.735904     4

Try to use optuna to determine the best hyper-parameters for each model:

In [27]:
max_trials = 100

# Optuna optimization for hyperparameters
optuna.logging.set_verbosity(optuna.logging.INFO)  # Changed from WARNING to INFO

def create_svr_objective(dataset_name, cv_folds):
    def objective(trial):
        C = trial.suggest_float('C', 0.01, 100.0, log=True)
        gamma = trial.suggest_float('gamma', 1e-6, 1.0, log=True)
        epsilon = trial.suggest_float('epsilon', 0.001, 1.0, log=True)
        
        mse_scores = []
        for train_data_pca, train_target, test_data_pca, test_target in cv_folds:
            model = SVR(kernel='rbf', C=C, gamma=gamma, epsilon=epsilon)
            model.fit(train_data_pca, train_target)
            y_pred = model.predict(test_data_pca)
            mse = mean_squared_error(test_target, y_pred)
            mse_scores.append(mse)
        
        return np.mean(mse_scores)
    return objective

def create_nn_objective(dataset_name, cv_folds):
    def objective(trial):
        # Architecture
        n_layers = trial.suggest_int('n_layers', 1, 3)
        hidden_sizes = []
        for i in range(n_layers):
            size = trial.suggest_int(f'hidden_size_{i}', 10, 200)
            hidden_sizes.append(size)
        hidden_layer_sizes = tuple(hidden_sizes)
        
        # Other hyperparameters
        alpha = trial.suggest_float('alpha', 1e-6, 1e-2, log=True)
        learning_rate_init = trial.suggest_float('learning_rate_init', 1e-4, 1e-1, log=True)
        
        mse_scores = []
        for train_data_pca, train_target, test_data_pca, test_target in cv_folds:
            model = MLPRegressor(
                hidden_layer_sizes=hidden_layer_sizes,
                alpha=alpha,
                learning_rate_init=learning_rate_init,
                max_iter=1000,
                random_state=19890417
            )
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                model.fit(train_data_pca, train_target)
            y_pred = model.predict(test_data_pca)
            mse = mean_squared_error(test_target, y_pred)
            mse_scores.append(mse)
        
        return np.mean(mse_scores)
    return objective

def create_xgb_objective(dataset_name, cv_folds):
    def objective(trial):
        n_estimators = trial.suggest_int('n_estimators', 50, 500)
        max_depth = trial.suggest_int('max_depth', 3, 10)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3)
        subsample = trial.suggest_float('subsample', 0.6, 1.0)
        colsample_bytree = trial.suggest_float('colsample_bytree', 0.6, 1.0)
        reg_alpha = trial.suggest_float('reg_alpha', 0.0, 1.0)
        reg_lambda = trial.suggest_float('reg_lambda', 0.0, 1.0)
        
        mse_scores = []
        for train_data_pca, train_target, test_data_pca, test_target in cv_folds:
            model = XGBRegressor(
                n_estimators=n_estimators,
                max_depth=max_depth,
                learning_rate=learning_rate,
                subsample=subsample,
                colsample_bytree=colsample_bytree,
                reg_alpha=reg_alpha,
                reg_lambda=reg_lambda,
                random_state=19890417,
                verbosity=0
            )
            model.fit(train_data_pca, train_target)
            y_pred = model.predict(test_data_pca)
            mse = mean_squared_error(test_target, y_pred)
            mse_scores.append(mse)
        
        return np.mean(mse_scores)
    return objective

# Run optimization for each model and dataset
print("Starting hyperparameter optimization...")
best_params = {}

for dat in ["Ti_TM", "Ti_TE", "Si_TE", "Si_TM"]:
    print(f"\nOptimizing for dataset: {dat}")
    best_params[dat] = {}
    
    # SVR optimization
    print("  Optimizing SVR...")
    study_svr = optuna.create_study(direction='minimize', sampler=optuna.samplers.TPESampler(seed=19890417))
    study_svr.optimize(create_svr_objective(dat, PC_folds[dat]), n_trials=max_trials, show_progress_bar=True)
    best_params[dat]['svr'] = study_svr.best_params
    print(f"    Best SVR MSE: {study_svr.best_value:.6f}")
    
    # Neural Network optimization
    print("  Optimizing Neural Network...")
    study_nn = optuna.create_study(direction='minimize', sampler=optuna.samplers.TPESampler(seed=19890417))
    study_nn.optimize(create_nn_objective(dat, PC_folds[dat]), n_trials=max_trials, show_progress_bar=True)
    best_params[dat]['nn'] = study_nn.best_params
    print(f"    Best NN MSE: {study_nn.best_value:.6f}")
    
    # XGBoost optimization
    print("  Optimizing XGBoost...")
    study_xgb = optuna.create_study(direction='minimize', sampler=optuna.samplers.TPESampler(seed=19890417))
    study_xgb.optimize(create_xgb_objective(dat, PC_folds[dat]), n_trials=max_trials, show_progress_bar=True)
    best_params[dat]['xgb'] = study_xgb.best_params
    print(f"    Best XGBoost MSE: {study_xgb.best_value:.6f}")

# Train final models with optimized parameters
results_svr_optimized_dfs = {}
results_nn_optimized_dfs = {}
results_xgb_optimized_dfs = {}

print("\nTraining final models with optimized parameters...")

for dat in ["Ti_TM", "Ti_TE", "Si_TE", "Si_TM"]:
    print(f"\nTraining optimized models for {dat}...")
    
    # SVR with optimized parameters
    svr_result_list = []
    fold_i = 0
    for train_data_pca, train_target, test_data_pca, test_target in PC_folds[dat]:
        params = best_params[dat]['svr']
        model = SVR(kernel='rbf', **params)
        model.fit(train_data_pca, train_target)
        y_pred = model.predict(test_data_pca)
        
        mse = mean_squared_error(test_target, y_pred)
        r2 = r2_score(test_target, y_pred)
        rmse = np.sqrt(mse)
        mae = np.mean(np.abs(test_target - y_pred))
        
        svr_result_list.append({
            "mse": mse,
            "r2": r2,
            "rmse": rmse,
            "mae": mae,
            "fold": fold_i,
        })
        fold_i += 1
    results_svr_optimized_dfs[dat] = pd.DataFrame(svr_result_list)
    
    # Neural Network with optimized parameters
    nn_result_list = []
    fold_i = 0
    for train_data_pca, train_target, test_data_pca, test_target in PC_folds[dat]:
        params = best_params[dat]['nn'].copy()
        # Reconstruct hidden_layer_sizes tuple
        n_layers = len([k for k in params.keys() if k.startswith('hidden_size_')])
        hidden_sizes = []
        for i in range(n_layers):
            hidden_sizes.append(params.pop(f'hidden_size_{i}'))
        params['hidden_layer_sizes'] = tuple(hidden_sizes)
        params.pop('n_layers', None)
        
        model = MLPRegressor(max_iter=1000, random_state=19890417, **params)
        model.fit(train_data_pca, train_target)
        y_pred = model.predict(test_data_pca)
        
        mse = mean_squared_error(test_target, y_pred)
        r2 = r2_score(test_target, y_pred)
        rmse = np.sqrt(mse)
        mae = np.mean(np.abs(test_target - y_pred))
        
        nn_result_list.append({
            "mse": mse,
            "r2": r2,
            "rmse": rmse,
            "mae": mae,
            "fold": fold_i,
        })
        fold_i += 1
    results_nn_optimized_dfs[dat] = pd.DataFrame(nn_result_list)
    
    # XGBoost with optimized parameters
    xgb_result_list = []
    fold_i = 0
    for train_data_pca, train_target, test_data_pca, test_target in PC_folds[dat]:
        params = best_params[dat]['xgb']
        model = XGBRegressor(random_state=19890417, verbosity=0, **params)
        model.fit(train_data_pca, train_target)
        y_pred = model.predict(test_data_pca)
        
        mse = mean_squared_error(test_target, y_pred)
        r2 = r2_score(test_target, y_pred)
        rmse = np.sqrt(mse)
        mae = np.mean(np.abs(test_target - y_pred))
        
        xgb_result_list.append({
            "mse": mse,
            "r2": r2,
            "rmse": rmse,
            "mae": mae,
            "fold": fold_i,
        })
        fold_i += 1
    results_xgb_optimized_dfs[dat] = pd.DataFrame(xgb_result_list)

[I 2025-08-19 19:27:57,694] A new study created in memory with name: no-name-49b3a660-2efc-4025-81fc-8f1cba3ba6d7

Starting hyperparameter optimization...

Optimizing for dataset: Ti_TM
  Optimizing SVR...

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2025-08-19 19:27:57,728] Trial 0 finished with value: 922.33806603343 and parameters: {'C': 0.7080166777372641, 'gamma': 0.03664288488964582, 'epsilon': 0.7303805334596838}. Best is trial 0 with value: 922.33806603343.
[I 2025-08-19 19:27:57,745] Trial 1 finished with value: 920.4224004632733 and parameters: {'C': 0.716739811622706, 'gamma': 0.026605024569958235, 'epsilon': 0.009909020096150061}. Best is trial 1 with value: 920.4224004632733.
[I 2025-08-19 19:27:57,762] Trial 2 finished with value: 160.1069106516455 and parameters: {'C': 1.1072914768800126, 'gamma': 5.503780404533425e-05, 'epsilon': 0.3479369431596531}. Best is trial 2 with value: 160.1069106516455.
[I 2025-08-19 19:27:57,791] Trial 3 finished with value: 4.616285471365195 and parameters: {'C': 52.38270938257665, 'gamma': 0.0007953407290028804, 'epsilon': 0.0041235565070253995}. Best is trial 3 with value: 4.616285471365195.
[I 2025-08-19 19:27:57,813] Trial 4 finished with value: 922.9279853237564 and parameters: {'C': 0.011484946565558417, 'gamma': 3.3521156622013896e-06, 'epsilon': 0.005522897166504355}. Best is trial 3 with value: 4.616285471365195.
[I 2025-08-19 19:27:57,832] Trial 5 finished with value: 862.2291762819198 and parameters: {'C': 0.8238571129572483, 'gamma': 0.004792844142778419, 'epsilon': 0.15372812711578807}. Best is trial 3 with value: 4.616285471365195.
[I 2025-08-19 19:27:57,846] Trial 6 finished with value: 636.3287961637304 and parameters: {'C': 1.3286000153927777, 'gamma': 0.0016107068546676673, 'epsilon': 0.10201317075512983}. Best is trial 3 with value: 4.616285471365195.
[I 2025-08-19 19:27:57,872] Trial 7 finished with value: 1.0620408033256856 and parameters: {'C': 16.855013503209154, 'gamma': 8.28218838461416e-05, 'epsilon': 0.0013728944900654164}. Best is trial 7 with value: 1.0620408033256856.
[I 2025-08-19 19:27:57,886] Trial 8 finished with value: 898.2281822601293 and parameters: {'C': 0.024028914251212098, 'gamma': 4.2359234267462355e-05, 'epsilon': 0.12665147101972324}. Best is trial 7 with value: 1.0620408033256856.
[I 2025-08-19 19:27:57,908] Trial 9 finished with value: 925.634304271973 and parameters: {'C': 0.011027893465400396, 'gamma': 0.12079654162943208, 'epsilon': 0.019428094060121262}. Best is trial 7 with value: 1.0620408033256856.
[I 2025-08-19 19:27:57,995] Trial 10 finished with value: 0.0129255356331788 and parameters: {'C': 51.70222977150333, 'gamma': 3.3292485699658947e-06, 'epsilon': 0.0010253718120924727}. Best is trial 10 with value: 0.0129255356331788.
[I 2025-08-19 19:27:58,061] Trial 11 finished with value: 0.0055628123813953835 and parameters: {'C': 85.42348757968868, 'gamma': 1.1154406725445421e-06, 'epsilon': 0.0012795966681601113}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:58,100] Trial 12 finished with value: 0.023199617393583928 and parameters: {'C': 48.46159798985091, 'gamma': 1.7476210261657477e-06, 'epsilon': 0.0012143194777005564}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:58,145] Trial 13 finished with value: 2.113482037258552 and parameters: {'C': 8.372649683289024, 'gamma': 8.770101098559268e-06, 'epsilon': 0.0026978741259317237}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:58,194] Trial 14 finished with value: 0.009246972654856227 and parameters: {'C': 94.51679095184821, 'gamma': 1.0011144508177092e-06, 'epsilon': 0.03077770181525936}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:58,249] Trial 15 finished with value: 919.7387142496806 and parameters: {'C': 5.447806224186973, 'gamma': 0.8460123301163074, 'epsilon': 0.038393756884340734}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:58,280] Trial 16 finished with value: 0.008009307485236926 and parameters: {'C': 90.1489814436034, 'gamma': 1.1579936548340816e-06, 'epsilon': 0.0356921623259633}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:58,312] Trial 17 finished with value: 842.4246184232345 and parameters: {'C': 0.13401569015354817, 'gamma': 1.1384618077482095e-05, 'epsilon': 0.01338826122032564}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:58,348] Trial 18 finished with value: 4.187680448139544 and parameters: {'C': 14.205403683368278, 'gamma': 0.000316014213069673, 'epsilon': 0.05815570949375549}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:58,389] Trial 19 finished with value: 12.494126964369784 and parameters: {'C': 4.00923205241002, 'gamma': 1.5899121020453432e-05, 'epsilon': 0.006672772577687329}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:58,427] Trial 20 finished with value: 1.5197456797461943 and parameters: {'C': 24.293713547276674, 'gamma': 0.0002361217170389266, 'epsilon': 0.002669440617000856}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:58,460] Trial 21 finished with value: 0.02416558651009202 and parameters: {'C': 61.12804319076856, 'gamma': 1.249220020974622e-06, 'epsilon': 0.029559862026038705}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:58,498] Trial 22 finished with value: 0.010929989918903107 and parameters: {'C': 98.81178401185669, 'gamma': 1.0378766770201175e-06, 'epsilon': 0.06586901383694259}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:58,534] Trial 23 finished with value: 0.1946643771277049 and parameters: {'C': 25.097987020278982, 'gamma': 5.523053025049896e-06, 'epsilon': 0.28134607890219415}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:58,568] Trial 24 finished with value: 0.020505831036465867 and parameters: {'C': 95.83739498712931, 'gamma': 2.1622621550185083e-05, 'epsilon': 0.022833153232196753}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:58,599] Trial 25 finished with value: 432.07255052325746 and parameters: {'C': 2.412765335551275, 'gamma': 3.4623985950326406e-06, 'epsilon': 0.012910065834370587}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:58,636] Trial 26 finished with value: 914.8249258500069 and parameters: {'C': 0.14170910236355977, 'gamma': 1.010215423765902e-06, 'epsilon': 0.040645331458983844}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:58,661] Trial 27 finished with value: 0.6383332430529365 and parameters: {'C': 33.33626523610092, 'gamma': 2.0759354249209443e-05, 'epsilon': 0.9029951252717084}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:58,703] Trial 28 finished with value: 1.7480682211819343 and parameters: {'C': 11.553295583092657, 'gamma': 3.89980799729244e-06, 'epsilon': 0.002298287218415806}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:58,741] Trial 29 finished with value: 918.4048508332456 and parameters: {'C': 0.2667448396950702, 'gamma': 0.010487863297349041, 'epsilon': 0.3214765276813141}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:58,777] Trial 30 finished with value: 0.4222516497214007 and parameters: {'C': 98.18712761819653, 'gamma': 0.0002321864362104762, 'epsilon': 0.07596131200467136}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:58,805] Trial 31 finished with value: 0.02992168015933929 and parameters: {'C': 96.10619211411044, 'gamma': 1.1070849824004803e-06, 'epsilon': 0.19229662446702128}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:58,836] Trial 32 finished with value: 0.48290764630886845 and parameters: {'C': 29.26070946529964, 'gamma': 2.264176021813278e-06, 'epsilon': 0.5170063597050738}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:58,864] Trial 33 finished with value: 0.03991203660936081 and parameters: {'C': 42.356946895688885, 'gamma': 7.45332398608993e-06, 'epsilon': 0.05871287929804117}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:58,902] Trial 34 finished with value: 0.060761295625289646 and parameters: {'C': 67.9352684940552, 'gamma': 4.2959273427896366e-05, 'epsilon': 0.009724656498875219}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:58,934] Trial 35 finished with value: 0.40638636365854214 and parameters: {'C': 23.39521638435582, 'gamma': 2.085867330982561e-06, 'epsilon': 0.019863125837543776}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:58,968] Trial 36 finished with value: 3.7780085591416013 and parameters: {'C': 7.5228744651592985, 'gamma': 6.364737327797627e-06, 'epsilon': 0.06005760442530769}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:58,993] Trial 37 finished with value: 0.07709020339668655 and parameters: {'C': 62.7733420577349, 'gamma': 1.067579815878884e-06, 'epsilon': 0.19239036022242959}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:59,035] Trial 38 finished with value: 1.0137543757634864 and parameters: {'C': 16.084664094920072, 'gamma': 7.691892975972941e-05, 'epsilon': 0.004976753457631503}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:59,068] Trial 39 finished with value: 0.08790639015233415 and parameters: {'C': 33.38806642789753, 'gamma': 2.543999509999001e-06, 'epsilon': 0.10476928959491592}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:59,099] Trial 40 finished with value: 550.3099727707597 and parameters: {'C': 2.1267058090215603, 'gamma': 0.0018845154051968889, 'epsilon': 0.007860586853542842}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:59,135] Trial 41 finished with value: 0.010639421142492386 and parameters: {'C': 56.77684089981928, 'gamma': 3.4074159085079672e-06, 'epsilon': 0.0015625439566176321}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:59,190] Trial 42 finished with value: 0.00736671323425195 and parameters: {'C': 76.15654959929823, 'gamma': 4.481077021023596e-06, 'epsilon': 0.0019629636156787912}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:59,220] Trial 43 finished with value: 0.01842633449202277 and parameters: {'C': 47.81556976390967, 'gamma': 5.4884122152978504e-06, 'epsilon': 0.0018255165201013345}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:59,246] Trial 44 finished with value: 0.006499696315933047 and parameters: {'C': 68.6773759635658, 'gamma': 2.1119953409355203e-06, 'epsilon': 0.003925908157994881}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:59,274] Trial 45 finished with value: 0.7626773107920721 and parameters: {'C': 20.742443510861385, 'gamma': 2.043087092151609e-06, 'epsilon': 0.004147616530503975}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:59,308] Trial 46 finished with value: 0.018698592044393874 and parameters: {'C': 71.82182804596894, 'gamma': 1.155812711327863e-05, 'epsilon': 0.003583715695559655}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:59,334] Trial 47 finished with value: 470.56376925786583 and parameters: {'C': 0.5214488781500273, 'gamma': 2.7833869471003458e-05, 'epsilon': 0.0010461115578620545}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:59,373] Trial 48 finished with value: 2.507250097508904 and parameters: {'C': 11.896963360796999, 'gamma': 0.00013155504489326017, 'epsilon': 0.0018907508261091328}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:59,404] Trial 49 finished with value: 781.5096409538633 and parameters: {'C': 35.3102605747963, 'gamma': 0.03687905468577654, 'epsilon': 0.0035400034853249624}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:59,502] Trial 50 finished with value: 922.6706368546336 and parameters: {'C': 0.02232675805772785, 'gamma': 1.8002454238126348e-06, 'epsilon': 0.014097524931184702}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:59,575] Trial 51 finished with value: 0.013084975482373511 and parameters: {'C': 52.938497055015524, 'gamma': 4.1477719406863e-06, 'epsilon': 0.0014520538034367024}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:59,618] Trial 52 finished with value: 0.019000125136292435 and parameters: {'C': 70.1511725515375, 'gamma': 1.1275893330294171e-05, 'epsilon': 0.0014381405499649688}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:59,647] Trial 53 finished with value: 0.02666110102316721 and parameters: {'C': 39.26946809092624, 'gamma': 3.0667736455452e-06, 'epsilon': 0.0017300895046002884}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:59,682] Trial 54 finished with value: 0.01172416397800734 and parameters: {'C': 70.07936378616722, 'gamma': 6.3349618729682045e-06, 'epsilon': 0.002861563777000773}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:59,713] Trial 55 finished with value: 0.030504614060901637 and parameters: {'C': 46.15367600855275, 'gamma': 1.7308815363994482e-06, 'epsilon': 0.0022125463884541223}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:59,743] Trial 56 finished with value: 7.422250513503956 and parameters: {'C': 22.05765887446624, 'gamma': 0.0008254291074605873, 'epsilon': 0.005376587974765241}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:59,780] Trial 57 finished with value: 891.7935645644653 and parameters: {'C': 98.91924070822107, 'gamma': 0.667829761807425, 'epsilon': 0.0014272434192950623}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:59,811] Trial 58 finished with value: 0.35779906272988826 and parameters: {'C': 17.939819833934635, 'gamma': 3.7749503369479066e-06, 'epsilon': 0.02915683181117682}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:59,851] Trial 59 finished with value: 0.021175311906483626 and parameters: {'C': 71.31821350568353, 'gamma': 1.551767615845503e-05, 'epsilon': 0.0010209953317985756}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:59,875] Trial 60 finished with value: 146.43362340258054 and parameters: {'C': 9.392891247594024, 'gamma': 1.5976947330767639e-06, 'epsilon': 0.04063998493040548}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:59,898] Trial 61 finished with value: 0.007633279147283141 and parameters: {'C': 98.41697982723662, 'gamma': 1.4796005346737177e-06, 'epsilon': 0.08213738190162871}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:59,919] Trial 62 finished with value: 0.01740012362589229 and parameters: {'C': 56.594678302381055, 'gamma': 2.9117933686096955e-06, 'epsilon': 0.07588194803681568}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:59,944] Trial 63 finished with value: 0.42179693792665524 and parameters: {'C': 31.61793533434656, 'gamma': 1.419876067802737e-06, 'epsilon': 0.12276383154956763}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:59,964] Trial 64 finished with value: 0.009352029558534623 and parameters: {'C': 80.10770563839749, 'gamma': 4.868478011655498e-06, 'epsilon': 0.04643882390946327}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:27:59,986] Trial 65 finished with value: 0.014864084916088132 and parameters: {'C': 82.33541803426347, 'gamma': 8.413854520863729e-06, 'epsilon': 0.04482265817236996}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:28:00,010] Trial 66 finished with value: 0.26048339510161445 and parameters: {'C': 43.28213170544312, 'gamma': 1.0107067499583538e-06, 'epsilon': 0.02452936048606701}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:28:00,038] Trial 67 finished with value: 0.006290412945780419 and parameters: {'C': 99.22046045326843, 'gamma': 5.169835450288296e-06, 'epsilon': 0.015604339911334154}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:28:00,074] Trial 68 finished with value: 0.023483286519475434 and parameters: {'C': 99.2229679477298, 'gamma': 2.6467582381414052e-05, 'epsilon': 0.016296091777534914}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:28:00,096] Trial 69 finished with value: 0.4024507566014055 and parameters: {'C': 29.034722307388236, 'gamma': 1.532556314803867e-06, 'epsilon': 0.035395308802449836}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:28:00,123] Trial 70 finished with value: 917.2073148179995 and parameters: {'C': 0.04884935346304276, 'gamma': 2.3829181341501607e-06, 'epsilon': 0.010918020388395485}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:28:00,157] Trial 71 finished with value: 0.010476091293448134 and parameters: {'C': 79.80640395491008, 'gamma': 5.0949815288803834e-06, 'epsilon': 0.05142338933609837}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:28:00,192] Trial 72 finished with value: 0.03765453071104807 and parameters: {'C': 44.44008424614917, 'gamma': 9.240319714393025e-06, 'epsilon': 0.02524976232676996}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:28:00,215] Trial 73 finished with value: 0.01857385046489074 and parameters: {'C': 61.41067257870562, 'gamma': 4.585639639022115e-06, 'epsilon': 0.09418279867393559}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:28:00,241] Trial 74 finished with value: 0.008340711614248684 and parameters: {'C': 77.23591705554252, 'gamma': 2.4438795536157873e-06, 'epsilon': 0.05074471451818698}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:28:00,267] Trial 75 finished with value: 0.015460745718037447 and parameters: {'C': 53.07264289734314, 'gamma': 2.5342829699125696e-06, 'epsilon': 0.03396045517446803}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:28:00,295] Trial 76 finished with value: 0.1292904563533244 and parameters: {'C': 37.99964927237686, 'gamma': 1.454746370740241e-06, 'epsilon': 0.017259207707126897}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:28:00,321] Trial 77 finished with value: 0.024356037511690565 and parameters: {'C': 82.34637693520442, 'gamma': 1.477362762513226e-05, 'epsilon': 0.07062683156474957}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:28:00,352] Trial 78 finished with value: 0.1378521657282091 and parameters: {'C': 26.61019218539311, 'gamma': 2.701225250820734e-06, 'epsilon': 0.008277091106083379}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:28:00,376] Trial 79 finished with value: 587.1003914595422 and parameters: {'C': 4.671569475797696, 'gamma': 1.0669564577893723e-06, 'epsilon': 0.08506012209885995}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:28:00,403] Trial 80 finished with value: 117.27837050786835 and parameters: {'C': 99.58537863798956, 'gamma': 0.0038738225927039344, 'epsilon': 0.14026868435286455}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:28:00,424] Trial 81 finished with value: 0.012065052132689151 and parameters: {'C': 77.73081247471426, 'gamma': 6.85688492415316e-06, 'epsilon': 0.028260347323471435}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:28:00,445] Trial 82 finished with value: 0.018317855610486954 and parameters: {'C': 58.657413339753695, 'gamma': 1.8571928450598765e-06, 'epsilon': 0.052421029597062595}. Best is trial 11 with value: 0.0055628123813953835.
[I 2025-08-19 19:28:00,466] Trial 83 finished with value: 0.007918865947870113 and parameters: {'C': 82.13308247254436, 'gamma': 3.987999726615934e-06, 'epsilon': 0.04736433998521603}. Best is trial 11 with value: 0.0055628123813953835.

[I 2025-08-19 19:28:00,871] A new study created in memory with name: no-name-9527002d-650e-4445-b777-495ce9e39982

[I 2025-08-19 19:28:00,722] Trial 93 finished with value: 0.003867135677828648 and parameters: {'C': 84.54788530010002, 'gamma': 2.0522492088685758e-06, 'epsilon': 0.002196186971712145}. Best is trial 93 with value: 0.003867135677828648.
[I 2025-08-19 19:28:00,749] Trial 94 finished with value: 0.014380530426709354 and parameters: {'C': 51.284483120149375, 'gamma': 2.1413864596216778e-06, 'epsilon': 0.0023413424119241226}. Best is trial 93 with value: 0.003867135677828648.
[I 2025-08-19 19:28:00,774] Trial 95 finished with value: 0.00866803183000404 and parameters: {'C': 62.08506167573479, 'gamma': 3.9556077573473165e-06, 'epsilon': 0.003994291743386165}. Best is trial 93 with value: 0.003867135677828648.
[I 2025-08-19 19:28:00,802] Trial 96 finished with value: 0.008263356895795635 and parameters: {'C': 85.26022141387782, 'gamma': 6.09671592548126e-06, 'epsilon': 0.0022890035039222194}. Best is trial 93 with value: 0.003867135677828648.
[I 2025-08-19 19:28:00,826] Trial 97 finished with value: 791.4273317396995 and parameters: {'C': 1.371301697543672, 'gamma': 1.357037716866051e-06, 'epsilon': 0.0032165356465400615}. Best is trial 93 with value: 0.003867135677828648.
[I 2025-08-19 19:28:00,845] Trial 98 finished with value: 0.15393345681644796 and parameters: {'C': 30.181492765793315, 'gamma': 1.9174912577175443e-06, 'epsilon': 0.0019896394391790795}. Best is trial 93 with value: 0.003867135677828648.
[I 2025-08-19 19:28:00,868] Trial 99 finished with value: 0.007449604188890818 and parameters: {'C': 65.53011463558447, 'gamma': 3.3183163010131474e-06, 'epsilon': 0.009882385180593834}. Best is trial 93 with value: 0.003867135677828648.
    Best SVR MSE: 0.003867
  Optimizing Neural Network...

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2025-08-19 19:28:02,350] Trial 0 finished with value: 0.8432372976338292 and parameters: {'n_layers': 2, 'hidden_size_0': 155, 'hidden_size_1': 192, 'alpha': 7.167398116227066e-05, 'learning_rate_init': 0.016311046738317646}. Best is trial 0 with value: 0.8432372976338292.
[I 2025-08-19 19:28:02,495] Trial 1 finished with value: 3.7617917546584536 and parameters: {'n_layers': 1, 'hidden_size_0': 107, 'alpha': 1.4469073799463473e-05, 'learning_rate_init': 0.03479369431596534}. Best is trial 0 with value: 0.8432372976338292.
[I 2025-08-19 19:28:03,408] Trial 2 finished with value: 0.4867332135596669 and parameters: {'n_layers': 3, 'hidden_size_0': 102, 'hidden_size_1': 49, 'hidden_size_2': 12, 'alpha': 2.239817654479077e-06, 'learning_rate_init': 0.0005522897166504359}. Best is trial 2 with value: 0.4867332135596669.
[I 2025-08-19 19:28:04,043] Trial 3 finished with value: 1.2120350370521875 and parameters: {'n_layers': 2, 'hidden_size_0': 127, 'hidden_size_1': 149, 'alpha': 0.00013286000153927766, 'learning_rate_init': 0.004013361252949541}. Best is trial 2 with value: 0.4867332135596669.
[I 2025-08-19 19:28:05,918] Trial 4 finished with value: 0.5276181006716119 and parameters: {'n_layers': 3, 'hidden_size_0': 164, 'hidden_size_1': 71, 'hidden_size_2': 18, 'alpha': 2.4028914251212117e-06, 'learning_rate_init': 0.0006508397211868865}. Best is trial 2 with value: 0.4867332135596669.
[I 2025-08-19 19:28:06,367] Trial 5 finished with value: 48.77011228603429 and parameters: {'n_layers': 3, 'hidden_size_0': 12, 'hidden_size_1': 171, 'hidden_size_2': 92, 'alpha': 3.31245933388589e-05, 'learning_rate_init': 0.0475469046012784}. Best is trial 2 with value: 0.4867332135596669.
[I 2025-08-19 19:28:07,872] Trial 6 finished with value: 0.8358903236381015 and parameters: {'n_layers': 3, 'hidden_size_0': 149, 'hidden_size_1': 93, 'hidden_size_2': 62, 'alpha': 0.0008307038575919792, 'learning_rate_init': 0.0006247417454051523}. Best is trial 2 with value: 0.4867332135596669.
[I 2025-08-19 19:28:09,148] Trial 7 finished with value: 173.95651749046775 and parameters: {'n_layers': 1, 'hidden_size_0': 42, 'alpha': 2.003017770189989e-05, 'learning_rate_init': 0.00010288226798899776}. Best is trial 2 with value: 0.4867332135596669.
[I 2025-08-19 19:28:09,382] Trial 8 finished with value: 6.7409222311842685 and parameters: {'n_layers': 2, 'hidden_size_0': 47, 'hidden_size_1': 133, 'alpha': 5.0121585016886075e-06, 'learning_rate_init': 0.029839538215823313}. Best is trial 2 with value: 0.4867332135596669.
[I 2025-08-19 19:28:09,510] Trial 9 finished with value: 14.987412243362007 and parameters: {'n_layers': 2, 'hidden_size_0': 14, 'hidden_size_1': 133, 'alpha': 1.82655565832615e-06, 'learning_rate_init': 0.024608957414494176}. Best is trial 2 with value: 0.4867332135596669.
[I 2025-08-19 19:28:12,526] Trial 10 finished with value: 1.0504755829575991 and parameters: {'n_layers': 3, 'hidden_size_0': 76, 'hidden_size_1': 10, 'hidden_size_2': 192, 'alpha': 0.009579480611214039, 'learning_rate_init': 0.0001279596668160112}. Best is trial 2 with value: 0.4867332135596669.
[I 2025-08-19 19:28:13,224] Trial 11 finished with value: 4.568888071725315 and parameters: {'n_layers': 3, 'hidden_size_0': 200, 'hidden_size_1': 57, 'hidden_size_2': 21, 'alpha': 1.4735234191302077e-06, 'learning_rate_init': 0.0008973977753066866}. Best is trial 2 with value: 0.4867332135596669.
[I 2025-08-19 19:28:14,435] Trial 12 finished with value: 0.9030740757425522 and parameters: {'n_layers': 3, 'hidden_size_0': 183, 'hidden_size_1': 61, 'hidden_size_2': 10, 'alpha': 5.5265922018765535e-06, 'learning_rate_init': 0.0006441494607252907}. Best is trial 2 with value: 0.4867332135596669.
[I 2025-08-19 19:28:14,577] Trial 13 finished with value: 8.144118802335134 and parameters: {'n_layers': 3, 'hidden_size_0': 94, 'hidden_size_1': 40, 'hidden_size_2': 51, 'alpha': 1.5582582203062537e-06, 'learning_rate_init': 0.002618971599170178}. Best is trial 2 with value: 0.4867332135596669.
[I 2025-08-19 19:28:17,421] Trial 14 finished with value: 0.5267214825681001 and parameters: {'n_layers': 3, 'hidden_size_0': 135, 'hidden_size_1': 90, 'hidden_size_2': 137, 'alpha': 0.00030575759352265825, 'learning_rate_init': 0.00031256598782533374}. Best is trial 2 with value: 0.4867332135596669.
[I 2025-08-19 19:28:19,967] Trial 15 finished with value: 0.5898603675325507 and parameters: {'n_layers': 2, 'hidden_size_0': 122, 'hidden_size_1': 99, 'alpha': 0.000565166804815854, 'learning_rate_init': 0.00020662089070488756}. Best is trial 2 with value: 0.4867332135596669.
[I 2025-08-19 19:28:21,296] Trial 16 finished with value: 0.9080191020553048 and parameters: {'n_layers': 3, 'hidden_size_0': 79, 'hidden_size_1': 22, 'hidden_size_2': 151, 'alpha': 0.000367514480261099, 'learning_rate_init': 0.00029162045705949483}. Best is trial 2 with value: 0.4867332135596669.
[I 2025-08-19 19:28:21,511] Trial 17 finished with value: 21.803654712576503 and parameters: {'n_layers': 2, 'hidden_size_0': 132, 'hidden_size_1': 76, 'alpha': 0.002656134279370658, 'learning_rate_init': 0.002003259421522913}. Best is trial 2 with value: 0.4867332135596669.
[I 2025-08-19 19:28:22,966] Trial 18 finished with value: 1.3081178994905454 and parameters: {'n_layers': 1, 'hidden_size_0': 99, 'alpha': 0.00020351592556499854, 'learning_rate_init': 0.0003038495822843854}. Best is trial 2 with value: 0.4867332135596669.
[I 2025-08-19 19:28:23,294] Trial 19 finished with value: 12.703517186292803 and parameters: {'n_layers': 3, 'hidden_size_0': 67, 'hidden_size_1': 40, 'hidden_size_2': 129, 'alpha': 0.0016373200566472048, 'learning_rate_init': 0.004809038719233302}. Best is trial 2 with value: 0.4867332135596669.
[I 2025-08-19 19:28:23,449] Trial 20 finished with value: 770.8660385933056 and parameters: {'n_layers': 2, 'hidden_size_0': 141, 'hidden_size_1': 108, 'alpha': 5.904238191391142e-05, 'learning_rate_init': 0.09447938304283673}. Best is trial 2 with value: 0.4867332135596669.
[I 2025-08-19 19:28:23,835] Trial 21 finished with value: 21.005784326458862 and parameters: {'n_layers': 3, 'hidden_size_0': 168, 'hidden_size_1': 79, 'hidden_size_2': 40, 'alpha': 5.105651587085344e-06, 'learning_rate_init': 0.0013616678248519682}. Best is trial 2 with value: 0.4867332135596669.
[I 2025-08-19 19:28:26,048] Trial 22 finished with value: 0.4723374116350339 and parameters: {'n_layers': 3, 'hidden_size_0': 176, 'hidden_size_1': 57, 'hidden_size_2': 93, 'alpha': 1.1525057364160255e-05, 'learning_rate_init': 0.0004362112401612418}. Best is trial 22 with value: 0.4723374116350339.
[I 2025-08-19 19:28:28,262] Trial 23 finished with value: 0.5195052620927996 and parameters: {'n_layers': 3, 'hidden_size_0': 181, 'hidden_size_1': 44, 'hidden_size_2': 98, 'alpha': 1.270445631462451e-05, 'learning_rate_init': 0.0003402116743260814}. Best is trial 22 with value: 0.4723374116350339.
[I 2025-08-19 19:28:29,252] Trial 24 finished with value: 0.4473968934500456 and parameters: {'n_layers': 3, 'hidden_size_0': 198, 'hidden_size_1': 40, 'hidden_size_2': 88, 'alpha': 8.883368038870933e-06, 'learning_rate_init': 0.0012861484382983065}. Best is trial 24 with value: 0.4473968934500456.
[I 2025-08-19 19:28:29,776] Trial 25 finished with value: 15.316139860037861 and parameters: {'n_layers': 3, 'hidden_size_0': 194, 'hidden_size_1': 25, 'hidden_size_2': 78, 'alpha': 5.784148386119281e-06, 'learning_rate_init': 0.00824499068398444}. Best is trial 24 with value: 0.4473968934500456.
[I 2025-08-19 19:28:30,139] Trial 26 finished with value: 13.74006921721622 and parameters: {'n_layers': 3, 'hidden_size_0': 175, 'hidden_size_1': 57, 'hidden_size_2': 117, 'alpha': 3.4296299669290926e-05, 'learning_rate_init': 0.0013846321824739964}. Best is trial 24 with value: 0.4473968934500456.
[I 2025-08-19 19:28:30,451] Trial 27 finished with value: 3.270266814369761 and parameters: {'n_layers': 2, 'hidden_size_0': 117, 'hidden_size_1': 26, 'alpha': 9.42946961776238e-06, 'learning_rate_init': 0.0012084035442932759}. Best is trial 24 with value: 0.4473968934500456.
[I 2025-08-19 19:28:33,376] Trial 28 finished with value: 0.5871773448508139 and parameters: {'n_layers': 3, 'hidden_size_0': 187, 'hidden_size_1': 115, 'hidden_size_2': 165, 'alpha': 3.6748137586527135e-06, 'learning_rate_init': 0.00045669747170143957}. Best is trial 24 with value: 0.4473968934500456.
[I 2025-08-19 19:28:33,726] Trial 29 finished with value: 14.801835990999166 and parameters: {'n_layers': 2, 'hidden_size_0': 158, 'hidden_size_1': 47, 'alpha': 5.214488781500273e-05, 'learning_rate_init': 0.007542367462218732}. Best is trial 24 with value: 0.4473968934500456.
[I 2025-08-19 19:28:36,588] Trial 30 finished with value: 0.45627393633893404 and parameters: {'n_layers': 3, 'hidden_size_0': 146, 'hidden_size_1': 11, 'hidden_size_2': 78, 'alpha': 1.1292703573366097e-06, 'learning_rate_init': 0.00018373320375177947}. Best is trial 24 with value: 0.4473968934500456.
[I 2025-08-19 19:28:39,900] Trial 31 finished with value: 0.6745890114151801 and parameters: {'n_layers': 3, 'hidden_size_0': 150, 'hidden_size_1': 16, 'hidden_size_2': 80, 'alpha': 1.1498536606562435e-06, 'learning_rate_init': 0.00017261027166076923}. Best is trial 24 with value: 0.4473968934500456.
[I 2025-08-19 19:28:41,929] Trial 32 finished with value: 0.47088396294288914 and parameters: {'n_layers': 3, 'hidden_size_0': 109, 'hidden_size_1': 32, 'hidden_size_2': 110, 'alpha': 2.944515798712252e-06, 'learning_rate_init': 0.00017819389405938197}. Best is trial 24 with value: 0.4473968934500456.
[I 2025-08-19 19:28:46,014] Trial 33 finished with value: 0.8741184755944273 and parameters: {'n_layers': 3, 'hidden_size_0': 170, 'hidden_size_1': 11, 'hidden_size_2': 108, 'alpha': 9.576915567824426e-06, 'learning_rate_init': 0.00018604424462460075}. Best is trial 24 with value: 0.4473968934500456.
[I 2025-08-19 19:28:48,370] Trial 34 finished with value: 0.9683021608141653 and parameters: {'n_layers': 3, 'hidden_size_0': 114, 'hidden_size_1': 32, 'hidden_size_2': 76, 'alpha': 2.8415188351482617e-06, 'learning_rate_init': 0.00013638461952905276}. Best is trial 24 with value: 0.4473968934500456.
[I 2025-08-19 19:28:51,304] Trial 35 finished with value: 0.5816137573758313 and parameters: {'n_layers': 3, 'hidden_size_0': 191, 'hidden_size_1': 30, 'hidden_size_2': 90, 'alpha': 1.0283623530642035e-06, 'learning_rate_init': 0.0003856110385746639}. Best is trial 24 with value: 0.4473968934500456.
[I 2025-08-19 19:28:54,134] Trial 36 finished with value: 0.9966859187341072 and parameters: {'n_layers': 1, 'hidden_size_0': 162, 'alpha': 1.689804853343851e-05, 'learning_rate_init': 0.00022989104891989626}. Best is trial 24 with value: 0.4473968934500456.
[I 2025-08-19 19:28:54,832] Trial 37 finished with value: 1.0529064511345134 and parameters: {'n_layers': 3, 'hidden_size_0': 144, 'hidden_size_1': 58, 'hidden_size_2': 117, 'alpha': 0.00011282943984976962, 'learning_rate_init': 0.0008750882939105075}. Best is trial 24 with value: 0.4473968934500456.
[I 2025-08-19 19:28:57,579] Trial 38 finished with value: 0.4399351591974778 and parameters: {'n_layers': 3, 'hidden_size_0': 177, 'hidden_size_1': 35, 'hidden_size_2': 61, 'alpha': 2.940046883614416e-06, 'learning_rate_init': 0.0004763930465233728}. Best is trial 38 with value: 0.4399351591974778.
[I 2025-08-19 19:29:06,834] Trial 39 finished with value: 0.817009211545886 and parameters: {'n_layers': 2, 'hidden_size_0': 199, 'hidden_size_1': 38, 'alpha': 2.8091672281379968e-06, 'learning_rate_init': 0.00010083131549969856}. Best is trial 38 with value: 0.4399351591974778.
[I 2025-08-19 19:29:08,161] Trial 40 finished with value: 10.652055619329099 and parameters: {'n_layers': 3, 'hidden_size_0': 156, 'hidden_size_1': 196, 'hidden_size_2': 59, 'alpha': 2.514748742614831e-05, 'learning_rate_init': 0.001980741519257006}. Best is trial 38 with value: 0.4399351591974778.
[I 2025-08-19 19:29:09,938] Trial 41 finished with value: 2.3242762895993865 and parameters: {'n_layers': 3, 'hidden_size_0': 176, 'hidden_size_1': 20, 'hidden_size_2': 71, 'alpha': 8.81892753473231e-06, 'learning_rate_init': 0.0004879597781127805}. Best is trial 38 with value: 0.4399351591974778.
[I 2025-08-19 19:29:12,017] Trial 42 finished with value: 0.5498618251034719 and parameters: {'n_layers': 3, 'hidden_size_0': 185, 'hidden_size_1': 51, 'hidden_size_2': 42, 'alpha': 2.166757565544989e-06, 'learning_rate_init': 0.0008569781619924055}. Best is trial 38 with value: 0.4399351591974778.
[I 2025-08-19 19:29:17,675] Trial 43 finished with value: 0.38653450873999323 and parameters: {'n_layers': 3, 'hidden_size_0': 167, 'hidden_size_1': 69, 'hidden_size_2': 108, 'alpha': 3.895048919655879e-06, 'learning_rate_init': 0.00023554339961074828}. Best is trial 43 with value: 0.38653450873999323.
[I 2025-08-19 19:29:24,956] Trial 44 finished with value: 0.679623537810459 and parameters: {'n_layers': 3, 'hidden_size_0': 165, 'hidden_size_1': 65, 'hidden_size_2': 105, 'alpha': 3.417138072805868e-06, 'learning_rate_init': 0.0001531292562660883}. Best is trial 43 with value: 0.38653450873999323.
[I 2025-08-19 19:29:28,391] Trial 45 finished with value: 0.8872544228274712 and parameters: {'n_layers': 3, 'hidden_size_0': 150, 'hidden_size_1': 32, 'hidden_size_2': 121, 'alpha': 6.95094398464146e-06, 'learning_rate_init': 0.00026199644453856743}. Best is trial 43 with value: 0.38653450873999323.
[I 2025-08-19 19:29:30,206] Trial 46 finished with value: 3.463019375373451 and parameters: {'n_layers': 3, 'hidden_size_0': 106, 'hidden_size_1': 85, 'hidden_size_2': 70, 'alpha': 1.7546159959576787e-06, 'learning_rate_init': 0.0006387253495279345}. Best is trial 43 with value: 0.38653450873999323.
[I 2025-08-19 19:29:38,067] Trial 47 finished with value: 0.853845756034475 and parameters: {'n_layers': 3, 'hidden_size_0': 129, 'hidden_size_1': 164, 'hidden_size_2': 106, 'alpha': 1.0036859582589686e-06, 'learning_rate_init': 0.0002143253029564054}. Best is trial 43 with value: 0.38653450873999323.
[I 2025-08-19 19:29:46,016] Trial 48 finished with value: 0.6833566634265122 and parameters: {'n_layers': 3, 'hidden_size_0': 191, 'hidden_size_1': 69, 'hidden_size_2': 87, 'alpha': 4.18069833579815e-06, 'learning_rate_init': 0.00014229564664842238}. Best is trial 43 with value: 0.38653450873999323.
[I 2025-08-19 19:29:48,451] Trial 49 finished with value: 0.8068815425428095 and parameters: {'n_layers': 3, 'hidden_size_0': 137, 'hidden_size_1': 11, 'hidden_size_2': 61, 'alpha': 2.1495244408360677e-06, 'learning_rate_init': 0.0005402345411376773}. Best is trial 43 with value: 0.38653450873999323.
[I 2025-08-19 19:29:48,988] Trial 50 finished with value: 2.1642884558421756 and parameters: {'n_layers': 2, 'hidden_size_0': 86, 'hidden_size_1': 33, 'alpha': 1.4915851925702686e-06, 'learning_rate_init': 0.0010349716099646914}. Best is trial 43 with value: 0.38653450873999323.
[I 2025-08-19 19:29:52,707] Trial 51 finished with value: 0.9715272854037884 and parameters: {'n_layers': 3, 'hidden_size_0': 175, 'hidden_size_1': 50, 'hidden_size_2': 95, 'alpha': 3.459080654864452e-06, 'learning_rate_init': 0.0003644528316989327}. Best is trial 43 with value: 0.38653450873999323.
[I 2025-08-19 19:29:57,979] Trial 52 finished with value: 0.49772703518858974 and parameters: {'n_layers': 3, 'hidden_size_0': 177, 'hidden_size_1': 48, 'hidden_size_2': 85, 'alpha': 1.2147345667756441e-05, 'learning_rate_init': 0.000251287088649081}. Best is trial 43 with value: 0.38653450873999323.
[I 2025-08-19 19:30:00,911] Trial 53 finished with value: 0.5798936230019621 and parameters: {'n_layers': 3, 'hidden_size_0': 199, 'hidden_size_1': 19, 'hidden_size_2': 100, 'alpha': 6.60131560014847e-06, 'learning_rate_init': 0.0004263425253501848}. Best is trial 43 with value: 0.38653450873999323.
[I 2025-08-19 19:30:02,167] Trial 54 finished with value: 4.889984495063347 and parameters: {'n_layers': 3, 'hidden_size_0': 167, 'hidden_size_1': 37, 'hidden_size_2': 134, 'alpha': 2.529539009506549e-06, 'learning_rate_init': 0.0007593388201227932}. Best is trial 43 with value: 0.38653450873999323.
[I 2025-08-19 19:30:09,689] Trial 55 finished with value: 1.2900283679972149 and parameters: {'n_layers': 3, 'hidden_size_0': 156, 'hidden_size_1': 72, 'hidden_size_2': 113, 'alpha': 2.3229679612469803e-05, 'learning_rate_init': 0.00010793179756018865}. Best is trial 43 with value: 0.38653450873999323.
[I 2025-08-19 19:30:10,237] Trial 56 finished with value: 1.4968786167068104 and parameters: {'n_layers': 1, 'hidden_size_0': 47, 'alpha': 4.544672380112525e-06, 'learning_rate_init': 0.0017190675479620962}. Best is trial 43 with value: 0.38653450873999323.
[I 2025-08-19 19:30:10,527] Trial 57 finished with value: 14.168267053675994 and parameters: {'n_layers': 3, 'hidden_size_0': 148, 'hidden_size_1': 63, 'hidden_size_2': 68, 'alpha': 7.937556619334228e-06, 'learning_rate_init': 0.0026672880595195376}. Best is trial 43 with value: 0.38653450873999323.
[I 2025-08-19 19:30:15,565] Trial 58 finished with value: 0.8388477080110146 and parameters: {'n_layers': 3, 'hidden_size_0': 182, 'hidden_size_1': 54, 'hidden_size_2': 92, 'alpha': 4.072373997945149e-05, 'learning_rate_init': 0.0001691226237563749}. Best is trial 43 with value: 0.38653450873999323.
[I 2025-08-19 19:30:16,970] Trial 59 finished with value: 1.4293133844953556 and parameters: {'n_layers': 3, 'hidden_size_0': 172, 'hidden_size_1': 43, 'hidden_size_2': 32, 'alpha': 1.4700849177742253e-05, 'learning_rate_init': 0.0006440726391608523}. Best is trial 43 with value: 0.38653450873999323.
[I 2025-08-19 19:30:20,222] Trial 60 finished with value: 0.507305489713171 and parameters: {'n_layers': 3, 'hidden_size_0': 162, 'hidden_size_1': 82, 'hidden_size_2': 126, 'alpha': 1.4285057526648174e-06, 'learning_rate_init': 0.00029789837366363736}. Best is trial 43 with value: 0.38653450873999323.
[I 2025-08-19 19:30:21,609] Trial 61 finished with value: 0.4724908719372628 and parameters: {'n_layers': 3, 'hidden_size_0': 102, 'hidden_size_1': 40, 'hidden_size_2': 19, 'alpha': 1.8617518573875604e-06, 'learning_rate_init': 0.0005208892292467418}. Best is trial 43 with value: 0.38653450873999323.
[I 2025-08-19 19:30:23,754] Trial 62 finished with value: 0.8934951462710521 and parameters: {'n_layers': 3, 'hidden_size_0': 93, 'hidden_size_1': 25, 'hidden_size_2': 24, 'alpha': 2.2162043646140237e-06, 'learning_rate_init': 0.0004913295531054524}. Best is trial 43 with value: 0.38653450873999323.
[I 2025-08-19 19:30:25,475] Trial 63 finished with value: 1.0638916738094508 and parameters: {'n_layers': 3, 'hidden_size_0': 70, 'hidden_size_1': 36, 'hidden_size_2': 54, 'alpha': 5.070265613696624e-06, 'learning_rate_init': 0.00037341627689885004}. Best is trial 43 with value: 0.38653450873999323.
[I 2025-08-19 19:30:28,845] Trial 64 finished with value: 1.065361616073734 and parameters: {'n_layers': 3, 'hidden_size_0': 113, 'hidden_size_1': 17, 'hidden_size_2': 49, 'alpha': 1.4231100963566066e-06, 'learning_rate_init': 0.00020292329491529394}. Best is trial 43 with value: 0.38653450873999323.
[I 2025-08-19 19:30:31,149] Trial 65 finished with value: 0.6843840046868579 and parameters: {'n_layers': 3, 'hidden_size_0': 124, 'hidden_size_1': 44, 'hidden_size_2': 12, 'alpha': 2.9763954926883656e-06, 'learning_rate_init': 0.0002602564985281586}. Best is trial 43 with value: 0.38653450873999323.
[I 2025-08-19 19:30:31,732] Trial 66 finished with value: 13.96107882699236 and parameters: {'n_layers': 3, 'hidden_size_0': 188, 'hidden_size_1': 27, 'hidden_size_2': 150, 'alpha': 1.8702964707949462e-06, 'learning_rate_init': 0.0007757990605427605}. Best is trial 43 with value: 0.38653450873999323.
[I 2025-08-19 19:30:32,612] Trial 67 finished with value: 0.7018703067079396 and parameters: {'n_layers': 3, 'hidden_size_0': 101, 'hidden_size_1': 97, 'hidden_size_2': 82, 'alpha': 8.59142134715976e-05, 'learning_rate_init': 0.0037169873951486665}. Best is trial 43 with value: 0.38653450873999323.

[I 2025-08-19 19:32:22,050] A new study created in memory with name: no-name-f9ed3140-8ea2-4b3d-a073-da84298c35ac

[I 2025-08-19 19:32:22,047] Trial 99 finished with value: 0.9348139030597931 and parameters: {'n_layers': 3, 'hidden_size_0': 185, 'hidden_size_1': 58, 'hidden_size_2': 55, 'alpha': 1.6415936937177499e-06, 'learning_rate_init': 0.0002145972390107328}. Best is trial 70 with value: 0.28845176484818424.
    Best NN MSE: 0.288452
  Optimizing XGBoost...

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2025-08-19 19:32:22,982] Trial 0 finished with value: 2.111865997314453 and parameters: {'n_estimators': 258, 'max_depth': 9, 'learning_rate': 0.2868097549949875, 'subsample': 0.7855361528214284, 'colsample_bytree': 0.8949975776223627, 'reg_alpha': 0.3320102363966625, 'reg_lambda': 0.5110654892617195}. Best is trial 0 with value: 2.111865997314453.
[I 2025-08-19 19:32:23,941] Trial 1 finished with value: 219.9090362548828 and parameters: {'n_estimators': 180, 'max_depth': 9, 'learning_rate': 0.2796411269270747, 'subsample': 0.7933702148684326, 'colsample_bytree': 0.6820362600374056, 'reg_alpha': 0.015032244738287792, 'reg_lambda': 0.08755316586959205}. Best is trial 0 with value: 2.111865997314453.
[I 2025-08-19 19:32:25,001] Trial 2 finished with value: 34.78501472473145 and parameters: {'n_estimators': 161, 'max_depth': 6, 'learning_rate': 0.1878953431482189, 'subsample': 0.8915671114884505, 'colsample_bytree': 0.8123394253137142, 'reg_alpha': 0.5345027511515238, 'reg_lambda': 0.6695520821461635}. Best is trial 0 with value: 2.111865997314453.
[I 2025-08-19 19:32:27,996] Trial 3 finished with value: 16.08736934661865 and parameters: {'n_estimators': 413, 'max_depth': 5, 'learning_rate': 0.02330492566401024, 'subsample': 0.6380734147609546, 'colsample_bytree': 0.7084632067144855, 'reg_alpha': 0.7008700794530022, 'reg_lambda': 0.010623140491635374}. Best is trial 0 with value: 2.111865997314453.
[I 2025-08-19 19:32:29,568] Trial 4 finished with value: 2.13508026599884 and parameters: {'n_estimators': 432, 'max_depth': 6, 'learning_rate': 0.12021091525697909, 'subsample': 0.9569496331670797, 'colsample_bytree': 0.870226990068316, 'reg_alpha': 0.7312240315039474, 'reg_lambda': 0.435093453351329}. Best is trial 0 with value: 2.111865997314453.
[I 2025-08-19 19:32:31,316] Trial 5 finished with value: 66.63917846679688 and parameters: {'n_estimators': 173, 'max_depth': 8, 'learning_rate': 0.08691771756991429, 'subsample': 0.6088455034591104, 'colsample_bytree': 0.6681143463440867, 'reg_alpha': 0.32542120056118984, 'reg_lambda': 0.0041135098313099805}. Best is trial 0 with value: 2.111865997314453.
[I 2025-08-19 19:32:32,473] Trial 6 finished with value: 1.5817189693450928 and parameters: {'n_estimators': 247, 'max_depth': 4, 'learning_rate': 0.19806639115434782, 'subsample': 0.6700024796424326, 'colsample_bytree': 0.9299722797191209, 'reg_alpha': 0.43794163794797203, 'reg_lambda': 0.02396063029390616}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:32:33,214] Trial 7 finished with value: 25.5027795791626 and parameters: {'n_estimators': 342, 'max_depth': 3, 'learning_rate': 0.24113901075722252, 'subsample': 0.7850682737528474, 'colsample_bytree': 0.8073724882416142, 'reg_alpha': 0.01937463403047257, 'reg_lambda': 0.9363830553724265}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:32:33,822] Trial 8 finished with value: 6.200183582305908 and parameters: {'n_estimators': 78, 'max_depth': 5, 'learning_rate': 0.2929950878885234, 'subsample': 0.8283459221308414, 'colsample_bytree': 0.8479684819767384, 'reg_alpha': 0.342864361117479, 'reg_lambda': 0.475341108248701}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:32:37,355] Trial 9 finished with value: 23.364721488952636 and parameters: {'n_estimators': 472, 'max_depth': 4, 'learning_rate': 0.032558088778383364, 'subsample': 0.8489797501078457, 'colsample_bytree': 0.7548199148748489, 'reg_alpha': 0.5163822278837185, 'reg_lambda': 0.9659068497351706}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:32:38,832] Trial 10 finished with value: 1.8955047130584717 and parameters: {'n_estimators': 335, 'max_depth': 3, 'learning_rate': 0.1872848218450139, 'subsample': 0.6993642643004209, 'colsample_bytree': 0.9981341962753011, 'reg_alpha': 0.9258835810465541, 'reg_lambda': 0.22988284856541494}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:32:39,805] Trial 11 finished with value: 1.9491867542266845 and parameters: {'n_estimators': 309, 'max_depth': 3, 'learning_rate': 0.18997222684394377, 'subsample': 0.6929233501126211, 'colsample_bytree': 0.995825475924077, 'reg_alpha': 0.9938772419949407, 'reg_lambda': 0.2335631727203537}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:32:40,877] Trial 12 finished with value: 1.7911783933639527 and parameters: {'n_estimators': 249, 'max_depth': 3, 'learning_rate': 0.19912928235442232, 'subsample': 0.6951200153014897, 'colsample_bytree': 0.9954960824170772, 'reg_alpha': 0.9859926578458946, 'reg_lambda': 0.24217586412147524}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:32:41,899] Trial 13 finished with value: 1.9936525344848632 and parameters: {'n_estimators': 241, 'max_depth': 4, 'learning_rate': 0.22443310004350467, 'subsample': 0.6990065728721915, 'colsample_bytree': 0.9421485025788295, 'reg_alpha': 0.7661596842270053, 'reg_lambda': 0.27349321550692984}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:32:42,798] Trial 14 finished with value: 1.6340274095535279 and parameters: {'n_estimators': 84, 'max_depth': 7, 'learning_rate': 0.14380863867521615, 'subsample': 0.733412795749345, 'colsample_bytree': 0.940854634390738, 'reg_alpha': 0.20804353733041508, 'reg_lambda': 0.1641748422189292}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:32:43,544] Trial 15 finished with value: 136.40044555664062 and parameters: {'n_estimators': 75, 'max_depth': 7, 'learning_rate': 0.1413785629216363, 'subsample': 0.7451515388781427, 'colsample_bytree': 0.6073046007031884, 'reg_alpha': 0.1752912865515978, 'reg_lambda': 0.1305544584735739}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:32:45,207] Trial 16 finished with value: 2.4082825660705565 and parameters: {'n_estimators': 117, 'max_depth': 10, 'learning_rate': 0.09876984395944828, 'subsample': 0.6535963526911596, 'colsample_bytree': 0.9229297720745212, 'reg_alpha': 0.17883504477150766, 'reg_lambda': 0.3672136347228592}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:32:45,952] Trial 17 finished with value: 1.781727170944214 and parameters: {'n_estimators': 50, 'max_depth': 7, 'learning_rate': 0.15644962725499267, 'subsample': 0.7472624489711909, 'colsample_bytree': 0.9311333564015557, 'reg_alpha': 0.4413291839299185, 'reg_lambda': 0.6462441610670564}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:32:47,149] Trial 18 finished with value: 1.7738894701004029 and parameters: {'n_estimators': 128, 'max_depth': 8, 'learning_rate': 0.0652052151960141, 'subsample': 0.7477373917970433, 'colsample_bytree': 0.9542888931415013, 'reg_alpha': 0.1582339851325661, 'reg_lambda': 0.12434561812259648}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:32:48,925] Trial 19 finished with value: 2.1158170223236086 and parameters: {'n_estimators': 204, 'max_depth': 5, 'learning_rate': 0.1498564406380478, 'subsample': 0.6416215753121858, 'colsample_bytree': 0.8604762311443335, 'reg_alpha': 0.6148944472427522, 'reg_lambda': 0.6138822345550484}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:32:50,321] Trial 20 finished with value: 37.30540523529053 and parameters: {'n_estimators': 396, 'max_depth': 6, 'learning_rate': 0.25558591593576174, 'subsample': 0.9976484536230416, 'colsample_bytree': 0.7665910275290476, 'reg_alpha': 0.4098328076665084, 'reg_lambda': 0.3361711609559096}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:32:52,068] Trial 21 finished with value: 1.7909356594085692 and parameters: {'n_estimators': 129, 'max_depth': 8, 'learning_rate': 0.06202579745618032, 'subsample': 0.742491949303143, 'colsample_bytree': 0.956087580763954, 'reg_alpha': 0.20795349615640846, 'reg_lambda': 0.12728419100777552}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:32:53,275] Trial 22 finished with value: 2.6198801040649413 and parameters: {'n_estimators': 118, 'max_depth': 8, 'learning_rate': 0.05393464230122257, 'subsample': 0.6693538666521399, 'colsample_bytree': 0.9005437386204713, 'reg_alpha': 0.11336267027918578, 'reg_lambda': 0.126201570128542}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:32:54,905] Trial 23 finished with value: 1.8656720161437987 and parameters: {'n_estimators': 211, 'max_depth': 7, 'learning_rate': 0.12023825116138163, 'subsample': 0.738949917084377, 'colsample_bytree': 0.9613348125272682, 'reg_alpha': 0.257263302233113, 'reg_lambda': 0.05837519202509454}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:32:55,799] Trial 24 finished with value: 1.8718343496322631 and parameters: {'n_estimators': 139, 'max_depth': 9, 'learning_rate': 0.21437884662412385, 'subsample': 0.721733873557414, 'colsample_bytree': 0.9018155048512784, 'reg_alpha': 0.13092092351144727, 'reg_lambda': 0.19467602737463632}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:32:57,205] Trial 25 finished with value: 1.7744763374328614 and parameters: {'n_estimators': 105, 'max_depth': 8, 'learning_rate': 0.1632209125771243, 'subsample': 0.8341041388961002, 'colsample_bytree': 0.9640236483587363, 'reg_alpha': 0.2650810420342792, 'reg_lambda': 0.16489151343235786}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:33:00,088] Trial 26 finished with value: 13.050599670410156 and parameters: {'n_estimators': 297, 'max_depth': 7, 'learning_rate': 0.07358399040039913, 'subsample': 0.6096290102887394, 'colsample_bytree': 0.8325041698463593, 'reg_alpha': 0.08682247469796056, 'reg_lambda': 0.3256657956592113}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:33:01,678] Trial 27 finished with value: 2.9212934017181396 and parameters: {'n_estimators': 215, 'max_depth': 10, 'learning_rate': 0.11856737341403221, 'subsample': 0.8722172640778296, 'colsample_bytree': 0.8865517396418541, 'reg_alpha': 0.4023572527880217, 'reg_lambda': 0.05619192364872157}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:33:02,240] Trial 28 finished with value: 1.8223794221878051 and parameters: {'n_estimators': 80, 'max_depth': 4, 'learning_rate': 0.17171668177959679, 'subsample': 0.7674657795860412, 'colsample_bytree': 0.9266715170325389, 'reg_alpha': 0.281014695697215, 'reg_lambda': 0.7994949142971836}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:33:03,952] Trial 29 finished with value: 2.1285018920898438 and parameters: {'n_estimators': 274, 'max_depth': 9, 'learning_rate': 0.09915756149322943, 'subsample': 0.8083955485662169, 'colsample_bytree': 0.8799491896698346, 'reg_alpha': 0.4589887349618313, 'reg_lambda': 0.4151628896921212}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:33:04,717] Trial 30 finished with value: 272.8226257324219 and parameters: {'n_estimators': 54, 'max_depth': 6, 'learning_rate': 0.011723183223308509, 'subsample': 0.6691836196705564, 'colsample_bytree': 0.9702959029438012, 'reg_alpha': 0.6043049453151685, 'reg_lambda': 0.29847665710428795}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:33:05,621] Trial 31 finished with value: 1.9347021579742432 and parameters: {'n_estimators': 93, 'max_depth': 8, 'learning_rate': 0.16649692349147366, 'subsample': 0.89619150514462, 'colsample_bytree': 0.9718704879908334, 'reg_alpha': 0.25616854414311335, 'reg_lambda': 0.1648746184400852}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:33:07,266] Trial 32 finished with value: 2.8782303810119627 and parameters: {'n_estimators': 158, 'max_depth': 8, 'learning_rate': 0.13142247138120064, 'subsample': 0.8206396736524797, 'colsample_bytree': 0.9124960434663223, 'reg_alpha': 0.3517856509779884, 'reg_lambda': 0.07947960559672973}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:33:08,476] Trial 33 finished with value: 1.6141446590423585 and parameters: {'n_estimators': 108, 'max_depth': 9, 'learning_rate': 0.17551792844481848, 'subsample': 0.7780720900100552, 'colsample_bytree': 0.9458961058349362, 'reg_alpha': 0.0755917513404877, 'reg_lambda': 0.18823544760457417}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:33:09,352] Trial 34 finished with value: 2.012847590446472 and parameters: {'n_estimators': 149, 'max_depth': 9, 'learning_rate': 0.26515321410473125, 'subsample': 0.7876299921777382, 'colsample_bytree': 0.9453201428782013, 'reg_alpha': 0.05156588554215183, 'reg_lambda': 0.00415089524100162}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:33:10,372] Trial 35 finished with value: 43.04887771606445 and parameters: {'n_estimators': 192, 'max_depth': 9, 'learning_rate': 0.21443142482662952, 'subsample': 0.765374357574939, 'colsample_bytree': 0.8373531470612292, 'reg_alpha': 0.14179091304236843, 'reg_lambda': 0.0880260047986245}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:33:11,737] Trial 36 finished with value: 1.702557909488678 and parameters: {'n_estimators': 177, 'max_depth': 10, 'learning_rate': 0.17513076983854367, 'subsample': 0.718804732986579, 'colsample_bytree': 0.9100458258029354, 'reg_alpha': 0.0067560437161210685, 'reg_lambda': 0.5652766915191867}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:33:13,188] Trial 37 finished with value: 1.8916093349456786 and parameters: {'n_estimators': 179, 'max_depth': 10, 'learning_rate': 0.1790186300228942, 'subsample': 0.7062586587630835, 'colsample_bytree': 0.8790292661794332, 'reg_alpha': 0.008845263077802618, 'reg_lambda': 0.5689357281553331}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:33:14,376] Trial 38 finished with value: 1.9933720827102661 and parameters: {'n_estimators': 223, 'max_depth': 10, 'learning_rate': 0.2317083712770205, 'subsample': 0.7167530848666589, 'colsample_bytree': 0.9232820957542723, 'reg_alpha': 0.0667574813763086, 'reg_lambda': 0.8215120224826168}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:33:16,013] Trial 39 finished with value: 24.67994213104248 and parameters: {'n_estimators': 168, 'max_depth': 10, 'learning_rate': 0.20091857020099957, 'subsample': 0.6745294742916192, 'colsample_bytree': 0.7896641611581298, 'reg_alpha': 0.014724215280766943, 'reg_lambda': 0.7199492987567286}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:33:17,567] Trial 40 finished with value: 2.0560257911682127 and parameters: {'n_estimators': 267, 'max_depth': 5, 'learning_rate': 0.1395609257822414, 'subsample': 0.6289295086686799, 'colsample_bytree': 0.8571188277893673, 'reg_alpha': 0.216753833979035, 'reg_lambda': 0.5332158621150817}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:33:19,006] Trial 41 finished with value: 1.9720024585723877 and parameters: {'n_estimators': 141, 'max_depth': 9, 'learning_rate': 0.1985422713982838, 'subsample': 0.7261800412856758, 'colsample_bytree': 0.9778043102837686, 'reg_alpha': 0.0762059282402735, 'reg_lambda': 0.4551073737517403}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:33:20,096] Trial 42 finished with value: 2.799455761909485 and parameters: {'n_estimators': 99, 'max_depth': 9, 'learning_rate': 0.10271715514637017, 'subsample': 0.7726260870948956, 'colsample_bytree': 0.8999629271186284, 'reg_alpha': 0.14994937901139282, 'reg_lambda': 0.37598257140392866}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:33:22,380] Trial 43 finished with value: 1.7597082614898683 and parameters: {'n_estimators': 184, 'max_depth': 7, 'learning_rate': 0.03536171735070018, 'subsample': 0.7603157939470566, 'colsample_bytree': 0.9443529316230437, 'reg_alpha': 0.3221105935013634, 'reg_lambda': 0.18811403878067162}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:33:23,860] Trial 44 finished with value: 1.6523368597030639 and parameters: {'n_estimators': 237, 'max_depth': 7, 'learning_rate': 0.17809693935167192, 'subsample': 0.8045989738660706, 'colsample_bytree': 0.936886676352078, 'reg_alpha': 0.32591248726705807, 'reg_lambda': 0.2010477609180061}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:33:25,622] Trial 45 finished with value: 2.0035305261611938 and parameters: {'n_estimators': 290, 'max_depth': 6, 'learning_rate': 0.1789189799173008, 'subsample': 0.7964791697878109, 'colsample_bytree': 0.9888387873845912, 'reg_alpha': 0.3655478373045093, 'reg_lambda': 0.4962444337355111}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:33:26,645] Trial 46 finished with value: 53.09797706604004 and parameters: {'n_estimators': 249, 'max_depth': 5, 'learning_rate': 0.15143462151482884, 'subsample': 0.855202848520044, 'colsample_bytree': 0.694801020497922, 'reg_alpha': 0.48868630138349667, 'reg_lambda': 0.050713525990869396}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:33:28,230] Trial 47 finished with value: 1.866341757774353 and parameters: {'n_estimators': 329, 'max_depth': 6, 'learning_rate': 0.1863510605797211, 'subsample': 0.684183421625764, 'colsample_bytree': 0.9162039677931416, 'reg_alpha': 0.5630219174153064, 'reg_lambda': 0.21939413246332767}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:33:29,218] Trial 48 finished with value: 2.22106990814209 and parameters: {'n_estimators': 368, 'max_depth': 4, 'learning_rate': 0.23871299330887646, 'subsample': 0.7830290761130165, 'colsample_bytree': 0.9414329888871209, 'reg_alpha': 0.2166106136053136, 'reg_lambda': 0.26681852951021123}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:33:30,272] Trial 49 finished with value: 1.6361555337905884 and parameters: {'n_estimators': 237, 'max_depth': 7, 'learning_rate': 0.2114350489098727, 'subsample': 0.8112904334507252, 'colsample_bytree': 0.9357282335872902, 'reg_alpha': 0.29414028099469414, 'reg_lambda': 0.3987587149959101}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:33:31,623] Trial 50 finished with value: 1.683656358718872 and parameters: {'n_estimators': 227, 'max_depth': 7, 'learning_rate': 0.21682620716204204, 'subsample': 0.8085786040131767, 'colsample_bytree': 0.9825515324142281, 'reg_alpha': 0.30220167952328153, 'reg_lambda': 0.2639664608546935}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:33:32,728] Trial 51 finished with value: 1.622816300392151 and parameters: {'n_estimators': 244, 'max_depth': 7, 'learning_rate': 0.21661809884005112, 'subsample': 0.8106474811594098, 'colsample_bytree': 0.9856442138682986, 'reg_alpha': 0.2985391233627298, 'reg_lambda': 0.2760038890541248}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:33:34,123] Trial 52 finished with value: 1.893215250968933 and parameters: {'n_estimators': 480, 'max_depth': 7, 'learning_rate': 0.2532806281218847, 'subsample': 0.8378382403308398, 'colsample_bytree': 0.9337789466060865, 'reg_alpha': 0.3614697931329445, 'reg_lambda': 0.39779180940567904}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:33:35,335] Trial 53 finished with value: 1.8436392784118651 and parameters: {'n_estimators': 238, 'max_depth': 6, 'learning_rate': 0.20188115294856274, 'subsample': 0.8795812435243705, 'colsample_bytree': 0.9998046942450549, 'reg_alpha': 0.3939039794259949, 'reg_lambda': 0.3298739124976809}. Best is trial 6 with value: 1.5817189693450928.
[I 2025-08-19 19:33:36,736] Trial 54 finished with value: 1.732063102722168 and parameters: {'n_estimators': 266, 'max_depth': 7, 'learning_rate': 0.19149094423000132, 'subsample': 0.8127340443066777, 'colsample_bytree': 0.9545048770146668, 'reg_alpha': 0.3167655147117781, 'reg_lambda': 0.21721756582470517}. Best is trial 6 with value: 1.5817189693450928.

[I 2025-08-19 19:34:35,865] A new study created in memory with name: no-name-2cbf9d47-5cf8-47bb-908c-89304613c4de

[I 2025-08-19 19:34:35,858] Trial 99 finished with value: 1.9454102516174316 and parameters: {'n_estimators': 414, 'max_depth': 9, 'learning_rate': 0.182165842133311, 'subsample': 0.7883805141447673, 'colsample_bytree': 0.8595317321972867, 'reg_alpha': 0.671209827933654, 'reg_lambda': 0.04741157488800425}. Best is trial 97 with value: 1.4579979658126831.
    Best XGBoost MSE: 1.457998

Optimizing for dataset: Ti_TE
  Optimizing SVR...

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2025-08-19 19:34:35,911] Trial 0 finished with value: 911.8286913097063 and parameters: {'C': 0.7080166777372641, 'gamma': 0.03664288488964582, 'epsilon': 0.7303805334596838}. Best is trial 0 with value: 911.8286913097063.
[I 2025-08-19 19:34:35,934] Trial 1 finished with value: 904.2574600524728 and parameters: {'C': 0.716739811622706, 'gamma': 0.026605024569958235, 'epsilon': 0.009909020096150061}. Best is trial 1 with value: 904.2574600524728.
[I 2025-08-19 19:34:36,005] Trial 2 finished with value: 147.18118115616082 and parameters: {'C': 1.1072914768800126, 'gamma': 5.503780404533425e-05, 'epsilon': 0.3479369431596531}. Best is trial 2 with value: 147.18118115616082.
[I 2025-08-19 19:34:36,079] Trial 3 finished with value: 1.114461134045072 and parameters: {'C': 52.38270938257665, 'gamma': 0.0007953407290028804, 'epsilon': 0.0041235565070253995}. Best is trial 3 with value: 1.114461134045072.
[I 2025-08-19 19:34:36,106] Trial 4 finished with value: 922.7552502418617 and parameters: {'C': 0.011484946565558417, 'gamma': 3.3521156622013896e-06, 'epsilon': 0.005522897166504355}. Best is trial 3 with value: 1.114461134045072.
[I 2025-08-19 19:34:36,139] Trial 5 finished with value: 801.5721040236309 and parameters: {'C': 0.8238571129572483, 'gamma': 0.004792844142778419, 'epsilon': 0.15372812711578807}. Best is trial 3 with value: 1.114461134045072.
[I 2025-08-19 19:34:36,171] Trial 6 finished with value: 556.4832147809614 and parameters: {'C': 1.3286000153927777, 'gamma': 0.0016107068546676673, 'epsilon': 0.10201317075512983}. Best is trial 3 with value: 1.114461134045072.
[I 2025-08-19 19:34:36,204] Trial 7 finished with value: 0.6226713338548108 and parameters: {'C': 16.855013503209154, 'gamma': 8.28218838461416e-05, 'epsilon': 0.0013728944900654164}. Best is trial 7 with value: 0.6226713338548108.
[I 2025-08-19 19:34:36,226] Trial 8 finished with value: 896.6217259511219 and parameters: {'C': 0.024028914251212098, 'gamma': 4.2359234267462355e-05, 'epsilon': 0.12665147101972324}. Best is trial 7 with value: 0.6226713338548108.
[I 2025-08-19 19:34:36,259] Trial 9 finished with value: 925.6320772954084 and parameters: {'C': 0.011027893465400396, 'gamma': 0.12079654162943208, 'epsilon': 0.019428094060121262}. Best is trial 7 with value: 0.6226713338548108.
[I 2025-08-19 19:34:36,322] Trial 10 finished with value: 0.033322036950756286 and parameters: {'C': 51.70222977150333, 'gamma': 3.3292485699658947e-06, 'epsilon': 0.0010253718120924727}. Best is trial 10 with value: 0.033322036950756286.
[I 2025-08-19 19:34:36,386] Trial 11 finished with value: 0.017177124900835266 and parameters: {'C': 85.42348757968868, 'gamma': 1.1154406725445421e-06, 'epsilon': 0.0012795966681601113}. Best is trial 11 with value: 0.017177124900835266.
[I 2025-08-19 19:34:36,439] Trial 12 finished with value: 0.05847538039908664 and parameters: {'C': 48.46159798985091, 'gamma': 1.7476210261657477e-06, 'epsilon': 0.0012143194777005564}. Best is trial 11 with value: 0.017177124900835266.
[I 2025-08-19 19:34:36,488] Trial 13 finished with value: 3.323383680252223 and parameters: {'C': 8.372649683289024, 'gamma': 8.770101098559268e-06, 'epsilon': 0.0026978741259317237}. Best is trial 11 with value: 0.017177124900835266.
[I 2025-08-19 19:34:36,522] Trial 14 finished with value: 0.017946555985827332 and parameters: {'C': 94.51679095184821, 'gamma': 1.0011144508177092e-06, 'epsilon': 0.03077770181525936}. Best is trial 11 with value: 0.017177124900835266.
[I 2025-08-19 19:34:36,574] Trial 15 finished with value: 919.7387152850966 and parameters: {'C': 5.447806224186973, 'gamma': 0.8460123301163074, 'epsilon': 0.038393756884340734}. Best is trial 11 with value: 0.017177124900835266.
[I 2025-08-19 19:34:36,620] Trial 16 finished with value: 0.01603530137416877 and parameters: {'C': 90.1489814436034, 'gamma': 1.1579936548340816e-06, 'epsilon': 0.0356921623259633}. Best is trial 16 with value: 0.01603530137416877.
[I 2025-08-19 19:34:36,666] Trial 17 finished with value: 837.6431665556005 and parameters: {'C': 0.13401569015354817, 'gamma': 1.1384618077482095e-05, 'epsilon': 0.01338826122032564}. Best is trial 16 with value: 0.01603530137416877.
[I 2025-08-19 19:34:36,716] Trial 18 finished with value: 2.203962408304009 and parameters: {'C': 14.205403683368278, 'gamma': 0.000316014213069673, 'epsilon': 0.05815570949375549}. Best is trial 16 with value: 0.01603530137416877.
[I 2025-08-19 19:34:36,768] Trial 19 finished with value: 15.110148320737483 and parameters: {'C': 4.00923205241002, 'gamma': 1.5899121020453432e-05, 'epsilon': 0.006672772577687329}. Best is trial 16 with value: 0.01603530137416877.
[I 2025-08-19 19:34:36,824] Trial 20 finished with value: 0.6989294696750098 and parameters: {'C': 24.293713547276674, 'gamma': 0.0002361217170389266, 'epsilon': 0.002669440617000856}. Best is trial 16 with value: 0.01603530137416877.
[I 2025-08-19 19:34:36,855] Trial 21 finished with value: 0.049049222856488 and parameters: {'C': 61.12804319076856, 'gamma': 1.249220020974622e-06, 'epsilon': 0.029559862026038705}. Best is trial 16 with value: 0.01603530137416877.
[I 2025-08-19 19:34:36,894] Trial 22 finished with value: 0.018714367123113758 and parameters: {'C': 98.81178401185669, 'gamma': 1.0378766770201175e-06, 'epsilon': 0.06586901383694259}. Best is trial 16 with value: 0.01603530137416877.
[I 2025-08-19 19:34:36,924] Trial 23 finished with value: 0.4129040037226021 and parameters: {'C': 25.097987020278982, 'gamma': 5.523053025049896e-06, 'epsilon': 0.28134607890219415}. Best is trial 16 with value: 0.01603530137416877.
[I 2025-08-19 19:34:36,958] Trial 24 finished with value: 0.02016703417535618 and parameters: {'C': 95.83739498712931, 'gamma': 2.1622621550185083e-05, 'epsilon': 0.022833153232196753}. Best is trial 16 with value: 0.01603530137416877.
[I 2025-08-19 19:34:37,000] Trial 25 finished with value: 406.86007762934935 and parameters: {'C': 2.412765335551275, 'gamma': 3.4623985950326406e-06, 'epsilon': 0.012910065834370587}. Best is trial 16 with value: 0.01603530137416877.
[I 2025-08-19 19:34:37,030] Trial 26 finished with value: 914.1153648555113 and parameters: {'C': 0.14170910236355977, 'gamma': 1.010215423765902e-06, 'epsilon': 0.040645331458983844}. Best is trial 16 with value: 0.01603530137416877.
[I 2025-08-19 19:34:37,061] Trial 27 finished with value: 0.6585652812029266 and parameters: {'C': 33.33626523610092, 'gamma': 2.0759354249209443e-05, 'epsilon': 0.9029951252717084}. Best is trial 16 with value: 0.01603530137416877.
[I 2025-08-19 19:34:37,092] Trial 28 finished with value: 1.680308356055346 and parameters: {'C': 11.553295583092657, 'gamma': 3.89980799729244e-06, 'epsilon': 0.002298287218415806}. Best is trial 16 with value: 0.01603530137416877.
[I 2025-08-19 19:34:37,120] Trial 29 finished with value: 903.7164505779962 and parameters: {'C': 0.2667448396950702, 'gamma': 0.010487863297349041, 'epsilon': 0.3214765276813141}. Best is trial 16 with value: 0.01603530137416877.
[I 2025-08-19 19:34:37,158] Trial 30 finished with value: 0.1577169835323095 and parameters: {'C': 98.18712761819653, 'gamma': 0.0002321864362104762, 'epsilon': 0.07596131200467136}. Best is trial 16 with value: 0.01603530137416877.
[I 2025-08-19 19:34:37,190] Trial 31 finished with value: 0.043366132599288086 and parameters: {'C': 96.10619211411044, 'gamma': 1.1070849824004803e-06, 'epsilon': 0.19229662446702128}. Best is trial 16 with value: 0.01603530137416877.
[I 2025-08-19 19:34:37,228] Trial 32 finished with value: 0.5845086165118957 and parameters: {'C': 29.26070946529964, 'gamma': 2.264176021813278e-06, 'epsilon': 0.5170063597050738}. Best is trial 16 with value: 0.01603530137416877.
[I 2025-08-19 19:34:37,257] Trial 33 finished with value: 0.06869161524496949 and parameters: {'C': 42.356946895688885, 'gamma': 7.45332398608993e-06, 'epsilon': 0.05871287929804117}. Best is trial 16 with value: 0.01603530137416877.
[I 2025-08-19 19:34:37,304] Trial 34 finished with value: 0.04339837787180229 and parameters: {'C': 67.9352684940552, 'gamma': 4.2959273427896366e-05, 'epsilon': 0.009724656498875219}. Best is trial 16 with value: 0.01603530137416877.
[I 2025-08-19 19:34:37,354] Trial 35 finished with value: 0.41781456063329114 and parameters: {'C': 23.39521638435582, 'gamma': 2.085867330982561e-06, 'epsilon': 0.019863125837543776}. Best is trial 16 with value: 0.01603530137416877.
[I 2025-08-19 19:34:37,395] Trial 36 finished with value: 4.006396804095703 and parameters: {'C': 7.5228744651592985, 'gamma': 6.364737327797627e-06, 'epsilon': 0.06005760442530769}. Best is trial 16 with value: 0.01603530137416877.
[I 2025-08-19 19:34:37,443] Trial 37 finished with value: 0.12111227807058748 and parameters: {'C': 62.7733420577349, 'gamma': 1.067579815878884e-06, 'epsilon': 0.19239036022242959}. Best is trial 16 with value: 0.01603530137416877.
[I 2025-08-19 19:34:37,504] Trial 38 finished with value: 0.6797921002919161 and parameters: {'C': 16.084664094920072, 'gamma': 7.691892975972941e-05, 'epsilon': 0.004976753457631503}. Best is trial 16 with value: 0.01603530137416877.
[I 2025-08-19 19:34:37,555] Trial 39 finished with value: 0.17476057999535238 and parameters: {'C': 33.38806642789753, 'gamma': 2.543999509999001e-06, 'epsilon': 0.10476928959491592}. Best is trial 16 with value: 0.01603530137416877.
[I 2025-08-19 19:34:37,602] Trial 40 finished with value: 440.0196085996581 and parameters: {'C': 2.1267058090215603, 'gamma': 0.0018845154051968889, 'epsilon': 0.007860586853542842}. Best is trial 16 with value: 0.01603530137416877.
[I 2025-08-19 19:34:37,643] Trial 41 finished with value: 0.026819953467679312 and parameters: {'C': 77.22004630265945, 'gamma': 2.3541989598960642e-05, 'epsilon': 0.02261951439896177}. Best is trial 16 with value: 0.01603530137416877.
[I 2025-08-19 19:34:37,671] Trial 42 finished with value: 0.011277055360264599 and parameters: {'C': 90.94276907073511, 'gamma': 4.999552076938166e-06, 'epsilon': 0.02862357247481895}. Best is trial 42 with value: 0.011277055360264599.
[I 2025-08-19 19:34:37,697] Trial 43 finished with value: 0.06004585668697042 and parameters: {'C': 47.81556976390967, 'gamma': 2.1300173519554547e-06, 'epsilon': 0.035493121800397036}. Best is trial 42 with value: 0.011277055360264599.
[I 2025-08-19 19:34:37,726] Trial 44 finished with value: 0.07594687217550783 and parameters: {'C': 41.077765378374266, 'gamma': 5.1008265518875e-06, 'epsilon': 0.08397139211289947}. Best is trial 42 with value: 0.011277055360264599.
[I 2025-08-19 19:34:37,773] Trial 45 finished with value: 0.4229168926559497 and parameters: {'C': 20.742443510861385, 'gamma': 1.0304724358511207e-05, 'epsilon': 0.014583407191580494}. Best is trial 42 with value: 0.011277055360264599.
[I 2025-08-19 19:34:37,820] Trial 46 finished with value: 0.00783608457052649 and parameters: {'C': 98.51501748123245, 'gamma': 1.8181924063449967e-06, 'epsilon': 0.0275818925034608}. Best is trial 46 with value: 0.00783608457052649.
[I 2025-08-19 19:34:37,863] Trial 47 finished with value: 794.3036359036315 and parameters: {'C': 0.5214488781500273, 'gamma': 3.5045694677092564e-06, 'epsilon': 0.028163953594509034}. Best is trial 46 with value: 0.00783608457052649.
[I 2025-08-19 19:34:37,897] Trial 48 finished with value: 0.02474001877948994 and parameters: {'C': 61.30400617853694, 'gamma': 2.405171130173897e-06, 'epsilon': 0.047007107361669936}. Best is trial 46 with value: 0.00783608457052649.
[I 2025-08-19 19:34:37,928] Trial 49 finished with value: 924.9516281445049 and parameters: {'C': 0.03328924531018883, 'gamma': 0.03447171108188919, 'epsilon': 0.0015925011609805573}. Best is trial 46 with value: 0.00783608457052649.
[I 2025-08-19 19:34:37,959] Trial 50 finished with value: 757.2830079553751 and parameters: {'C': 43.761598499271265, 'gamma': 0.06821762062831291, 'epsilon': 0.004163491270388736}. Best is trial 46 with value: 0.00783608457052649.
[I 2025-08-19 19:34:38,000] Trial 51 finished with value: 0.018942481677389274 and parameters: {'C': 77.64919577710828, 'gamma': 1.5517058274799377e-06, 'epsilon': 0.04782664919308806}. Best is trial 46 with value: 0.00783608457052649.
[I 2025-08-19 19:34:38,075] Trial 52 finished with value: 0.007182469205518011 and parameters: {'C': 99.31927645418497, 'gamma': 1.6130696521046082e-06, 'epsilon': 0.015822532271820122}. Best is trial 52 with value: 0.007182469205518011.
[I 2025-08-19 19:34:38,126] Trial 53 finished with value: 0.035754972448932706 and parameters: {'C': 58.71874972312744, 'gamma': 1.3330095410100564e-05, 'epsilon': 0.02576624696220757}. Best is trial 52 with value: 0.007182469205518011.
[I 2025-08-19 19:34:38,167] Trial 54 finished with value: 2.055571528634787 and parameters: {'C': 10.345630632777572, 'gamma': 4.807746834556456e-06, 'epsilon': 0.012614225096315828}. Best is trial 52 with value: 0.007182469205518011.
[I 2025-08-19 19:34:38,208] Trial 55 finished with value: 0.16064028755980986 and parameters: {'C': 35.148245162923786, 'gamma': 1.7308815363994482e-06, 'epsilon': 0.01706128179297203}. Best is trial 52 with value: 0.007182469205518011.
[I 2025-08-19 19:34:38,252] Trial 56 finished with value: 0.018862841789810042 and parameters: {'C': 75.69156526501784, 'gamma': 8.393688360373294e-06, 'epsilon': 0.009462463324406745}. Best is trial 52 with value: 0.007182469205518011.
[I 2025-08-19 19:34:38,304] Trial 57 finished with value: 906.1830553840031 and parameters: {'C': 21.568194261455144, 'gamma': 0.667829761807425, 'epsilon': 0.03324074430973251}. Best is trial 52 with value: 0.007182469205518011.
[I 2025-08-19 19:34:38,351] Trial 58 finished with value: 0.037132425553392405 and parameters: {'C': 50.46136909680343, 'gamma': 3.5283779885540406e-06, 'epsilon': 0.016174994590622993}. Best is trial 52 with value: 0.007182469205518011.
[I 2025-08-19 19:34:38,392] Trial 59 finished with value: 0.02592316051533681 and parameters: {'C': 99.08550808009184, 'gamma': 3.0007612767707553e-05, 'epsilon': 0.04548879782527813}. Best is trial 52 with value: 0.007182469205518011.
[I 2025-08-19 19:34:38,434] Trial 60 finished with value: 1.9285866344451814 and parameters: {'C': 16.511530829050624, 'gamma': 1.5976947330767639e-06, 'epsilon': 0.0018873839127743755}. Best is trial 52 with value: 0.007182469205518011.
[I 2025-08-19 19:34:38,465] Trial 61 finished with value: 0.01420682219447364 and parameters: {'C': 98.83785633998602, 'gamma': 1.4229124253686413e-06, 'epsilon': 0.0742897939158075}. Best is trial 52 with value: 0.007182469205518011.
[I 2025-08-19 19:34:38,498] Trial 62 finished with value: 0.06749708126808954 and parameters: {'C': 73.03840796911568, 'gamma': 1.0022092135451245e-06, 'epsilon': 0.12070603271298401}. Best is trial 52 with value: 0.007182469205518011.
[I 2025-08-19 19:34:38,534] Trial 63 finished with value: 0.1517411971902561 and parameters: {'C': 31.686968177756576, 'gamma': 2.9616663028076856e-06, 'epsilon': 0.030391598323290393}. Best is trial 52 with value: 0.007182469205518011.
[I 2025-08-19 19:34:38,574] Trial 64 finished with value: 0.04424844845226535 and parameters: {'C': 51.9050502024309, 'gamma': 4.77064962513158e-06, 'epsilon': 0.08989189496470602}. Best is trial 52 with value: 0.007182469205518011.
[I 2025-08-19 19:34:38,604] Trial 65 finished with value: 0.018152068137699262 and parameters: {'C': 82.40642535384067, 'gamma': 1.5795971386090843e-06, 'epsilon': 0.07097754742006057}. Best is trial 52 with value: 0.007182469205518011.
[I 2025-08-19 19:34:38,642] Trial 66 finished with value: 0.015219919817404493 and parameters: {'C': 99.36859537063155, 'gamma': 1.3535721059096205e-05, 'epsilon': 0.020626194251669172}. Best is trial 52 with value: 0.007182469205518011.
[I 2025-08-19 19:34:38,694] Trial 67 finished with value: 0.06416519582355099 and parameters: {'C': 41.359909086240414, 'gamma': 1.3044083013722668e-05, 'epsilon': 0.003358676398298301}. Best is trial 52 with value: 0.007182469205518011.
[I 2025-08-19 19:34:38,734] Trial 68 finished with value: 0.11406108172592802 and parameters: {'C': 60.81025743957748, 'gamma': 0.00011311551805100707, 'epsilon': 0.020748654240317833}. Best is trial 52 with value: 0.007182469205518011.
[I 2025-08-19 19:34:38,789] Trial 69 finished with value: 0.19178546046426131 and parameters: {'C': 28.297470990465154, 'gamma': 5.882349006829326e-06, 'epsilon': 0.0010114421849947589}. Best is trial 52 with value: 0.007182469205518011.
[I 2025-08-19 19:34:38,832] Trial 70 finished with value: 0.5415673867176407 and parameters: {'C': 99.52306583319545, 'gamma': 0.0006435750148237092, 'epsilon': 0.006983197881817188}. Best is trial 52 with value: 0.007182469205518011.
[I 2025-08-19 19:34:38,855] Trial 71 finished with value: 0.015500116642449286 and parameters: {'C': 71.5589660177058, 'gamma': 2.613730086804515e-06, 'epsilon': 0.025297708954906895}. Best is trial 52 with value: 0.007182469205518011.
[I 2025-08-19 19:34:38,887] Trial 72 finished with value: 0.01612943811312182 and parameters: {'C': 68.46069545280304, 'gamma': 2.7622280684311078e-06, 'epsilon': 0.011508485800731437}. Best is trial 52 with value: 0.007182469205518011.
[I 2025-08-19 19:34:38,929] Trial 73 finished with value: 0.02434119214308447 and parameters: {'C': 66.68381620354398, 'gamma': 8.658945058323356e-06, 'epsilon': 0.01774874888048034}. Best is trial 52 with value: 0.007182469205518011.
[I 2025-08-19 19:34:38,984] Trial 74 finished with value: 0.09195768502667105 and parameters: {'C': 39.38328286640076, 'gamma': 2.7662932980275194e-06, 'epsilon': 0.024958216238931553}. Best is trial 52 with value: 0.007182469205518011.
[I 2025-08-19 19:34:39,014] Trial 75 finished with value: 0.05306298666892395 and parameters: {'C': 53.07264289734314, 'gamma': 1.5579910525349707e-06, 'epsilon': 0.011998387279371756}. Best is trial 52 with value: 0.007182469205518011.
[I 2025-08-19 19:34:39,053] Trial 76 finished with value: 0.015338453381816691 and parameters: {'C': 77.39730059264214, 'gamma': 3.7174573135752794e-06, 'epsilon': 0.038187680949518146}. Best is trial 52 with value: 0.007182469205518011.
[I 2025-08-19 19:34:39,088] Trial 77 finished with value: 0.02237350930260757 and parameters: {'C': 81.26764714734843, 'gamma': 1.6870662629819155e-05, 'epsilon': 0.0366475137887675}. Best is trial 52 with value: 0.007182469205518011.
[I 2025-08-19 19:34:39,122] Trial 78 finished with value: 911.6720902275968 and parameters: {'C': 0.030318404219413567, 'gamma': 6.864213695085055e-06, 'epsilon': 0.04866086079969087}. Best is trial 52 with value: 0.007182469205518011.
[I 2025-08-19 19:34:39,163] Trial 79 finished with value: 0.04214185463274048 and parameters: {'C': 49.7554715726939, 'gamma': 4.316605086610618e-06, 'epsilon': 0.04195445774553384}. Best is trial 52 with value: 0.007182469205518011.
[I 2025-08-19 19:34:39,211] Trial 80 finished with value: 15.022458237407609 and parameters: {'C': 99.570825006228, 'gamma': 0.0038738225927039344, 'epsilon': 0.05374873738697927}. Best is trial 52 with value: 0.007182469205518011.
[I 2025-08-19 19:34:39,244] Trial 81 finished with value: 0.01804249356585844 and parameters: {'C': 67.09643966355341, 'gamma': 2.2340957255328866e-06, 'epsilon': 0.021102230842727658}. Best is trial 52 with value: 0.007182469205518011.
[I 2025-08-19 19:34:39,283] Trial 82 finished with value: 0.012758458069415463 and parameters: {'C': 77.89015109097771, 'gamma': 2.983749159351855e-06, 'epsilon': 0.026329830895268948}. Best is trial 52 with value: 0.007182469205518011.
[I 2025-08-19 19:34:39,323] Trial 83 finished with value: 0.21237673972485202 and parameters: {'C': 33.76328596730052, 'gamma': 1.5374341446254157e-06, 'epsilon': 0.028398775224316584}. Best is trial 52 with value: 0.007182469205518011.
[I 2025-08-19 19:34:39,344] Trial 84 finished with value: 0.03510704332374992 and parameters: {'C': 52.60164577690747, 'gamma': 3.4921468644233303e-06, 'epsilon': 0.03615616070206292}. Best is trial 52 with value: 0.007182469205518011.

[I 2025-08-19 19:34:39,976] A new study created in memory with name: no-name-399aad74-df4a-4097-b78e-137ac7d0df6b

[I 2025-08-19 19:34:39,842] Trial 96 finished with value: 835.0360492550657 and parameters: {'C': 0.5959376166536612, 'gamma': 1.99291679033236e-06, 'epsilon': 0.057055202857510035}. Best is trial 52 with value: 0.007182469205518011.
[I 2025-08-19 19:34:39,879] Trial 97 finished with value: 0.1090600351558029 and parameters: {'C': 45.64150106504006, 'gamma': 1.2748247634050776e-06, 'epsilon': 0.027767539769192256}. Best is trial 52 with value: 0.007182469205518011.
[I 2025-08-19 19:34:39,928] Trial 98 finished with value: 89.9387548624045 and parameters: {'C': 5.104505968011669, 'gamma': 3.3339558725317438e-06, 'epsilon': 0.06671671778315579}. Best is trial 52 with value: 0.007182469205518011.
[I 2025-08-19 19:34:39,973] Trial 99 finished with value: 0.02484373316631999 and parameters: {'C': 59.975587076262855, 'gamma': 4.730456393822553e-06, 'epsilon': 0.019013511683233925}. Best is trial 52 with value: 0.007182469205518011.
    Best SVR MSE: 0.007182
  Optimizing Neural Network...

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2025-08-19 19:34:41,737] Trial 0 finished with value: 0.3273564371962968 and parameters: {'n_layers': 2, 'hidden_size_0': 155, 'hidden_size_1': 192, 'alpha': 7.167398116227066e-05, 'learning_rate_init': 0.016311046738317646}. Best is trial 0 with value: 0.3273564371962968.
[I 2025-08-19 19:34:42,054] Trial 1 finished with value: 6.61398955963647 and parameters: {'n_layers': 1, 'hidden_size_0': 107, 'alpha': 1.4469073799463473e-05, 'learning_rate_init': 0.03479369431596534}. Best is trial 0 with value: 0.3273564371962968.
[I 2025-08-19 19:34:43,824] Trial 2 finished with value: 0.29140792541220184 and parameters: {'n_layers': 3, 'hidden_size_0': 102, 'hidden_size_1': 49, 'hidden_size_2': 12, 'alpha': 2.239817654479077e-06, 'learning_rate_init': 0.0005522897166504359}. Best is trial 2 with value: 0.29140792541220184.
[I 2025-08-19 19:34:45,310] Trial 3 finished with value: 0.23850181160295642 and parameters: {'n_layers': 2, 'hidden_size_0': 127, 'hidden_size_1': 149, 'alpha': 0.00013286000153927766, 'learning_rate_init': 0.004013361252949541}. Best is trial 3 with value: 0.23850181160295642.
[I 2025-08-19 19:34:47,746] Trial 4 finished with value: 0.18022215864104346 and parameters: {'n_layers': 3, 'hidden_size_0': 164, 'hidden_size_1': 71, 'hidden_size_2': 18, 'alpha': 2.4028914251212117e-06, 'learning_rate_init': 0.0006508397211868865}. Best is trial 4 with value: 0.18022215864104346.
[I 2025-08-19 19:34:48,858] Trial 5 finished with value: 5.323440301975498 and parameters: {'n_layers': 3, 'hidden_size_0': 12, 'hidden_size_1': 171, 'hidden_size_2': 92, 'alpha': 3.31245933388589e-05, 'learning_rate_init': 0.0475469046012784}. Best is trial 4 with value: 0.18022215864104346.
[I 2025-08-19 19:34:50,895] Trial 6 finished with value: 0.8454013180988744 and parameters: {'n_layers': 3, 'hidden_size_0': 149, 'hidden_size_1': 93, 'hidden_size_2': 62, 'alpha': 0.0008307038575919792, 'learning_rate_init': 0.0006247417454051523}. Best is trial 4 with value: 0.18022215864104346.
[I 2025-08-19 19:34:52,700] Trial 7 finished with value: 195.79929425285235 and parameters: {'n_layers': 1, 'hidden_size_0': 42, 'alpha': 2.003017770189989e-05, 'learning_rate_init': 0.00010288226798899776}. Best is trial 4 with value: 0.18022215864104346.
[I 2025-08-19 19:34:53,070] Trial 8 finished with value: 1.2493287095720276 and parameters: {'n_layers': 2, 'hidden_size_0': 47, 'hidden_size_1': 133, 'alpha': 5.0121585016886075e-06, 'learning_rate_init': 0.029839538215823313}. Best is trial 4 with value: 0.18022215864104346.
[I 2025-08-19 19:34:53,284] Trial 9 finished with value: 21.972056452306354 and parameters: {'n_layers': 2, 'hidden_size_0': 14, 'hidden_size_1': 133, 'alpha': 1.82655565832615e-06, 'learning_rate_init': 0.024608957414494176}. Best is trial 4 with value: 0.18022215864104346.
[I 2025-08-19 19:34:54,409] Trial 10 finished with value: 0.9744320743172935 and parameters: {'n_layers': 3, 'hidden_size_0': 195, 'hidden_size_1': 11, 'hidden_size_2': 192, 'alpha': 0.009579480611214039, 'learning_rate_init': 0.001629725211129312}. Best is trial 4 with value: 0.18022215864104346.
[I 2025-08-19 19:34:55,259] Trial 11 finished with value: 1.332661867650833 and parameters: {'n_layers': 2, 'hidden_size_0': 141, 'hidden_size_1': 89, 'alpha': 0.0005021563471774668, 'learning_rate_init': 0.0047290018676499086}. Best is trial 4 with value: 0.18022215864104346.
[I 2025-08-19 19:34:55,539] Trial 12 finished with value: 23.83591063747803 and parameters: {'n_layers': 1, 'hidden_size_0': 199, 'alpha': 0.00030700764204304415, 'learning_rate_init': 0.0043436727685164465}. Best is trial 4 with value: 0.18022215864104346.
[I 2025-08-19 19:34:56,316] Trial 13 finished with value: 0.3010480267246606 and parameters: {'n_layers': 2, 'hidden_size_0': 113, 'hidden_size_1': 58, 'alpha': 0.00016496491964448738, 'learning_rate_init': 0.0012426354307450943}. Best is trial 4 with value: 0.18022215864104346.
[I 2025-08-19 19:35:04,170] Trial 14 finished with value: 0.24868071003175954 and parameters: {'n_layers': 3, 'hidden_size_0': 160, 'hidden_size_1': 142, 'hidden_size_2': 11, 'alpha': 0.0019132030194288657, 'learning_rate_init': 0.00017838383323786635}. Best is trial 4 with value: 0.18022215864104346.
[I 2025-08-19 19:35:04,335] Trial 15 finished with value: 26.07579164153313 and parameters: {'n_layers': 2, 'hidden_size_0': 80, 'hidden_size_1': 62, 'alpha': 8.359550890614878e-06, 'learning_rate_init': 0.00810703879249531}. Best is trial 4 with value: 0.18022215864104346.
[I 2025-08-19 19:35:05,577] Trial 16 finished with value: 1.246429242709952 and parameters: {'n_layers': 2, 'hidden_size_0': 174, 'hidden_size_1': 113, 'alpha': 4.598334297723421e-05, 'learning_rate_init': 0.0015115236979788306}. Best is trial 4 with value: 0.18022215864104346.
[I 2025-08-19 19:35:08,555] Trial 17 finished with value: 0.258552517390862 and parameters: {'n_layers': 3, 'hidden_size_0': 129, 'hidden_size_1': 16, 'hidden_size_2': 155, 'alpha': 0.002268432737646649, 'learning_rate_init': 0.00026962814416399726}. Best is trial 4 with value: 0.18022215864104346.
[I 2025-08-19 19:35:08,776] Trial 18 finished with value: 18.175957510775426 and parameters: {'n_layers': 1, 'hidden_size_0': 177, 'alpha': 0.0001498219403457522, 'learning_rate_init': 0.009134800103402804}. Best is trial 4 with value: 0.18022215864104346.
[I 2025-08-19 19:35:10,758] Trial 19 finished with value: 0.1869865881612775 and parameters: {'n_layers': 2, 'hidden_size_0': 80, 'hidden_size_1': 174, 'alpha': 1.0164823734436477e-06, 'learning_rate_init': 0.0006796676578994936}. Best is trial 4 with value: 0.18022215864104346.
[I 2025-08-19 19:35:12,847] Trial 20 finished with value: 0.20820808608096403 and parameters: {'n_layers': 3, 'hidden_size_0': 80, 'hidden_size_1': 199, 'hidden_size_2': 63, 'alpha': 1.4485630680206427e-06, 'learning_rate_init': 0.000445446698187223}. Best is trial 4 with value: 0.18022215864104346.
[I 2025-08-19 19:35:14,972] Trial 21 finished with value: 0.3196528009992871 and parameters: {'n_layers': 3, 'hidden_size_0': 78, 'hidden_size_1': 197, 'hidden_size_2': 62, 'alpha': 1.0168252277179458e-06, 'learning_rate_init': 0.0005152931699774145}. Best is trial 4 with value: 0.18022215864104346.
[I 2025-08-19 19:35:18,392] Trial 22 finished with value: 0.28265781937665163 and parameters: {'n_layers': 3, 'hidden_size_0': 82, 'hidden_size_1': 170, 'hidden_size_2': 52, 'alpha': 3.846928146107184e-06, 'learning_rate_init': 0.0002736372663297118}. Best is trial 4 with value: 0.18022215864104346.
[I 2025-08-19 19:35:19,780] Trial 23 finished with value: 3.5534384873746516 and parameters: {'n_layers': 3, 'hidden_size_0': 60, 'hidden_size_1': 172, 'hidden_size_2': 108, 'alpha': 1.6695392719385313e-06, 'learning_rate_init': 0.0009576786392186535}. Best is trial 4 with value: 0.18022215864104346.
[I 2025-08-19 19:35:20,796] Trial 24 finished with value: 3.1043219433290394 and parameters: {'n_layers': 3, 'hidden_size_0': 96, 'hidden_size_1': 197, 'hidden_size_2': 34, 'alpha': 4.825008158563805e-06, 'learning_rate_init': 0.00251006333256785}. Best is trial 4 with value: 0.18022215864104346.
[I 2025-08-19 19:35:21,790] Trial 25 finished with value: 38.10546666731089 and parameters: {'n_layers': 2, 'hidden_size_0': 59, 'hidden_size_1': 74, 'alpha': 1.033942746392717e-06, 'learning_rate_init': 0.09994017866681287}. Best is trial 4 with value: 0.18022215864104346.
[I 2025-08-19 19:35:23,907] Trial 26 finished with value: 0.46743875323703055 and parameters: {'n_layers': 3, 'hidden_size_0': 34, 'hidden_size_1': 36, 'hidden_size_2': 96, 'alpha': 3.424797199769857e-06, 'learning_rate_init': 0.0003074913643216911}. Best is trial 4 with value: 0.18022215864104346.
[I 2025-08-19 19:35:25,056] Trial 27 finished with value: 0.30251627181983115 and parameters: {'n_layers': 2, 'hidden_size_0': 64, 'hidden_size_1': 114, 'alpha': 1.0045954706727361e-05, 'learning_rate_init': 0.0007787228509470787}. Best is trial 4 with value: 0.18022215864104346.
[I 2025-08-19 19:35:31,400] Trial 28 finished with value: 0.2686872315381179 and parameters: {'n_layers': 3, 'hidden_size_0': 92, 'hidden_size_1': 159, 'hidden_size_2': 37, 'alpha': 7.353426889148068e-06, 'learning_rate_init': 0.00013638178966729966}. Best is trial 4 with value: 0.18022215864104346.
[I 2025-08-19 19:35:31,928] Trial 29 finished with value: 18.46044408307402 and parameters: {'n_layers': 2, 'hidden_size_0': 121, 'hidden_size_1': 184, 'alpha': 2.443869289720194e-06, 'learning_rate_init': 0.0023300833936246}. Best is trial 4 with value: 0.18022215864104346.
[I 2025-08-19 19:35:34,610] Trial 30 finished with value: 0.3448823214966483 and parameters: {'n_layers': 3, 'hidden_size_0': 75, 'hidden_size_1': 99, 'hidden_size_2': 124, 'alpha': 1.0307270203416091e-06, 'learning_rate_init': 0.0004136102034293571}. Best is trial 4 with value: 0.18022215864104346.
[I 2025-08-19 19:35:35,226] Trial 31 finished with value: 9.623632819571702 and parameters: {'n_layers': 2, 'hidden_size_0': 137, 'hidden_size_1': 153, 'alpha': 9.860512623624776e-05, 'learning_rate_init': 0.007942812607414418}. Best is trial 4 with value: 0.18022215864104346.
[I 2025-08-19 19:35:36,311] Trial 32 finished with value: 12.424308675573794 and parameters: {'n_layers': 2, 'hidden_size_0': 165, 'hidden_size_1': 183, 'alpha': 2.2766919701581018e-05, 'learning_rate_init': 0.003790071389232329}. Best is trial 4 with value: 0.18022215864104346.
[I 2025-08-19 19:35:37,622] Trial 33 finished with value: 0.22684370849578067 and parameters: {'n_layers': 2, 'hidden_size_0': 111, 'hidden_size_1': 146, 'alpha': 1.354146096273525e-05, 'learning_rate_init': 0.0009587006840327029}. Best is trial 4 with value: 0.18022215864104346.
[I 2025-08-19 19:35:38,515] Trial 34 finished with value: 0.3204119853796252 and parameters: {'n_layers': 1, 'hidden_size_0': 114, 'alpha': 1.3755187100858545e-05, 'learning_rate_init': 0.0009254553275138481}. Best is trial 4 with value: 0.18022215864104346.
[I 2025-08-19 19:35:40,922] Trial 35 finished with value: 0.16932598484154288 and parameters: {'n_layers': 2, 'hidden_size_0': 99, 'hidden_size_1': 181, 'alpha': 2.595002625070385e-06, 'learning_rate_init': 0.00040036813132387475}. Best is trial 35 with value: 0.16932598484154288.
[I 2025-08-19 19:35:43,834] Trial 36 finished with value: 0.17837126392496697 and parameters: {'n_layers': 2, 'hidden_size_0': 101, 'hidden_size_1': 185, 'alpha': 2.3350156910449545e-06, 'learning_rate_init': 0.0004279581743289012}. Best is trial 35 with value: 0.16932598484154288.
[I 2025-08-19 19:35:48,971] Trial 37 finished with value: 0.23854945493109875 and parameters: {'n_layers': 2, 'hidden_size_0': 98, 'hidden_size_1': 185, 'alpha': 2.2664952986336953e-06, 'learning_rate_init': 0.00019568351022749108}. Best is trial 35 with value: 0.16932598484154288.
[I 2025-08-19 19:35:51,146] Trial 38 finished with value: 0.1685101776418778 and parameters: {'n_layers': 1, 'hidden_size_0': 89, 'alpha': 2.9695167729448614e-06, 'learning_rate_init': 0.00036304647639621496}. Best is trial 38 with value: 0.1685101776418778.
[I 2025-08-19 19:35:53,524] Trial 39 finished with value: 37.737959264803784 and parameters: {'n_layers': 1, 'hidden_size_0': 103, 'alpha': 6.6084163415866965e-06, 'learning_rate_init': 0.00010549669936358791}. Best is trial 38 with value: 0.1685101776418778.
[I 2025-08-19 19:35:54,982] Trial 40 finished with value: 0.2455893463942478 and parameters: {'n_layers': 1, 'hidden_size_0': 123, 'alpha': 3.1262055372744165e-06, 'learning_rate_init': 0.00035812041023792536}. Best is trial 38 with value: 0.1685101776418778.
[I 2025-08-19 19:35:55,856] Trial 41 finished with value: 0.30266306656789405 and parameters: {'n_layers': 1, 'hidden_size_0': 92, 'alpha': 2.693644442142605e-06, 'learning_rate_init': 0.0006879395728725316}. Best is trial 38 with value: 0.1685101776418778.
[I 2025-08-19 19:35:56,955] Trial 42 finished with value: 0.18485318440546114 and parameters: {'n_layers': 2, 'hidden_size_0': 71, 'hidden_size_1': 80, 'alpha': 1.6434784881152112e-06, 'learning_rate_init': 0.0005718980132498855}. Best is trial 38 with value: 0.1685101776418778.
[I 2025-08-19 19:35:59,205] Trial 43 finished with value: 12.644214484390377 and parameters: {'n_layers': 1, 'hidden_size_0': 70, 'alpha': 5.151762911090251e-06, 'learning_rate_init': 0.00018142052388234973}. Best is trial 38 with value: 0.1685101776418778.
[I 2025-08-19 19:36:01,310] Trial 44 finished with value: 0.3647163950003093 and parameters: {'n_layers': 2, 'hidden_size_0': 50, 'hidden_size_1': 79, 'alpha': 1.6600488753008908e-06, 'learning_rate_init': 0.0002380586011923054}. Best is trial 38 with value: 0.1685101776418778.
[I 2025-08-19 19:36:02,723] Trial 45 finished with value: 0.272810846291325 and parameters: {'n_layers': 2, 'hidden_size_0': 87, 'hidden_size_1': 42, 'alpha': 3.7059017512738844e-05, 'learning_rate_init': 0.000425156402897103}. Best is trial 38 with value: 0.1685101776418778.
[I 2025-08-19 19:36:03,842] Trial 46 finished with value: 0.684369753158586 and parameters: {'n_layers': 2, 'hidden_size_0': 33, 'hidden_size_1': 72, 'alpha': 4.300989019150095e-06, 'learning_rate_init': 0.0005460947262639754}. Best is trial 38 with value: 0.1685101776418778.
[I 2025-08-19 19:36:04,745] Trial 47 finished with value: 0.12639528039490205 and parameters: {'n_layers': 2, 'hidden_size_0': 107, 'hidden_size_1': 89, 'alpha': 2.040429345112942e-05, 'learning_rate_init': 0.001511987149316218}. Best is trial 47 with value: 0.12639528039490205.
[I 2025-08-19 19:36:05,641] Trial 48 finished with value: 0.21807982333723644 and parameters: {'n_layers': 1, 'hidden_size_0': 142, 'alpha': 1.7788708171592148e-05, 'learning_rate_init': 0.0012691019040191145}. Best is trial 47 with value: 0.12639528039490205.
[I 2025-08-19 19:36:06,578] Trial 49 finished with value: 2.068122412351761 and parameters: {'n_layers': 2, 'hidden_size_0': 133, 'hidden_size_1': 122, 'alpha': 1.058358190420158e-05, 'learning_rate_init': 0.0016892543237650884}. Best is trial 47 with value: 0.12639528039490205.
[I 2025-08-19 19:36:08,345] Trial 50 finished with value: 0.2409965231211336 and parameters: {'n_layers': 1, 'hidden_size_0': 105, 'alpha': 6.637416703169688e-05, 'learning_rate_init': 0.00033121224798118035}. Best is trial 47 with value: 0.12639528039490205.
[I 2025-08-19 19:36:10,778] Trial 51 finished with value: 0.09104284148576083 and parameters: {'n_layers': 2, 'hidden_size_0': 189, 'hidden_size_1': 86, 'alpha': 1.9358820336624017e-06, 'learning_rate_init': 0.0005460713456989244}. Best is trial 51 with value: 0.09104284148576083.
[I 2025-08-19 19:36:12,319] Trial 52 finished with value: 0.27622677676740837 and parameters: {'n_layers': 2, 'hidden_size_0': 191, 'hidden_size_1': 92, 'alpha': 6.532890981185493e-06, 'learning_rate_init': 0.0012719119412558943}. Best is trial 51 with value: 0.09104284148576083.
[I 2025-08-19 19:36:14,949] Trial 53 finished with value: 0.19708379301097784 and parameters: {'n_layers': 2, 'hidden_size_0': 185, 'hidden_size_1': 58, 'alpha': 2.4552095707622776e-06, 'learning_rate_init': 0.00022802395592096516}. Best is trial 51 with value: 0.09104284148576083.
[I 2025-08-19 19:36:15,809] Trial 54 finished with value: 0.7467888064387183 and parameters: {'n_layers': 2, 'hidden_size_0': 157, 'hidden_size_1': 101, 'alpha': 3.586351444149902e-06, 'learning_rate_init': 0.0022916204123304184}. Best is trial 51 with value: 0.09104284148576083.
[I 2025-08-19 19:36:16,934] Trial 55 finished with value: 0.17439636012618154 and parameters: {'n_layers': 1, 'hidden_size_0': 147, 'alpha': 1.4783055367687117e-06, 'learning_rate_init': 0.0007987186837958068}. Best is trial 51 with value: 0.09104284148576083.
[I 2025-08-19 19:36:17,824] Trial 56 finished with value: 0.15344418754354933 and parameters: {'n_layers': 1, 'hidden_size_0': 120, 'alpha': 1.3679722161166742e-06, 'learning_rate_init': 0.0007403477410934367}. Best is trial 51 with value: 0.09104284148576083.
[I 2025-08-19 19:36:19,492] Trial 57 finished with value: 0.14114392735390097 and parameters: {'n_layers': 1, 'hidden_size_0': 146, 'alpha': 1.4391741928259682e-06, 'learning_rate_init': 0.0007815784140794674}. Best is trial 51 with value: 0.09104284148576083.
[I 2025-08-19 19:36:20,047] Trial 58 finished with value: 0.2643555138505479 and parameters: {'n_layers': 1, 'hidden_size_0': 118, 'alpha': 2.6387677561394486e-05, 'learning_rate_init': 0.0010890210431766271}. Best is trial 51 with value: 0.09104284148576083.
[I 2025-08-19 19:36:20,942] Trial 59 finished with value: 0.4472308736439645 and parameters: {'n_layers': 1, 'hidden_size_0': 170, 'alpha': 1.4530537759250195e-06, 'learning_rate_init': 0.0018714921278655172}. Best is trial 51 with value: 0.09104284148576083.
[I 2025-08-19 19:36:23,076] Trial 60 finished with value: 0.2186932450622708 and parameters: {'n_layers': 1, 'hidden_size_0': 148, 'alpha': 0.00022767431049666183, 'learning_rate_init': 0.0006135222073479154}. Best is trial 51 with value: 0.09104284148576083.
[I 2025-08-19 19:36:23,685] Trial 61 finished with value: 0.1753096467928354 and parameters: {'n_layers': 1, 'hidden_size_0': 150, 'alpha': 1.7305546214144242e-06, 'learning_rate_init': 0.001419971880715104}. Best is trial 51 with value: 0.09104284148576083.
[I 2025-08-19 19:36:24,785] Trial 62 finished with value: 0.23443653343411328 and parameters: {'n_layers': 1, 'hidden_size_0': 127, 'alpha': 1.2762164921943067e-06, 'learning_rate_init': 0.0007848137918782442}. Best is trial 51 with value: 0.09104284148576083.
[I 2025-08-19 19:36:25,548] Trial 63 finished with value: 0.20329502201751715 and parameters: {'n_layers': 1, 'hidden_size_0': 109, 'alpha': 5.527018359220345e-06, 'learning_rate_init': 0.000813336525101838}. Best is trial 51 with value: 0.09104284148576083.
[I 2025-08-19 19:36:27,342] Trial 64 finished with value: 0.20231765580970312 and parameters: {'n_layers': 1, 'hidden_size_0': 181, 'alpha': 2.0258816243991065e-06, 'learning_rate_init': 0.0004844895891683771}. Best is trial 51 with value: 0.09104284148576083.
[I 2025-08-19 19:36:30,673] Trial 65 finished with value: 0.19662143320398734 and parameters: {'n_layers': 1, 'hidden_size_0': 141, 'alpha': 3.370298000328211e-06, 'learning_rate_init': 0.000341982252417451}. Best is trial 51 with value: 0.09104284148576083.
[I 2025-08-19 19:36:30,954] Trial 66 finished with value: 6.233767700404125 and parameters: {'n_layers': 1, 'hidden_size_0': 164, 'alpha': 1.3033110382552268e-06, 'learning_rate_init': 0.002932248096445039}. Best is trial 51 with value: 0.09104284148576083.
[I 2025-08-19 19:36:31,430] Trial 67 finished with value: 0.19920815630956648 and parameters: {'n_layers': 1, 'hidden_size_0': 90, 'alpha': 8.918153420693066e-06, 'learning_rate_init': 0.0010730704937036543}. Best is trial 51 with value: 0.09104284148576083.
[I 2025-08-19 19:36:31,901] Trial 68 finished with value: 0.15536643998772237 and parameters: {'n_layers': 1, 'hidden_size_0': 117, 'alpha': 4.4089804720572534e-06, 'learning_rate_init': 0.0018342174477751732}. Best is trial 51 with value: 0.09104284148576083.
[I 2025-08-19 19:36:32,202] Trial 69 finished with value: 1.1592945824072918 and parameters: {'n_layers': 1, 'hidden_size_0': 118, 'alpha': 4.52432263668358e-06, 'learning_rate_init': 0.0019978302978277893}. Best is trial 51 with value: 0.09104284148576083.
[I 2025-08-19 19:36:32,454] Trial 70 finished with value: 16.079196872324907 and parameters: {'n_layers': 1, 'hidden_size_0': 128, 'alpha': 3.0067618731465895e-06, 'learning_rate_init': 0.004945031028791398}. Best is trial 51 with value: 0.09104284148576083.
[I 2025-08-19 19:36:33,168] Trial 71 finished with value: 0.2565032705788726 and parameters: {'n_layers': 1, 'hidden_size_0': 85, 'alpha': 2.0339037525688446e-06, 'learning_rate_init': 0.0007622903203556799}. Best is trial 51 with value: 0.09104284148576083.

[I 2025-08-19 19:37:05,391] A new study created in memory with name: no-name-a7c46f45-2c85-4ae4-bcbf-664630c398f6

[I 2025-08-19 19:37:05,385] Trial 99 finished with value: 0.2914634124615293 and parameters: {'n_layers': 1, 'hidden_size_0': 145, 'alpha': 2.917507340098048e-06, 'learning_rate_init': 0.0005686592522072908}. Best is trial 51 with value: 0.09104284148576083.
    Best NN MSE: 0.091043
  Optimizing XGBoost...

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2025-08-19 19:37:06,615] Trial 0 finished with value: 2.4229641199111938 and parameters: {'n_estimators': 258, 'max_depth': 9, 'learning_rate': 0.2868097549949875, 'subsample': 0.7855361528214284, 'colsample_bytree': 0.8949975776223627, 'reg_alpha': 0.3320102363966625, 'reg_lambda': 0.5110654892617195}. Best is trial 0 with value: 2.4229641199111938.
[I 2025-08-19 19:37:07,938] Trial 1 finished with value: 206.14384117126465 and parameters: {'n_estimators': 180, 'max_depth': 9, 'learning_rate': 0.2796411269270747, 'subsample': 0.7933702148684326, 'colsample_bytree': 0.6820362600374056, 'reg_alpha': 0.015032244738287792, 'reg_lambda': 0.08755316586959205}. Best is trial 0 with value: 2.4229641199111938.
[I 2025-08-19 19:37:10,615] Trial 2 finished with value: 31.119950771331787 and parameters: {'n_estimators': 161, 'max_depth': 6, 'learning_rate': 0.1878953431482189, 'subsample': 0.8915671114884505, 'colsample_bytree': 0.8123394253137142, 'reg_alpha': 0.5345027511515238, 'reg_lambda': 0.6695520821461635}. Best is trial 0 with value: 2.4229641199111938.
[I 2025-08-19 19:37:14,132] Trial 3 finished with value: 18.826025772094727 and parameters: {'n_estimators': 413, 'max_depth': 5, 'learning_rate': 0.02330492566401024, 'subsample': 0.6380734147609546, 'colsample_bytree': 0.7084632067144855, 'reg_alpha': 0.7008700794530022, 'reg_lambda': 0.010623140491635374}. Best is trial 0 with value: 2.4229641199111938.
[I 2025-08-19 19:37:15,384] Trial 4 finished with value: 2.9248695850372313 and parameters: {'n_estimators': 432, 'max_depth': 6, 'learning_rate': 0.12021091525697909, 'subsample': 0.9569496331670797, 'colsample_bytree': 0.870226990068316, 'reg_alpha': 0.7312240315039474, 'reg_lambda': 0.435093453351329}. Best is trial 0 with value: 2.4229641199111938.
[I 2025-08-19 19:37:18,153] Trial 5 finished with value: 69.1453742980957 and parameters: {'n_estimators': 173, 'max_depth': 8, 'learning_rate': 0.08691771756991429, 'subsample': 0.6088455034591104, 'colsample_bytree': 0.6681143463440867, 'reg_alpha': 0.32542120056118984, 'reg_lambda': 0.0041135098313099805}. Best is trial 0 with value: 2.4229641199111938.
[I 2025-08-19 19:37:18,863] Trial 6 finished with value: 2.024068593978882 and parameters: {'n_estimators': 247, 'max_depth': 4, 'learning_rate': 0.19806639115434782, 'subsample': 0.6700024796424326, 'colsample_bytree': 0.9299722797191209, 'reg_alpha': 0.43794163794797203, 'reg_lambda': 0.02396063029390616}. Best is trial 6 with value: 2.024068593978882.
[I 2025-08-19 19:37:19,537] Trial 7 finished with value: 24.22957401275635 and parameters: {'n_estimators': 342, 'max_depth': 3, 'learning_rate': 0.24113901075722252, 'subsample': 0.7850682737528474, 'colsample_bytree': 0.8073724882416142, 'reg_alpha': 0.01937463403047257, 'reg_lambda': 0.9363830553724265}. Best is trial 6 with value: 2.024068593978882.
[I 2025-08-19 19:37:20,018] Trial 8 finished with value: 7.957479238510132 and parameters: {'n_estimators': 78, 'max_depth': 5, 'learning_rate': 0.2929950878885234, 'subsample': 0.8283459221308414, 'colsample_bytree': 0.8479684819767384, 'reg_alpha': 0.342864361117479, 'reg_lambda': 0.475341108248701}. Best is trial 6 with value: 2.024068593978882.
[I 2025-08-19 19:37:22,198] Trial 9 finished with value: 25.223766040802 and parameters: {'n_estimators': 472, 'max_depth': 4, 'learning_rate': 0.032558088778383364, 'subsample': 0.8489797501078457, 'colsample_bytree': 0.7548199148748489, 'reg_alpha': 0.5163822278837185, 'reg_lambda': 0.9659068497351706}. Best is trial 6 with value: 2.024068593978882.
[I 2025-08-19 19:37:23,444] Trial 10 finished with value: 1.9119411706924438 and parameters: {'n_estimators': 335, 'max_depth': 3, 'learning_rate': 0.1872848218450139, 'subsample': 0.6993642643004209, 'colsample_bytree': 0.9981341962753011, 'reg_alpha': 0.9258835810465541, 'reg_lambda': 0.22988284856541494}. Best is trial 10 with value: 1.9119411706924438.
[I 2025-08-19 19:37:24,367] Trial 11 finished with value: 2.0824222564697266 and parameters: {'n_estimators': 309, 'max_depth': 3, 'learning_rate': 0.18997222684394377, 'subsample': 0.6929233501126211, 'colsample_bytree': 0.995825475924077, 'reg_alpha': 0.9938772419949407, 'reg_lambda': 0.2335631727203537}. Best is trial 10 with value: 1.9119411706924438.
[I 2025-08-19 19:37:25,029] Trial 12 finished with value: 2.006594717502594 and parameters: {'n_estimators': 249, 'max_depth': 3, 'learning_rate': 0.19912928235442232, 'subsample': 0.6951200153014897, 'colsample_bytree': 0.9954960824170772, 'reg_alpha': 0.9859926578458946, 'reg_lambda': 0.24217586412147524}. Best is trial 10 with value: 1.9119411706924438.
[I 2025-08-19 19:37:26,035] Trial 13 finished with value: 1.8590033769607544 and parameters: {'n_estimators': 350, 'max_depth': 3, 'learning_rate': 0.14583711586972697, 'subsample': 0.7410933182998429, 'colsample_bytree': 0.9783766501623693, 'reg_alpha': 0.9754010391240079, 'reg_lambda': 0.2632746459459968}. Best is trial 13 with value: 1.8590033769607544.
[I 2025-08-19 19:37:27,450] Trial 14 finished with value: 1.875775408744812 and parameters: {'n_estimators': 330, 'max_depth': 7, 'learning_rate': 0.13462764611697792, 'subsample': 0.7343107457608639, 'colsample_bytree': 0.9443705985890376, 'reg_alpha': 0.8064636010580248, 'reg_lambda': 0.252161626938282}. Best is trial 13 with value: 1.8590033769607544.
[I 2025-08-19 19:37:28,681] Trial 15 finished with value: 110.63833236694336 and parameters: {'n_estimators': 390, 'max_depth': 7, 'learning_rate': 0.12795942279004577, 'subsample': 0.7407297324941162, 'colsample_bytree': 0.6073046007031884, 'reg_alpha': 0.8110002304115447, 'reg_lambda': 0.3337680074102888}. Best is trial 13 with value: 1.8590033769607544.
[I 2025-08-19 19:37:31,323] Trial 16 finished with value: 1.8666927576065064 and parameters: {'n_estimators': 498, 'max_depth': 10, 'learning_rate': 0.08897406920531206, 'subsample': 0.738416443060038, 'colsample_bytree': 0.9316848729024078, 'reg_alpha': 0.8526781656779027, 'reg_lambda': 0.6527809766476269}. Best is trial 13 with value: 1.8590033769607544.
[I 2025-08-19 19:37:33,304] Trial 17 finished with value: 1.801945185661316 and parameters: {'n_estimators': 444, 'max_depth': 10, 'learning_rate': 0.08116625491443873, 'subsample': 0.74129483579254, 'colsample_bytree': 0.9315645763884277, 'reg_alpha': 0.6499347613530091, 'reg_lambda': 0.7074404437148989}. Best is trial 17 with value: 1.801945185661316.
[I 2025-08-19 19:37:35,411] Trial 18 finished with value: 1.8460678577423095 and parameters: {'n_estimators': 372, 'max_depth': 10, 'learning_rate': 0.0673772495456012, 'subsample': 0.8991866927001761, 'colsample_bytree': 0.9532046369292468, 'reg_alpha': 0.6081071506386712, 'reg_lambda': 0.7673785237887013}. Best is trial 17 with value: 1.801945185661316.
[I 2025-08-19 19:37:37,515] Trial 19 finished with value: 2.809029054641724 and parameters: {'n_estimators': 449, 'max_depth': 10, 'learning_rate': 0.07653746221625551, 'subsample': 0.9848998084782115, 'colsample_bytree': 0.9030533074964808, 'reg_alpha': 0.6332501098253568, 'reg_lambda': 0.8078069386446991}. Best is trial 17 with value: 1.801945185661316.
[I 2025-08-19 19:37:39,940] Trial 20 finished with value: 8.844351482391357 and parameters: {'n_estimators': 396, 'max_depth': 9, 'learning_rate': 0.05427544337732998, 'subsample': 0.8826793202940959, 'colsample_bytree': 0.8418648023110671, 'reg_alpha': 0.16112704190696914, 'reg_lambda': 0.8005614257862144}. Best is trial 17 with value: 1.801945185661316.
[I 2025-08-19 19:37:41,353] Trial 21 finished with value: 1.9654237508773804 and parameters: {'n_estimators': 364, 'max_depth': 10, 'learning_rate': 0.1572121215346755, 'subsample': 0.9242043220140677, 'colsample_bytree': 0.9556555624481182, 'reg_alpha': 0.6664231546319666, 'reg_lambda': 0.6313314676561597}. Best is trial 17 with value: 1.801945185661316.
[I 2025-08-19 19:37:43,268] Trial 22 finished with value: 1.8976480484008789 and parameters: {'n_estimators': 300, 'max_depth': 8, 'learning_rate': 0.0633558602654242, 'subsample': 0.8300640993266417, 'colsample_bytree': 0.9549640794695173, 'reg_alpha': 0.5625299854888854, 'reg_lambda': 0.7880179896253702}. Best is trial 17 with value: 1.801945185661316.
[I 2025-08-19 19:37:45,441] Trial 23 finished with value: 2.6251445055007934 and parameters: {'n_estimators': 380, 'max_depth': 8, 'learning_rate': 0.10578522524969763, 'subsample': 0.7532084748862935, 'colsample_bytree': 0.896112616337208, 'reg_alpha': 0.4188815537150852, 'reg_lambda': 0.5528112951961908}. Best is trial 17 with value: 1.801945185661316.
[I 2025-08-19 19:37:47,071] Trial 24 finished with value: 1.9768911361694337 and parameters: {'n_estimators': 454, 'max_depth': 9, 'learning_rate': 0.15012514240744723, 'subsample': 0.8789024236326202, 'colsample_bytree': 0.9801337175006023, 'reg_alpha': 0.6089442573374072, 'reg_lambda': 0.8774141016054462}. Best is trial 17 with value: 1.801945185661316.
[I 2025-08-19 19:37:49,609] Trial 25 finished with value: 2.3077943325042725 and parameters: {'n_estimators': 420, 'max_depth': 10, 'learning_rate': 0.04593673132578222, 'subsample': 0.7693314923150417, 'colsample_bytree': 0.9141441196141372, 'reg_alpha': 0.7399600805000046, 'reg_lambda': 0.7164611434133529}. Best is trial 17 with value: 1.801945185661316.
[I 2025-08-19 19:37:53,424] Trial 26 finished with value: 2.123076248168945 and parameters: {'n_estimators': 498, 'max_depth': 5, 'learning_rate': 0.013032055684354928, 'subsample': 0.825805470779134, 'colsample_bytree': 0.9623508311881523, 'reg_alpha': 0.8998301162702587, 'reg_lambda': 0.5573617254314862}. Best is trial 17 with value: 1.801945185661316.
[I 2025-08-19 19:37:54,985] Trial 27 finished with value: 3.087679648399353 and parameters: {'n_estimators': 361, 'max_depth': 8, 'learning_rate': 0.1047322436875239, 'subsample': 0.927680161156834, 'colsample_bytree': 0.8714038480889148, 'reg_alpha': 0.46478135966486983, 'reg_lambda': 0.37715038310749693}. Best is trial 17 with value: 1.801945185661316.
[I 2025-08-19 19:37:56,481] Trial 28 finished with value: 1.9828582525253295 and parameters: {'n_estimators': 284, 'max_depth': 7, 'learning_rate': 0.16022023253027992, 'subsample': 0.7174870151668793, 'colsample_bytree': 0.963738613196555, 'reg_alpha': 0.18187236024916653, 'reg_lambda': 0.7536892422131704}. Best is trial 17 with value: 1.801945185661316.
[I 2025-08-19 19:37:58,398] Trial 29 finished with value: 2.3296257734298704 and parameters: {'n_estimators': 270, 'max_depth': 9, 'learning_rate': 0.06901706476572307, 'subsample': 0.6549192877006642, 'colsample_bytree': 0.87921223975072, 'reg_alpha': 0.78281498802686, 'reg_lambda': 0.8683211228176484}. Best is trial 17 with value: 1.801945185661316.
[I 2025-08-19 19:37:59,302] Trial 30 finished with value: 25.002127265930177 and parameters: {'n_estimators': 220, 'max_depth': 4, 'learning_rate': 0.1023996118290448, 'subsample': 0.766052421094216, 'colsample_bytree': 0.7726654921638396, 'reg_alpha': 0.5844625528571794, 'reg_lambda': 0.6172381951736233}. Best is trial 17 with value: 1.801945185661316.
[I 2025-08-19 19:38:01,590] Trial 31 finished with value: 1.818366241455078 and parameters: {'n_estimators': 500, 'max_depth': 10, 'learning_rate': 0.0833109037549652, 'subsample': 0.7279345864842983, 'colsample_bytree': 0.9267008078130342, 'reg_alpha': 0.8619178060905631, 'reg_lambda': 0.6982355243501572}. Best is trial 17 with value: 1.801945185661316.
[I 2025-08-19 19:38:04,217] Trial 32 finished with value: 2.4121594429016113 and parameters: {'n_estimators': 466, 'max_depth': 9, 'learning_rate': 0.044873923944539956, 'subsample': 0.7983739285993404, 'colsample_bytree': 0.9194647221664586, 'reg_alpha': 0.9200493699022946, 'reg_lambda': 0.6981812994362911}. Best is trial 17 with value: 1.801945185661316.
[I 2025-08-19 19:38:06,061] Trial 33 finished with value: 1.909476399421692 and parameters: {'n_estimators': 433, 'max_depth': 10, 'learning_rate': 0.08431221240211056, 'subsample': 0.7229039712884063, 'colsample_bytree': 0.9723221883102686, 'reg_alpha': 0.8635208653447775, 'reg_lambda': 0.15825492312383815}. Best is trial 17 with value: 1.801945185661316.
[I 2025-08-19 19:38:07,311] Trial 34 finished with value: 9.24402837753296 and parameters: {'n_estimators': 407, 'max_depth': 9, 'learning_rate': 0.26515321410473125, 'subsample': 0.7876299921777382, 'colsample_bytree': 0.8381567128311269, 'reg_alpha': 0.6619011433288812, 'reg_lambda': 0.5865420696496719}. Best is trial 17 with value: 1.801945185661316.
[I 2025-08-19 19:38:09,597] Trial 35 finished with value: 1.82375910282135 and parameters: {'n_estimators': 482, 'max_depth': 10, 'learning_rate': 0.11409086769868593, 'subsample': 0.6726649250884448, 'colsample_bytree': 0.942914971997178, 'reg_alpha': 0.7636973411406435, 'reg_lambda': 0.4832660895336318}. Best is trial 17 with value: 1.801945185661316.
[I 2025-08-19 19:38:11,558] Trial 36 finished with value: 1.98997962474823 and parameters: {'n_estimators': 472, 'max_depth': 10, 'learning_rate': 0.11545309983026131, 'subsample': 0.637030187857231, 'colsample_bytree': 0.8895003988874491, 'reg_alpha': 0.7608498662022027, 'reg_lambda': 0.4917177247442343}. Best is trial 17 with value: 1.801945185661316.
[I 2025-08-19 19:38:14,457] Trial 37 finished with value: 1.5749146699905396 and parameters: {'n_estimators': 500, 'max_depth': 10, 'learning_rate': 0.03534974619540455, 'subsample': 0.6102406524005818, 'colsample_bytree': 0.9408617461244262, 'reg_alpha': 0.6985592665793416, 'reg_lambda': 0.41888748933276365}. Best is trial 37 with value: 1.5749146699905396.
[I 2025-08-19 19:38:17,628] Trial 38 finished with value: 1.5525023221969605 and parameters: {'n_estimators': 497, 'max_depth': 9, 'learning_rate': 0.030616039646095248, 'subsample': 0.6086454800124534, 'colsample_bytree': 0.9334602635627671, 'reg_alpha': 0.7077919174123913, 'reg_lambda': 0.416299934480547}. Best is trial 38 with value: 1.5525023221969605.
[I 2025-08-19 19:38:21,425] Trial 39 finished with value: 4.361101388931274 and parameters: {'n_estimators': 441, 'max_depth': 9, 'learning_rate': 0.029723415652737832, 'subsample': 0.6004703956412925, 'colsample_bytree': 0.8623631133553646, 'reg_alpha': 0.7085127639271047, 'reg_lambda': 0.3504642987180813}. Best is trial 38 with value: 1.5525023221969605.
[I 2025-08-19 19:38:26,335] Trial 40 finished with value: 3.840821719169617 and parameters: {'n_estimators': 500, 'max_depth': 8, 'learning_rate': 0.010447320217873, 'subsample': 0.6233322860650101, 'colsample_bytree': 0.9220365146079751, 'reg_alpha': 0.6970389383315365, 'reg_lambda': 0.4284562143597832}. Best is trial 38 with value: 1.5525023221969605.
[I 2025-08-19 19:38:29,125] Trial 41 finished with value: 3.234997057914734 and parameters: {'n_estimators': 478, 'max_depth': 10, 'learning_rate': 0.040789631876948354, 'subsample': 0.655050902998656, 'colsample_bytree': 0.9061244648775091, 'reg_alpha': 0.8425322912820086, 'reg_lambda': 0.4357884511038272}. Best is trial 38 with value: 1.5525023221969605.
[I 2025-08-19 19:38:31,779] Trial 42 finished with value: 1.8375982761383056 and parameters: {'n_estimators': 481, 'max_depth': 10, 'learning_rate': 0.09441782226654863, 'subsample': 0.6728634856506528, 'colsample_bytree': 0.9403467450170092, 'reg_alpha': 0.77276664130655, 'reg_lambda': 0.5207446868999419}. Best is trial 38 with value: 1.5525023221969605.
[I 2025-08-19 19:38:33,096] Trial 43 finished with value: 11.628547859191894 and parameters: {'n_estimators': 129, 'max_depth': 9, 'learning_rate': 0.05288380074641233, 'subsample': 0.620455250564145, 'colsample_bytree': 0.8187137357852778, 'reg_alpha': 0.6724438462979994, 'reg_lambda': 0.40828777359105206}. Best is trial 38 with value: 1.5525023221969605.
[I 2025-08-19 19:38:35,921] Trial 44 finished with value: 1.8691739320755005 and parameters: {'n_estimators': 457, 'max_depth': 10, 'learning_rate': 0.022564429200363372, 'subsample': 0.6722400477387684, 'colsample_bytree': 0.9355139572428565, 'reg_alpha': 0.7255704157873712, 'reg_lambda': 0.2988876383827421}. Best is trial 38 with value: 1.5525023221969605.
[I 2025-08-19 19:38:37,977] Trial 45 finished with value: 12.884492492675781 and parameters: {'n_estimators': 415, 'max_depth': 10, 'learning_rate': 0.07634118358652334, 'subsample': 0.642201350131357, 'colsample_bytree': 0.7800047183818016, 'reg_alpha': 0.5335405129527677, 'reg_lambda': 0.45643482500414334}. Best is trial 38 with value: 1.5525023221969605.
[I 2025-08-19 19:38:40,956] Trial 46 finished with value: 35.27968425750733 and parameters: {'n_estimators': 486, 'max_depth': 9, 'learning_rate': 0.058561425105110615, 'subsample': 0.7068465918799621, 'colsample_bytree': 0.694801020497922, 'reg_alpha': 0.820184581300174, 'reg_lambda': 0.5120046330851833}. Best is trial 38 with value: 1.5525023221969605.
[I 2025-08-19 19:38:42,457] Trial 47 finished with value: 2.0870824337005613 and parameters: {'n_estimators': 433, 'max_depth': 10, 'learning_rate': 0.1181043209766553, 'subsample': 0.6828206656225265, 'colsample_bytree': 0.8916828131290357, 'reg_alpha': 0.7609868311342879, 'reg_lambda': 0.38336218943359307}. Best is trial 38 with value: 1.5525023221969605.
[I 2025-08-19 19:38:44,941] Trial 48 finished with value: 1.8158092021942138 and parameters: {'n_estimators': 465, 'max_depth': 8, 'learning_rate': 0.03769637682362979, 'subsample': 0.6183094584687259, 'colsample_bytree': 0.984296301138933, 'reg_alpha': 0.8840397931875136, 'reg_lambda': 0.16804248632478508}. Best is trial 38 with value: 1.5525023221969605.
[I 2025-08-19 19:38:47,997] Trial 49 finished with value: 1.8851859092712402 and parameters: {'n_estimators': 450, 'max_depth': 8, 'learning_rate': 0.03307550927243408, 'subsample': 0.6163430464042842, 'colsample_bytree': 0.9894398972216614, 'reg_alpha': 0.9452523037430176, 'reg_lambda': 0.08018877549552539}. Best is trial 38 with value: 1.5525023221969605.
[I 2025-08-19 19:38:50,994] Trial 50 finished with value: 1.796376371383667 and parameters: {'n_estimators': 421, 'max_depth': 6, 'learning_rate': 0.023718005888823696, 'subsample': 0.6322448521812122, 'colsample_bytree': 0.98472762552228, 'reg_alpha': 0.8854477235187606, 'reg_lambda': 0.127722685013814}. Best is trial 38 with value: 1.5525023221969605.
[I 2025-08-19 19:38:54,068] Trial 51 finished with value: 1.7499848127365112 and parameters: {'n_estimators': 464, 'max_depth': 6, 'learning_rate': 0.02240943561615348, 'subsample': 0.6010685644464008, 'colsample_bytree': 0.972738803034823, 'reg_alpha': 0.872971736714543, 'reg_lambda': 0.17162068313666284}. Best is trial 38 with value: 1.5525023221969605.
[I 2025-08-19 19:38:56,693] Trial 52 finished with value: 1.7795063495635985 and parameters: {'n_estimators': 426, 'max_depth': 6, 'learning_rate': 0.02143046076840279, 'subsample': 0.6019730819522537, 'colsample_bytree': 0.9792310701882859, 'reg_alpha': 0.8847661591098333, 'reg_lambda': 0.16039926229037688}. Best is trial 38 with value: 1.5525023221969605.
[I 2025-08-19 19:39:00,044] Trial 53 finished with value: 1.8561072587966918 and parameters: {'n_estimators': 421, 'max_depth': 6, 'learning_rate': 0.0183311353195659, 'subsample': 0.6004188574438002, 'colsample_bytree': 0.9997797473532356, 'reg_alpha': 0.9422625085829267, 'reg_lambda': 0.19021449605866106}. Best is trial 38 with value: 1.5525023221969605.
[I 2025-08-19 19:39:02,667] Trial 54 finished with value: 1.7778446674346924 and parameters: {'n_estimators': 390, 'max_depth': 6, 'learning_rate': 0.027226268861344563, 'subsample': 0.6359117854787161, 'colsample_bytree': 0.971488925886021, 'reg_alpha': 0.8102395295266562, 'reg_lambda': 0.10059080286377423}. Best is trial 38 with value: 1.5525023221969605.

[I 2025-08-19 19:40:48,894] A new study created in memory with name: no-name-b617a960-f158-4126-afcd-fef6cdf1e8aa

[I 2025-08-19 19:40:48,886] Trial 99 finished with value: 1.8489083051681519 and parameters: {'n_estimators': 481, 'max_depth': 7, 'learning_rate': 0.03175571685223396, 'subsample': 0.6372441653562613, 'colsample_bytree': 0.990870983323584, 'reg_alpha': 0.7450760472324092, 'reg_lambda': 0.5378853720434046}. Best is trial 38 with value: 1.5525023221969605.
    Best XGBoost MSE: 1.552502

Optimizing for dataset: Si_TE
  Optimizing SVR...

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2025-08-19 19:40:48,925] Trial 0 finished with value: 924.7983983219226 and parameters: {'C': 0.7080166777372641, 'gamma': 0.03664288488964582, 'epsilon': 0.7303805334596838}. Best is trial 0 with value: 924.7983983219226.
[I 2025-08-19 19:40:48,946] Trial 1 finished with value: 925.0888587043835 and parameters: {'C': 0.716739811622706, 'gamma': 0.026605024569958235, 'epsilon': 0.009909020096150061}. Best is trial 0 with value: 924.7983983219226.
[I 2025-08-19 19:40:48,966] Trial 2 finished with value: 190.88440226426403 and parameters: {'C': 1.1072914768800126, 'gamma': 5.503780404533425e-05, 'epsilon': 0.3479369431596531}. Best is trial 2 with value: 190.88440226426403.
[I 2025-08-19 19:40:48,994] Trial 3 finished with value: 70.22533913436806 and parameters: {'C': 52.38270938257665, 'gamma': 0.0007953407290028804, 'epsilon': 0.0041235565070253995}. Best is trial 3 with value: 70.22533913436806.
[I 2025-08-19 19:40:49,015] Trial 4 finished with value: 923.2759429834335 and parameters: {'C': 0.011484946565558417, 'gamma': 3.3521156622013896e-06, 'epsilon': 0.005522897166504355}. Best is trial 3 with value: 70.22533913436806.
[I 2025-08-19 19:40:49,032] Trial 5 finished with value: 909.3671154782944 and parameters: {'C': 0.8238571129572483, 'gamma': 0.004792844142778419, 'epsilon': 0.15372812711578807}. Best is trial 3 with value: 70.22533913436806.
[I 2025-08-19 19:40:49,051] Trial 6 finished with value: 814.4504552343423 and parameters: {'C': 1.3286000153927777, 'gamma': 0.0016107068546676673, 'epsilon': 0.10201317075512983}. Best is trial 3 with value: 70.22533913436806.
[I 2025-08-19 19:40:49,079] Trial 7 finished with value: 1.89259486754669 and parameters: {'C': 16.855013503209154, 'gamma': 8.28218838461416e-05, 'epsilon': 0.0013728944900654164}. Best is trial 7 with value: 1.89259486754669.
[I 2025-08-19 19:40:49,123] Trial 8 finished with value: 901.9226535960504 and parameters: {'C': 0.024028914251212098, 'gamma': 4.2359234267462355e-05, 'epsilon': 0.12665147101972324}. Best is trial 7 with value: 1.89259486754669.
[I 2025-08-19 19:40:49,150] Trial 9 finished with value: 925.6395097334229 and parameters: {'C': 0.011027893465400396, 'gamma': 0.12079654162943208, 'epsilon': 0.019428094060121262}. Best is trial 7 with value: 1.89259486754669.
[I 2025-08-19 19:40:49,212] Trial 10 finished with value: 0.07495922286557577 and parameters: {'C': 51.70222977150333, 'gamma': 3.3292485699658947e-06, 'epsilon': 0.0010253718120924727}. Best is trial 10 with value: 0.07495922286557577.
[I 2025-08-19 19:40:49,251] Trial 11 finished with value: 0.11217983534009741 and parameters: {'C': 85.42348757968868, 'gamma': 1.1154406725445421e-06, 'epsilon': 0.0012795966681601113}. Best is trial 10 with value: 0.07495922286557577.
[I 2025-08-19 19:40:49,281] Trial 12 finished with value: 0.17929281364519883 and parameters: {'C': 48.46159798985091, 'gamma': 1.7476210261657477e-06, 'epsilon': 0.0012143194777005564}. Best is trial 10 with value: 0.07495922286557577.
[I 2025-08-19 19:40:49,306] Trial 13 finished with value: 2.455122533967802 and parameters: {'C': 8.372649683289024, 'gamma': 8.770101098559268e-06, 'epsilon': 0.0026978741259317237}. Best is trial 10 with value: 0.07495922286557577.
[I 2025-08-19 19:40:49,332] Trial 14 finished with value: 0.11213926623359986 and parameters: {'C': 94.51679095184821, 'gamma': 1.0011144508177092e-06, 'epsilon': 0.03077770181525936}. Best is trial 10 with value: 0.07495922286557577.
[I 2025-08-19 19:40:49,365] Trial 15 finished with value: 916.3516709241405 and parameters: {'C': 9.342318408960328, 'gamma': 0.8460123301163074, 'epsilon': 0.038393756884340734}. Best is trial 10 with value: 0.07495922286557577.
[I 2025-08-19 19:40:49,390] Trial 16 finished with value: 16.80235330715376 and parameters: {'C': 3.9367422867652775, 'gamma': 1.2887929196439626e-05, 'epsilon': 0.03750090068705841}. Best is trial 10 with value: 0.07495922286557577.
[I 2025-08-19 19:40:49,411] Trial 17 finished with value: 867.2772414120336 and parameters: {'C': 0.13401569015354817, 'gamma': 0.0003089971118777482, 'epsilon': 0.013909452488898669}. Best is trial 10 with value: 0.07495922286557577.
[I 2025-08-19 19:40:49,433] Trial 18 finished with value: 0.136037207548017 and parameters: {'C': 30.520979531528607, 'gamma': 6.8634672503189825e-06, 'epsilon': 0.0639692398054048}. Best is trial 10 with value: 0.07495922286557577.
[I 2025-08-19 19:40:49,456] Trial 19 finished with value: 656.6734090981471 and parameters: {'C': 4.119297826379969, 'gamma': 1.0782149542974932e-06, 'epsilon': 0.006334127778159706}. Best is trial 10 with value: 0.07495922286557577.
[I 2025-08-19 19:40:49,478] Trial 20 finished with value: 0.9197894650875398 and parameters: {'C': 24.701424037920553, 'gamma': 1.8452864027845292e-05, 'epsilon': 0.9945982729319375}. Best is trial 10 with value: 0.07495922286557577.
[I 2025-08-19 19:40:49,501] Trial 21 finished with value: 0.18563255168409837 and parameters: {'C': 60.20961578639933, 'gamma': 1.257701346704906e-06, 'epsilon': 0.0022559060344579914}. Best is trial 10 with value: 0.07495922286557577.
[I 2025-08-19 19:40:49,526] Trial 22 finished with value: 0.03473266401900428 and parameters: {'C': 98.75767389170873, 'gamma': 3.386471508452206e-06, 'epsilon': 0.0010454161474260342}. Best is trial 22 with value: 0.03473266401900428.
[I 2025-08-19 19:40:49,552] Trial 23 finished with value: 5.127241998206228 and parameters: {'C': 90.8374217841294, 'gamma': 0.00017838288788758132, 'epsilon': 0.0023657036289726455}. Best is trial 22 with value: 0.03473266401900428.
[I 2025-08-19 19:40:49,577] Trial 24 finished with value: 1.2786432341458271 and parameters: {'C': 12.95162371222807, 'gamma': 4.30308296277909e-06, 'epsilon': 0.0010198781809987406}. Best is trial 22 with value: 0.03473266401900428.
[I 2025-08-19 19:40:49,604] Trial 25 finished with value: 0.14829317841251557 and parameters: {'C': 29.80645460370774, 'gamma': 1.5269794089124953e-05, 'epsilon': 0.008735240259429712}. Best is trial 22 with value: 0.03473266401900428.
[I 2025-08-19 19:40:49,627] Trial 26 finished with value: 0.034510470727262724 and parameters: {'C': 98.39556131829022, 'gamma': 3.5192320328699353e-06, 'epsilon': 0.003084683544165717}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:49,650] Trial 27 finished with value: 7.986318922505234 and parameters: {'C': 4.909212756180434, 'gamma': 2.846621207489622e-05, 'epsilon': 0.00322953185179204}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:49,671] Trial 28 finished with value: 0.16942554224638912 and parameters: {'C': 29.07231641592721, 'gamma': 4.8197123302003955e-06, 'epsilon': 0.0017852822246361443}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:49,697] Trial 29 finished with value: 687.8053072381803 and parameters: {'C': 0.3329405092224314, 'gamma': 0.00013299984255560376, 'epsilon': 0.0037365527376449843}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:49,726] Trial 30 finished with value: 572.183161632595 and parameters: {'C': 2.065486569398953, 'gamma': 3.0965080211725327e-06, 'epsilon': 0.0017762065731167747}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:49,752] Trial 31 finished with value: 0.03741882122497923 and parameters: {'C': 96.10619211411044, 'gamma': 3.02976718833927e-06, 'epsilon': 0.020893338964629814}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:49,783] Trial 32 finished with value: 0.0891577947538978 and parameters: {'C': 47.15965617763488, 'gamma': 3.2102507686315458e-06, 'epsilon': 0.008629011343873668}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:49,813] Trial 33 finished with value: 0.36305955457382794 and parameters: {'C': 22.361470830610145, 'gamma': 9.056307109263578e-06, 'epsilon': 0.3591641510785836}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:49,849] Trial 34 finished with value: 0.1676011506585783 and parameters: {'C': 45.79824352100234, 'gamma': 2.6051086347665504e-05, 'epsilon': 0.004395466639966274}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:49,872] Trial 35 finished with value: 784.7446701880086 and parameters: {'C': 68.694583557621, 'gamma': 0.010301406780603808, 'epsilon': 0.0010067974618296765}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:49,898] Trial 36 finished with value: 2.71505571012132 and parameters: {'C': 15.032610301555735, 'gamma': 2.4550690818408525e-06, 'epsilon': 0.001777654532631938}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:49,923] Trial 37 finished with value: 1.2145891077652804 and parameters: {'C': 35.66510134434856, 'gamma': 8.183215637166299e-05, 'epsilon': 0.0070445296180980084}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:49,948] Trial 38 finished with value: 70.5045554731602 and parameters: {'C': 96.7784868854277, 'gamma': 0.0007971895578786979, 'epsilon': 0.012752793955830866}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:49,967] Trial 39 finished with value: 923.0753882438614 and parameters: {'C': 0.0536803447617564, 'gamma': 0.0025432923799252956, 'epsilon': 0.02106426205914594}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:49,990] Trial 40 finished with value: 602.351442232213 and parameters: {'C': 0.36464262967573363, 'gamma': 4.086860030739056e-05, 'epsilon': 0.003916488839970008}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:50,017] Trial 41 finished with value: 0.06811855419540017 and parameters: {'C': 57.768471156117194, 'gamma': 3.0131385814852458e-06, 'epsilon': 0.009917662753632758}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:50,046] Trial 42 finished with value: 0.04791297954699451 and parameters: {'C': 59.177622116731484, 'gamma': 7.0443286464500815e-06, 'epsilon': 0.0052252867229444205}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:50,082] Trial 43 finished with value: 0.481634318769803 and parameters: {'C': 18.826974690818762, 'gamma': 5.967110521746655e-06, 'epsilon': 0.012295173020414883}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:50,101] Trial 44 finished with value: 0.06193045240771401 and parameters: {'C': 69.5354344531311, 'gamma': 2.4685319333818597e-06, 'epsilon': 0.018905800874161806}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:50,123] Trial 45 finished with value: 0.06656062349623722 and parameters: {'C': 66.33568873785154, 'gamma': 1.0562995971265267e-05, 'epsilon': 0.07686424635916894}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:50,144] Trial 46 finished with value: 0.22623717866600696 and parameters: {'C': 39.09039093848877, 'gamma': 2.0624868462660108e-06, 'epsilon': 0.021349768881226253}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:50,165] Trial 47 finished with value: 0.05194248583620644 and parameters: {'C': 99.27935926496744, 'gamma': 1.783651331833492e-06, 'epsilon': 0.005205374536476108}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:50,188] Trial 48 finished with value: 1.7867514272052667 and parameters: {'C': 10.1186048529859, 'gamma': 6.1112200147384975e-06, 'epsilon': 0.005034799077384554}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:50,208] Trial 49 finished with value: 5.0338732790446254 and parameters: {'C': 6.304473818622923, 'gamma': 2.331127092450728e-05, 'epsilon': 0.0027849736651691962}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:50,231] Trial 50 finished with value: 890.9575636191579 and parameters: {'C': 91.00105445549455, 'gamma': 0.06821762062831291, 'epsilon': 0.005765600236114435}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:50,252] Trial 51 finished with value: 0.08813629324946468 and parameters: {'C': 64.3565194828437, 'gamma': 1.9611506690877446e-06, 'epsilon': 0.02785807973995621}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:50,273] Trial 52 finished with value: 0.051020973994675776 and parameters: {'C': 99.32290293885747, 'gamma': 1.8334950292156067e-06, 'epsilon': 0.01595301133227343}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:50,298] Trial 53 finished with value: 0.2900609560665378 and parameters: {'C': 39.942044157769274, 'gamma': 1.6531970785723415e-06, 'epsilon': 0.046228071925819854}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:50,321] Trial 54 finished with value: 0.052618451477892125 and parameters: {'C': 87.87919275456741, 'gamma': 1.115693909466464e-05, 'epsilon': 0.01548883984094306}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:50,349] Trial 55 finished with value: 0.03453800781492619 and parameters: {'C': 99.80368795298833, 'gamma': 4.7545236072804905e-06, 'epsilon': 0.006654634798020067}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:50,369] Trial 56 finished with value: 0.32171531951876603 and parameters: {'C': 23.90845646140923, 'gamma': 4.383692114712592e-06, 'epsilon': 0.010002915574930216}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:50,396] Trial 57 finished with value: 27.89517168045767 and parameters: {'C': 48.52087568298724, 'gamma': 0.0004573809641786158, 'epsilon': 0.007692215638274563}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:50,424] Trial 58 finished with value: 0.5156416615163149 and parameters: {'C': 34.43199746740842, 'gamma': 4.970508597809755e-05, 'epsilon': 0.001471458544382295}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:50,445] Trial 59 finished with value: 891.7774384608387 and parameters: {'C': 65.11729408161256, 'gamma': 0.34742598962350657, 'epsilon': 0.02663462841752071}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:50,466] Trial 60 finished with value: 0.567909783327455 and parameters: {'C': 16.916606026168928, 'gamma': 7.460030426272091e-06, 'epsilon': 0.015927794297034514}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:50,488] Trial 61 finished with value: 0.06766844292978552 and parameters: {'C': 98.84220835982663, 'gamma': 1.4251641038816667e-06, 'epsilon': 0.005322319893676294}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:50,526] Trial 62 finished with value: 0.17525094691496207 and parameters: {'C': 73.64358680585615, 'gamma': 1.0021830283566188e-06, 'epsilon': 0.0031144416294908053}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:50,581] Trial 63 finished with value: 0.07839211587669545 and parameters: {'C': 99.82221039131345, 'gamma': 1.6394688274391754e-05, 'epsilon': 0.006310090583383965}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:50,614] Trial 64 finished with value: 0.0627709535700987 and parameters: {'C': 51.905732992091615, 'gamma': 4.076178078051121e-06, 'epsilon': 0.004440382550717764}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:50,637] Trial 65 finished with value: 0.5723219789449211 and parameters: {'C': 29.566306927189927, 'gamma': 1.7342154516601835e-06, 'epsilon': 0.011053186034747694}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:50,660] Trial 66 finished with value: 436.9521782064304 and parameters: {'C': 1.7250301827560524, 'gamma': 5.893215584062217e-06, 'epsilon': 0.0033652755739732665}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:50,683] Trial 67 finished with value: 0.07824105263429247 and parameters: {'C': 44.61256820473751, 'gamma': 1.103130614348362e-05, 'epsilon': 0.052087176819444615}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:50,711] Trial 68 finished with value: 0.045205580777135546 and parameters: {'C': 73.46482663384211, 'gamma': 3.211134116016691e-06, 'epsilon': 0.0018885279838585973}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:50,733] Trial 69 finished with value: 0.054657864885034525 and parameters: {'C': 53.74805488434186, 'gamma': 4.619014310394144e-06, 'epsilon': 0.002204114146087283}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:50,758] Trial 70 finished with value: 0.04862191269631046 and parameters: {'C': 71.70934810712299, 'gamma': 3.0470732059002026e-06, 'epsilon': 0.0012948576929618387}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:50,784] Trial 71 finished with value: 0.050298957697227684 and parameters: {'C': 72.65490314945194, 'gamma': 2.8552341739316744e-06, 'epsilon': 0.001283567021915849}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:50,812] Trial 72 finished with value: 0.04667831329617554 and parameters: {'C': 73.40814277955202, 'gamma': 3.0980222950751893e-06, 'epsilon': 0.0014775242462495238}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:50,836] Trial 73 finished with value: 0.23133976325453937 and parameters: {'C': 22.75610175556148, 'gamma': 1.630281250134791e-05, 'epsilon': 0.001604693987329943}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:50,861] Trial 74 finished with value: 0.076004536493412 and parameters: {'C': 39.581113110965404, 'gamma': 7.585469013520084e-06, 'epsilon': 0.0021545083336491897}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:50,887] Trial 75 finished with value: 0.04164333053701272 and parameters: {'C': 74.5750366164059, 'gamma': 3.599843885977611e-06, 'epsilon': 0.0012024765089693574}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:50,915] Trial 76 finished with value: 0.05830089212254983 and parameters: {'C': 54.41274154449124, 'gamma': 4.067529172170045e-06, 'epsilon': 0.0026503133239285533}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:50,934] Trial 77 finished with value: 906.6241385741141 and parameters: {'C': 0.02023124720015473, 'gamma': 3.278705344885276e-05, 'epsilon': 0.0018433198123403247}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:50,955] Trial 78 finished with value: 1.1254332390123665 and parameters: {'C': 12.133806417805422, 'gamma': 8.45645363834207e-06, 'epsilon': 0.0011040703022456065}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:50,981] Trial 79 finished with value: 0.19199650765627915 and parameters: {'C': 29.075433541109106, 'gamma': 2.1727728832481e-05, 'epsilon': 0.0014593681612092096}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:51,009] Trial 80 finished with value: 1.0115682296505077 and parameters: {'C': 76.77880103636896, 'gamma': 7.503591750811758e-05, 'epsilon': 0.0019500407262515761}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:51,044] Trial 81 finished with value: 0.04210401536600537 and parameters: {'C': 75.80838637737664, 'gamma': 3.4289239281349233e-06, 'epsilon': 0.001260162045017528}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:51,065] Trial 82 finished with value: 0.22759498989439866 and parameters: {'C': 54.9437067701393, 'gamma': 1.234628425700766e-06, 'epsilon': 0.002430855599118141}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:51,093] Trial 83 finished with value: 805.3963944554099 and parameters: {'C': 39.23406493682356, 'gamma': 0.01119051783449548, 'epsilon': 0.0011646664165983007}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:51,117] Trial 84 finished with value: 0.06363831153266035 and parameters: {'C': 70.73702769078355, 'gamma': 2.3499004951453406e-06, 'epsilon': 0.0015909197742094616}. Best is trial 26 with value: 0.034510470727262724.

[I 2025-08-19 19:40:51,513] A new study created in memory with name: no-name-382193ad-a62c-449e-803e-04ee31052f6d

[I 2025-08-19 19:40:51,463] Trial 97 finished with value: 0.05137278568587035 and parameters: {'C': 59.45154483998779, 'gamma': 3.966122845165508e-06, 'epsilon': 0.0023469647499259286}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:51,487] Trial 98 finished with value: 148.7424389663201 and parameters: {'C': 83.10375559223881, 'gamma': 0.0013564637930941737, 'epsilon': 0.0016696160297768848}. Best is trial 26 with value: 0.034510470727262724.
[I 2025-08-19 19:40:51,510] Trial 99 finished with value: 0.16340889698334715 and parameters: {'C': 25.67647075483184, 'gamma': 8.678659548014931e-06, 'epsilon': 0.0011980094219699647}. Best is trial 26 with value: 0.034510470727262724.
    Best SVR MSE: 0.034510
  Optimizing Neural Network...

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2025-08-19 19:40:52,956] Trial 0 finished with value: 8.900655583670076 and parameters: {'n_layers': 2, 'hidden_size_0': 155, 'hidden_size_1': 192, 'alpha': 7.167398116227066e-05, 'learning_rate_init': 0.016311046738317646}. Best is trial 0 with value: 8.900655583670076.
[I 2025-08-19 19:40:53,250] Trial 1 finished with value: 7.932864320554709 and parameters: {'n_layers': 1, 'hidden_size_0': 107, 'alpha': 1.4469073799463473e-05, 'learning_rate_init': 0.03479369431596534}. Best is trial 1 with value: 7.932864320554709.
[I 2025-08-19 19:40:53,939] Trial 2 finished with value: 5.646411574837586 and parameters: {'n_layers': 3, 'hidden_size_0': 102, 'hidden_size_1': 49, 'hidden_size_2': 12, 'alpha': 2.239817654479077e-06, 'learning_rate_init': 0.0005522897166504359}. Best is trial 2 with value: 5.646411574837586.
[I 2025-08-19 19:40:54,811] Trial 3 finished with value: 5.286217633146743 and parameters: {'n_layers': 2, 'hidden_size_0': 127, 'hidden_size_1': 149, 'alpha': 0.00013286000153927766, 'learning_rate_init': 0.004013361252949541}. Best is trial 3 with value: 5.286217633146743.
[I 2025-08-19 19:40:56,316] Trial 4 finished with value: 6.074806736478941 and parameters: {'n_layers': 3, 'hidden_size_0': 164, 'hidden_size_1': 71, 'hidden_size_2': 18, 'alpha': 2.4028914251212117e-06, 'learning_rate_init': 0.0006508397211868865}. Best is trial 3 with value: 5.286217633146743.
[I 2025-08-19 19:40:57,151] Trial 5 finished with value: 43.220041345221645 and parameters: {'n_layers': 3, 'hidden_size_0': 12, 'hidden_size_1': 171, 'hidden_size_2': 92, 'alpha': 3.31245933388589e-05, 'learning_rate_init': 0.0475469046012784}. Best is trial 3 with value: 5.286217633146743.
[I 2025-08-19 19:40:57,697] Trial 6 finished with value: 12.590728939582402 and parameters: {'n_layers': 3, 'hidden_size_0': 149, 'hidden_size_1': 93, 'hidden_size_2': 62, 'alpha': 0.0008307038575919792, 'learning_rate_init': 0.0006247417454051523}. Best is trial 3 with value: 5.286217633146743.
[I 2025-08-19 19:40:59,270] Trial 7 finished with value: 195.62349350391577 and parameters: {'n_layers': 1, 'hidden_size_0': 42, 'alpha': 2.003017770189989e-05, 'learning_rate_init': 0.00010288226798899776}. Best is trial 3 with value: 5.286217633146743.
[I 2025-08-19 19:40:59,626] Trial 8 finished with value: 15.446748820116948 and parameters: {'n_layers': 2, 'hidden_size_0': 47, 'hidden_size_1': 133, 'alpha': 5.0121585016886075e-06, 'learning_rate_init': 0.029839538215823313}. Best is trial 3 with value: 5.286217633146743.
[I 2025-08-19 19:40:59,785] Trial 9 finished with value: 20.879124306928 and parameters: {'n_layers': 2, 'hidden_size_0': 14, 'hidden_size_1': 133, 'alpha': 1.82655565832615e-06, 'learning_rate_init': 0.024608957414494176}. Best is trial 3 with value: 5.286217633146743.
[I 2025-08-19 19:41:00,370] Trial 10 finished with value: 7.180443836459143 and parameters: {'n_layers': 2, 'hidden_size_0': 190, 'hidden_size_1': 12, 'alpha': 0.0065217668437104175, 'learning_rate_init': 0.004612781098181828}. Best is trial 3 with value: 5.286217633146743.
[I 2025-08-19 19:41:00,885] Trial 11 finished with value: 9.39716250128679 and parameters: {'n_layers': 3, 'hidden_size_0': 104, 'hidden_size_1': 44, 'hidden_size_2': 197, 'alpha': 0.00035462626153403795, 'learning_rate_init': 0.0018633839150324573}. Best is trial 3 with value: 5.286217633146743.
[I 2025-08-19 19:41:01,009] Trial 12 finished with value: 47.13265535693699 and parameters: {'n_layers': 1, 'hidden_size_0': 107, 'alpha': 0.00030700764204304415, 'learning_rate_init': 0.0043436727685164465}. Best is trial 3 with value: 5.286217633146743.
[I 2025-08-19 19:41:03,720] Trial 13 finished with value: 5.547465347019205 and parameters: {'n_layers': 2, 'hidden_size_0': 82, 'hidden_size_1': 144, 'alpha': 0.004057147180852034, 'learning_rate_init': 0.00022853674518783846}. Best is trial 3 with value: 5.286217633146743.
[I 2025-08-19 19:41:07,881] Trial 14 finished with value: 5.893695350157462 and parameters: {'n_layers': 2, 'hidden_size_0': 74, 'hidden_size_1': 143, 'alpha': 0.009196665617482131, 'learning_rate_init': 0.00012112794101928454}. Best is trial 3 with value: 5.286217633146743.
[I 2025-08-19 19:41:08,401] Trial 15 finished with value: 8.25359765395107 and parameters: {'n_layers': 2, 'hidden_size_0': 130, 'hidden_size_1': 161, 'alpha': 0.0020528481704307263, 'learning_rate_init': 0.010757464049212982}. Best is trial 3 with value: 5.286217633146743.
[I 2025-08-19 19:41:08,679] Trial 16 finished with value: 34.20700299683824 and parameters: {'n_layers': 2, 'hidden_size_0': 78, 'hidden_size_1': 119, 'alpha': 0.0015914422920456869, 'learning_rate_init': 0.0017658361600897622}. Best is trial 3 with value: 5.286217633146743.
[I 2025-08-19 19:41:09,149] Trial 17 finished with value: 18.73766920496172 and parameters: {'n_layers': 1, 'hidden_size_0': 130, 'alpha': 0.00024019822404736563, 'learning_rate_init': 0.0870776120200264}. Best is trial 3 with value: 5.286217633146743.
[I 2025-08-19 19:41:10,273] Trial 18 finished with value: 18.57433889115225 and parameters: {'n_layers': 1, 'hidden_size_0': 75, 'alpha': 9.104226699768561e-05, 'learning_rate_init': 0.00028149774536224325}. Best is trial 3 with value: 5.286217633146743.
[I 2025-08-19 19:41:11,380] Trial 19 finished with value: 5.24292319749807 and parameters: {'n_layers': 2, 'hidden_size_0': 188, 'hidden_size_1': 194, 'alpha': 0.004679732842641749, 'learning_rate_init': 0.009227674815288531}. Best is trial 19 with value: 5.24292319749807.
[I 2025-08-19 19:41:12,705] Trial 20 finished with value: 9.955834539598705 and parameters: {'n_layers': 2, 'hidden_size_0': 174, 'hidden_size_1': 196, 'alpha': 0.0006097028207890378, 'learning_rate_init': 0.008010665083155098}. Best is trial 19 with value: 5.24292319749807.
[I 2025-08-19 19:41:14,060] Trial 21 finished with value: 3.8195095506048857 and parameters: {'n_layers': 2, 'hidden_size_0': 197, 'hidden_size_1': 162, 'alpha': 0.0037872113346983, 'learning_rate_init': 0.002157923490166353}. Best is trial 21 with value: 3.8195095506048857.
[I 2025-08-19 19:41:15,433] Trial 22 finished with value: 2.9972399521363564 and parameters: {'n_layers': 2, 'hidden_size_0': 197, 'hidden_size_1': 171, 'alpha': 0.002147788672237256, 'learning_rate_init': 0.0026468085264569545}. Best is trial 22 with value: 2.9972399521363564.
[I 2025-08-19 19:41:15,841] Trial 23 finished with value: 20.305729430786286 and parameters: {'n_layers': 2, 'hidden_size_0': 200, 'hidden_size_1': 175, 'alpha': 0.002740725344282795, 'learning_rate_init': 0.0016464278133931994}. Best is trial 22 with value: 2.9972399521363564.
[I 2025-08-19 19:41:16,458] Trial 24 finished with value: 8.858446627535718 and parameters: {'n_layers': 2, 'hidden_size_0': 183, 'hidden_size_1': 181, 'alpha': 0.0015122893546349703, 'learning_rate_init': 0.008487646796508088}. Best is trial 22 with value: 2.9972399521363564.
[I 2025-08-19 19:41:17,589] Trial 25 finished with value: 4.801632032416023 and parameters: {'n_layers': 2, 'hidden_size_0': 196, 'hidden_size_1': 197, 'alpha': 0.004977343867288044, 'learning_rate_init': 0.002408498012734956}. Best is trial 22 with value: 2.9972399521363564.
[I 2025-08-19 19:41:19,932] Trial 26 finished with value: 3.9855516746078066 and parameters: {'n_layers': 3, 'hidden_size_0': 198, 'hidden_size_1': 162, 'hidden_size_2': 183, 'alpha': 0.009890655198805946, 'learning_rate_init': 0.0010218267030143893}. Best is trial 22 with value: 2.9972399521363564.
[I 2025-08-19 19:41:20,545] Trial 27 finished with value: 16.128402167739928 and parameters: {'n_layers': 3, 'hidden_size_0': 168, 'hidden_size_1': 113, 'hidden_size_2': 194, 'alpha': 0.009700997955092059, 'learning_rate_init': 0.0012825005278145655}. Best is trial 22 with value: 2.9972399521363564.
[I 2025-08-19 19:41:21,146] Trial 28 finished with value: 17.56017152248907 and parameters: {'n_layers': 3, 'hidden_size_0': 149, 'hidden_size_1': 161, 'hidden_size_2': 145, 'alpha': 0.0009469422952432165, 'learning_rate_init': 0.0008856024026450131}. Best is trial 22 with value: 2.9972399521363564.
[I 2025-08-19 19:41:22,594] Trial 29 finished with value: 4.488628240314786 and parameters: {'n_layers': 3, 'hidden_size_0': 177, 'hidden_size_1': 94, 'hidden_size_2': 142, 'alpha': 0.00294233998393553, 'learning_rate_init': 0.001009703983213329}. Best is trial 22 with value: 2.9972399521363564.
[I 2025-08-19 19:41:25,327] Trial 30 finished with value: 5.971201770558791 and parameters: {'n_layers': 3, 'hidden_size_0': 159, 'hidden_size_1': 159, 'hidden_size_2': 152, 'alpha': 0.0005306489674795874, 'learning_rate_init': 0.0003486109874161647}. Best is trial 22 with value: 2.9972399521363564.
[I 2025-08-19 19:41:26,835] Trial 31 finished with value: 4.426974347014195 and parameters: {'n_layers': 3, 'hidden_size_0': 177, 'hidden_size_1': 97, 'hidden_size_2': 148, 'alpha': 0.002885040453881717, 'learning_rate_init': 0.0009880753384741176}. Best is trial 22 with value: 2.9972399521363564.
[I 2025-08-19 19:41:28,553] Trial 32 finished with value: 3.3424738102306977 and parameters: {'n_layers': 3, 'hidden_size_0': 198, 'hidden_size_1': 93, 'hidden_size_2': 166, 'alpha': 0.0019299846607383321, 'learning_rate_init': 0.0032936540539423888}. Best is trial 22 with value: 2.9972399521363564.
[I 2025-08-19 19:41:30,565] Trial 33 finished with value: 4.276851977241168 and parameters: {'n_layers': 3, 'hidden_size_0': 200, 'hidden_size_1': 69, 'hidden_size_2': 175, 'alpha': 0.0013259880060388753, 'learning_rate_init': 0.0027888574272625665}. Best is trial 22 with value: 2.9972399521363564.
[I 2025-08-19 19:41:32,396] Trial 34 finished with value: 4.597908027617587 and parameters: {'n_layers': 2, 'hidden_size_0': 184, 'hidden_size_1': 125, 'alpha': 0.007888034474882902, 'learning_rate_init': 0.004870475457827639}. Best is trial 22 with value: 2.9972399521363564.
[I 2025-08-19 19:41:35,394] Trial 35 finished with value: 3.5248429750971466 and parameters: {'n_layers': 3, 'hidden_size_0': 146, 'hidden_size_1': 183, 'hidden_size_2': 113, 'alpha': 0.003922952451735235, 'learning_rate_init': 0.002477057409409719}. Best is trial 22 with value: 2.9972399521363564.
[I 2025-08-19 19:41:38,416] Trial 36 finished with value: 3.7009179764802895 and parameters: {'n_layers': 3, 'hidden_size_0': 145, 'hidden_size_1': 182, 'hidden_size_2': 99, 'alpha': 0.00016854734479981214, 'learning_rate_init': 0.0030568116022216436}. Best is trial 22 with value: 2.9972399521363564.
[I 2025-08-19 19:41:41,283] Trial 37 finished with value: 5.727225429559973 and parameters: {'n_layers': 3, 'hidden_size_0': 119, 'hidden_size_1': 183, 'hidden_size_2': 101, 'alpha': 0.000178863998628685, 'learning_rate_init': 0.015035252630753376}. Best is trial 22 with value: 2.9972399521363564.
[I 2025-08-19 19:41:44,038] Trial 38 finished with value: 5.312114001536164 and parameters: {'n_layers': 3, 'hidden_size_0': 139, 'hidden_size_1': 187, 'hidden_size_2': 67, 'alpha': 2.9943899372809392e-05, 'learning_rate_init': 0.006322197826402302}. Best is trial 22 with value: 2.9972399521363564.
[I 2025-08-19 19:41:45,463] Trial 39 finished with value: 4.9822526980874615 and parameters: {'n_layers': 3, 'hidden_size_0': 150, 'hidden_size_1': 79, 'hidden_size_2': 126, 'alpha': 4.208698112007574e-05, 'learning_rate_init': 0.0032689838667928645}. Best is trial 22 with value: 2.9972399521363564.
[I 2025-08-19 19:41:46,862] Trial 40 finished with value: 4.438241513816355 and parameters: {'n_layers': 3, 'hidden_size_0': 162, 'hidden_size_1': 49, 'hidden_size_2': 118, 'alpha': 8.769540964305886e-06, 'learning_rate_init': 0.0165351959792355}. Best is trial 22 with value: 2.9972399521363564.
[I 2025-08-19 19:41:49,346] Trial 41 finished with value: 5.082656110746815 and parameters: {'n_layers': 3, 'hidden_size_0': 170, 'hidden_size_1': 172, 'hidden_size_2': 78, 'alpha': 0.0007119415677588263, 'learning_rate_init': 0.002234824719861182}. Best is trial 22 with value: 2.9972399521363564.
[I 2025-08-19 19:41:51,457] Trial 42 finished with value: 10.30486294355191 and parameters: {'n_layers': 2, 'hidden_size_0': 139, 'hidden_size_1': 153, 'alpha': 0.00108941172673032, 'learning_rate_init': 0.002980122912203416}. Best is trial 22 with value: 2.9972399521363564.
[I 2025-08-19 19:41:54,458] Trial 43 finished with value: 4.802256064987985 and parameters: {'n_layers': 3, 'hidden_size_0': 186, 'hidden_size_1': 171, 'hidden_size_2': 50, 'alpha': 6.229131410754154e-05, 'learning_rate_init': 0.005814599310396993}. Best is trial 22 with value: 2.9972399521363564.
[I 2025-08-19 19:41:56,187] Trial 44 finished with value: 7.7212201686678865 and parameters: {'n_layers': 2, 'hidden_size_0': 112, 'hidden_size_1': 180, 'alpha': 0.0022878864391491062, 'learning_rate_init': 0.0032141339010572263}. Best is trial 22 with value: 2.9972399521363564.
[I 2025-08-19 19:41:58,106] Trial 45 finished with value: 4.483871516781205 and parameters: {'n_layers': 3, 'hidden_size_0': 156, 'hidden_size_1': 109, 'hidden_size_2': 116, 'alpha': 0.00045484134795275666, 'learning_rate_init': 0.001483408409928585}. Best is trial 22 with value: 2.9972399521363564.
[I 2025-08-19 19:42:00,168] Trial 46 finished with value: 4.024922315696428 and parameters: {'n_layers': 2, 'hidden_size_0': 140, 'hidden_size_1': 136, 'alpha': 0.005026638349850595, 'learning_rate_init': 0.000555662898695702}. Best is trial 22 with value: 2.9972399521363564.
[I 2025-08-19 19:42:00,857] Trial 47 finished with value: 9.960347118988565 and parameters: {'n_layers': 1, 'hidden_size_0': 190, 'alpha': 3.52799420081415e-06, 'learning_rate_init': 0.0020844180921850745}. Best is trial 22 with value: 2.9972399521363564.
[I 2025-08-19 19:42:03,581] Trial 48 finished with value: 6.9431540194789125 and parameters: {'n_layers': 3, 'hidden_size_0': 92, 'hidden_size_1': 200, 'hidden_size_2': 86, 'alpha': 1.28604894090195e-06, 'learning_rate_init': 0.003870463166033577}. Best is trial 22 with value: 2.9972399521363564.
[I 2025-08-19 19:42:04,057] Trial 49 finished with value: 10.830357345750794 and parameters: {'n_layers': 2, 'hidden_size_0': 53, 'hidden_size_1': 80, 'alpha': 0.0020340485436470403, 'learning_rate_init': 0.0061302951705400665}. Best is trial 22 with value: 2.9972399521363564.
[I 2025-08-19 19:42:06,082] Trial 50 finished with value: 5.285825589609136 and parameters: {'n_layers': 2, 'hidden_size_0': 163, 'hidden_size_1': 153, 'alpha': 0.00345806403715321, 'learning_rate_init': 0.0007363545614247392}. Best is trial 22 with value: 2.9972399521363564.
[I 2025-08-19 19:42:10,203] Trial 51 finished with value: 2.8577449092319136 and parameters: {'n_layers': 3, 'hidden_size_0': 194, 'hidden_size_1': 164, 'hidden_size_2': 166, 'alpha': 0.006409641339136481, 'learning_rate_init': 0.0012515478877849517}. Best is trial 51 with value: 2.8577449092319136.
[I 2025-08-19 19:42:13,525] Trial 52 finished with value: 3.5005141069155576 and parameters: {'n_layers': 3, 'hidden_size_0': 192, 'hidden_size_1': 187, 'hidden_size_2': 165, 'alpha': 0.0061722546390296, 'learning_rate_init': 0.0014309534466882292}. Best is trial 51 with value: 2.8577449092319136.
[I 2025-08-19 19:42:16,134] Trial 53 finished with value: 3.8086356808860793 and parameters: {'n_layers': 3, 'hidden_size_0': 182, 'hidden_size_1': 188, 'hidden_size_2': 165, 'alpha': 0.005131687280581598, 'learning_rate_init': 0.0012160732685589316}. Best is trial 51 with value: 2.8577449092319136.
[I 2025-08-19 19:42:20,603] Trial 54 finished with value: 3.6289710435714455 and parameters: {'n_layers': 3, 'hidden_size_0': 193, 'hidden_size_1': 173, 'hidden_size_2': 172, 'alpha': 0.006593154101011753, 'learning_rate_init': 0.0014559862736852225}. Best is trial 51 with value: 2.8577449092319136.
[I 2025-08-19 19:42:25,534] Trial 55 finished with value: 4.278516788230627 and parameters: {'n_layers': 3, 'hidden_size_0': 194, 'hidden_size_1': 169, 'hidden_size_2': 167, 'alpha': 0.0068483597209663735, 'learning_rate_init': 0.00045250042440119425}. Best is trial 51 with value: 2.8577449092319136.
[I 2025-08-19 19:42:28,021] Trial 56 finished with value: 4.48292429925268 and parameters: {'n_layers': 3, 'hidden_size_0': 176, 'hidden_size_1': 142, 'hidden_size_2': 161, 'alpha': 0.005702963908199519, 'learning_rate_init': 0.001285459604111769}. Best is trial 51 with value: 2.8577449092319136.
[I 2025-08-19 19:42:29,160] Trial 57 finished with value: 13.578324237537917 and parameters: {'n_layers': 3, 'hidden_size_0': 192, 'hidden_size_1': 191, 'hidden_size_2': 132, 'alpha': 0.0019387201523530912, 'learning_rate_init': 0.0007313162854938865}. Best is trial 51 with value: 2.8577449092319136.
[I 2025-08-19 19:42:33,300] Trial 58 finished with value: 4.531528078977901 and parameters: {'n_layers': 3, 'hidden_size_0': 168, 'hidden_size_1': 176, 'hidden_size_2': 181, 'alpha': 0.006874980377338072, 'learning_rate_init': 0.004079651662570683}. Best is trial 51 with value: 2.8577449092319136.
[I 2025-08-19 19:42:36,786] Trial 59 finished with value: 5.830931761318382 and parameters: {'n_layers': 3, 'hidden_size_0': 183, 'hidden_size_1': 167, 'hidden_size_2': 158, 'alpha': 0.003917286821507576, 'learning_rate_init': 0.0014696885404001073}. Best is trial 51 with value: 2.8577449092319136.
[I 2025-08-19 19:42:39,706] Trial 60 finished with value: 4.111006592826476 and parameters: {'n_layers': 3, 'hidden_size_0': 191, 'hidden_size_1': 148, 'hidden_size_2': 176, 'alpha': 0.0017093807714867084, 'learning_rate_init': 0.0018265370485950074}. Best is trial 51 with value: 2.8577449092319136.
[I 2025-08-19 19:42:41,561] Trial 61 finished with value: 8.172618357255415 and parameters: {'n_layers': 3, 'hidden_size_0': 95, 'hidden_size_1': 185, 'hidden_size_2': 106, 'alpha': 0.0029165346528764167, 'learning_rate_init': 0.0024839864652035394}. Best is trial 51 with value: 2.8577449092319136.
[I 2025-08-19 19:42:45,049] Trial 62 finished with value: 3.524882230145475 and parameters: {'n_layers': 3, 'hidden_size_0': 121, 'hidden_size_1': 192, 'hidden_size_2': 134, 'alpha': 0.0069003480094177155, 'learning_rate_init': 0.0036018335005536463}. Best is trial 51 with value: 2.8577449092319136.
[I 2025-08-19 19:42:47,635] Trial 63 finished with value: 3.3873257926276117 and parameters: {'n_layers': 3, 'hidden_size_0': 121, 'hidden_size_1': 192, 'hidden_size_2': 134, 'alpha': 0.006222205439781921, 'learning_rate_init': 0.0017945798753325058}. Best is trial 51 with value: 2.8577449092319136.
[I 2025-08-19 19:42:50,310] Trial 64 finished with value: 5.713229677009947 and parameters: {'n_layers': 3, 'hidden_size_0': 125, 'hidden_size_1': 192, 'hidden_size_2': 135, 'alpha': 0.003977951366408517, 'learning_rate_init': 0.005174781177612187}. Best is trial 51 with value: 2.8577449092319136.
[I 2025-08-19 19:42:53,349] Trial 65 finished with value: 4.9049210500821285 and parameters: {'n_layers': 3, 'hidden_size_0': 116, 'hidden_size_1': 200, 'hidden_size_2': 116, 'alpha': 0.009327922542422018, 'learning_rate_init': 0.003942216486183378}. Best is trial 51 with value: 2.8577449092319136.
[I 2025-08-19 19:42:57,014] Trial 66 finished with value: 6.064651098283164 and parameters: {'n_layers': 3, 'hidden_size_0': 126, 'hidden_size_1': 191, 'hidden_size_2': 136, 'alpha': 0.0011266597837706965, 'learning_rate_init': 0.0018598539778740852}. Best is trial 51 with value: 2.8577449092319136.
[I 2025-08-19 19:42:58,410] Trial 67 finished with value: 6.4691385861756086 and parameters: {'n_layers': 3, 'hidden_size_0': 108, 'hidden_size_1': 100, 'hidden_size_2': 156, 'alpha': 0.0024808215632692635, 'learning_rate_init': 0.007030316639132017}. Best is trial 51 with value: 2.8577449092319136.
[I 2025-08-19 19:42:59,753] Trial 68 finished with value: 11.186843392443942 and parameters: {'n_layers': 3, 'hidden_size_0': 65, 'hidden_size_1': 179, 'hidden_size_2': 196, 'alpha': 0.0036304750406395817, 'learning_rate_init': 0.002564691807139008}. Best is trial 51 with value: 2.8577449092319136.

[I 2025-08-19 19:45:02,323] A new study created in memory with name: no-name-cd5b9313-8e35-4549-a969-e3a4908654ba

[I 2025-08-19 19:45:02,318] Trial 99 finished with value: 3.7595975029225874 and parameters: {'n_layers': 2, 'hidden_size_0': 191, 'hidden_size_1': 177, 'alpha': 0.0009603750455411034, 'learning_rate_init': 0.00010914410987179722}. Best is trial 71 with value: 2.8055508006945375.
    Best NN MSE: 2.805551
  Optimizing XGBoost...

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2025-08-19 19:45:02,927] Trial 0 finished with value: 3.449489164352417 and parameters: {'n_estimators': 258, 'max_depth': 9, 'learning_rate': 0.2868097549949875, 'subsample': 0.7855361528214284, 'colsample_bytree': 0.8949975776223627, 'reg_alpha': 0.3320102363966625, 'reg_lambda': 0.5110654892617195}. Best is trial 0 with value: 3.449489164352417.
[I 2025-08-19 19:45:03,480] Trial 1 finished with value: 102.57733573913575 and parameters: {'n_estimators': 180, 'max_depth': 9, 'learning_rate': 0.2796411269270747, 'subsample': 0.7933702148684326, 'colsample_bytree': 0.6820362600374056, 'reg_alpha': 0.015032244738287792, 'reg_lambda': 0.08755316586959205}. Best is trial 0 with value: 3.449489164352417.
[I 2025-08-19 19:45:04,058] Trial 2 finished with value: 22.429674530029295 and parameters: {'n_estimators': 161, 'max_depth': 6, 'learning_rate': 0.1878953431482189, 'subsample': 0.8915671114884505, 'colsample_bytree': 0.8123394253137142, 'reg_alpha': 0.5345027511515238, 'reg_lambda': 0.6695520821461635}. Best is trial 0 with value: 3.449489164352417.
[I 2025-08-19 19:45:05,866] Trial 3 finished with value: 16.409178924560546 and parameters: {'n_estimators': 413, 'max_depth': 5, 'learning_rate': 0.02330492566401024, 'subsample': 0.6380734147609546, 'colsample_bytree': 0.7084632067144855, 'reg_alpha': 0.7008700794530022, 'reg_lambda': 0.010623140491635374}. Best is trial 0 with value: 3.449489164352417.
[I 2025-08-19 19:45:07,512] Trial 4 finished with value: 4.0426837682724 and parameters: {'n_estimators': 432, 'max_depth': 6, 'learning_rate': 0.12021091525697909, 'subsample': 0.9569496331670797, 'colsample_bytree': 0.870226990068316, 'reg_alpha': 0.7312240315039474, 'reg_lambda': 0.435093453351329}. Best is trial 0 with value: 3.449489164352417.
[I 2025-08-19 19:45:08,728] Trial 5 finished with value: 72.15416450500489 and parameters: {'n_estimators': 173, 'max_depth': 8, 'learning_rate': 0.08691771756991429, 'subsample': 0.6088455034591104, 'colsample_bytree': 0.6681143463440867, 'reg_alpha': 0.32542120056118984, 'reg_lambda': 0.0041135098313099805}. Best is trial 0 with value: 3.449489164352417.
[I 2025-08-19 19:45:09,510] Trial 6 finished with value: 2.4910318851470947 and parameters: {'n_estimators': 247, 'max_depth': 4, 'learning_rate': 0.19806639115434782, 'subsample': 0.6700024796424326, 'colsample_bytree': 0.9299722797191209, 'reg_alpha': 0.43794163794797203, 'reg_lambda': 0.02396063029390616}. Best is trial 6 with value: 2.4910318851470947.
[I 2025-08-19 19:45:10,377] Trial 7 finished with value: 18.377904319763182 and parameters: {'n_estimators': 342, 'max_depth': 3, 'learning_rate': 0.24113901075722252, 'subsample': 0.7850682737528474, 'colsample_bytree': 0.8073724882416142, 'reg_alpha': 0.01937463403047257, 'reg_lambda': 0.9363830553724265}. Best is trial 6 with value: 2.4910318851470947.
[I 2025-08-19 19:45:10,991] Trial 8 finished with value: 7.640997076034546 and parameters: {'n_estimators': 78, 'max_depth': 5, 'learning_rate': 0.2929950878885234, 'subsample': 0.8283459221308414, 'colsample_bytree': 0.8479684819767384, 'reg_alpha': 0.342864361117479, 'reg_lambda': 0.475341108248701}. Best is trial 6 with value: 2.4910318851470947.
[I 2025-08-19 19:45:14,151] Trial 9 finished with value: 18.32922191619873 and parameters: {'n_estimators': 472, 'max_depth': 4, 'learning_rate': 0.032558088778383364, 'subsample': 0.8489797501078457, 'colsample_bytree': 0.7548199148748489, 'reg_alpha': 0.5163822278837185, 'reg_lambda': 0.9659068497351706}. Best is trial 6 with value: 2.4910318851470947.
[I 2025-08-19 19:45:14,977] Trial 10 finished with value: 3.0794973134994508 and parameters: {'n_estimators': 335, 'max_depth': 3, 'learning_rate': 0.1872848218450139, 'subsample': 0.6993642643004209, 'colsample_bytree': 0.9981341962753011, 'reg_alpha': 0.9258835810465541, 'reg_lambda': 0.22988284856541494}. Best is trial 6 with value: 2.4910318851470947.
[I 2025-08-19 19:45:15,819] Trial 11 finished with value: 2.831830596923828 and parameters: {'n_estimators': 309, 'max_depth': 3, 'learning_rate': 0.18997222684394377, 'subsample': 0.6929233501126211, 'colsample_bytree': 0.995825475924077, 'reg_alpha': 0.9938772419949407, 'reg_lambda': 0.2335631727203537}. Best is trial 6 with value: 2.4910318851470947.
[I 2025-08-19 19:45:16,651] Trial 12 finished with value: 3.0559170246124268 and parameters: {'n_estimators': 268, 'max_depth': 3, 'learning_rate': 0.2117028768071325, 'subsample': 0.6934676584164411, 'colsample_bytree': 0.9954960824170772, 'reg_alpha': 0.9860228810614967, 'reg_lambda': 0.24292057074100892}. Best is trial 6 with value: 2.4910318851470947.
[I 2025-08-19 19:45:18,173] Trial 13 finished with value: 2.822911810874939 and parameters: {'n_estimators': 342, 'max_depth': 4, 'learning_rate': 0.14708597625501948, 'subsample': 0.6985404795183655, 'colsample_bytree': 0.9421485025788295, 'reg_alpha': 0.7484558547246618, 'reg_lambda': 0.27349321550692984}. Best is trial 6 with value: 2.4910318851470947.
[I 2025-08-19 19:45:20,098] Trial 14 finished with value: 3.267954921722412 and parameters: {'n_estimators': 224, 'max_depth': 7, 'learning_rate': 0.1345296269256247, 'subsample': 0.733412795749345, 'colsample_bytree': 0.9182943904955571, 'reg_alpha': 0.7264408853245905, 'reg_lambda': 0.1641748422189292}. Best is trial 6 with value: 2.4910318851470947.
[I 2025-08-19 19:45:22,511] Trial 15 finished with value: 63.10665168762207 and parameters: {'n_estimators': 378, 'max_depth': 5, 'learning_rate': 0.08464244939530503, 'subsample': 0.654843247709312, 'colsample_bytree': 0.6073046007031884, 'reg_alpha': 0.6347908066418009, 'reg_lambda': 0.33718232280779065}. Best is trial 6 with value: 2.4910318851470947.
[I 2025-08-19 19:45:23,072] Trial 16 finished with value: 2.93844952583313 and parameters: {'n_estimators': 73, 'max_depth': 4, 'learning_rate': 0.22898347402290928, 'subsample': 0.7245717441332069, 'colsample_bytree': 0.9371047186018492, 'reg_alpha': 0.16632691318982473, 'reg_lambda': 0.6527809766476269}. Best is trial 6 with value: 2.4910318851470947.
[I 2025-08-19 19:45:24,181] Trial 17 finished with value: 2.548669719696045 and parameters: {'n_estimators': 227, 'max_depth': 4, 'learning_rate': 0.15928025466951973, 'subsample': 0.7472624489711909, 'colsample_bytree': 0.931726707547835, 'reg_alpha': 0.8231421250647952, 'reg_lambda': 0.33863683939137423}. Best is trial 6 with value: 2.4910318851470947.
[I 2025-08-19 19:45:25,373] Trial 18 finished with value: 4.226221895217895 and parameters: {'n_estimators': 124, 'max_depth': 10, 'learning_rate': 0.10557964899631328, 'subsample': 0.75880537144847, 'colsample_bytree': 0.8580665013569662, 'reg_alpha': 0.8721684054869389, 'reg_lambda': 0.6545469075409602}. Best is trial 6 with value: 2.4910318851470947.
[I 2025-08-19 19:45:26,502] Trial 19 finished with value: 3.27488489151001 and parameters: {'n_estimators': 216, 'max_depth': 7, 'learning_rate': 0.16322054168714456, 'subsample': 0.8875182127074529, 'colsample_bytree': 0.9537233284156168, 'reg_alpha': 0.4088612053451396, 'reg_lambda': 0.3587751968465111}. Best is trial 6 with value: 2.4910318851470947.
[I 2025-08-19 19:45:27,166] Trial 20 finished with value: 15.699400997161865 and parameters: {'n_estimators': 227, 'max_depth': 5, 'learning_rate': 0.25558591593576174, 'subsample': 0.9976484536230416, 'colsample_bytree': 0.7665910275290476, 'reg_alpha': 0.2160957728349574, 'reg_lambda': 0.13849473731548362}. Best is trial 6 with value: 2.4910318851470947.
[I 2025-08-19 19:45:28,232] Trial 21 finished with value: 3.416606140136719 and parameters: {'n_estimators': 307, 'max_depth': 4, 'learning_rate': 0.1523970898794077, 'subsample': 0.6487563254985845, 'colsample_bytree': 0.9531869470018105, 'reg_alpha': 0.8325886327292478, 'reg_lambda': 0.3364590825831738}. Best is trial 6 with value: 2.4910318851470947.
[I 2025-08-19 19:45:29,167] Trial 22 finished with value: 5.029004192352295 and parameters: {'n_estimators': 276, 'max_depth': 4, 'learning_rate': 0.16047079347158952, 'subsample': 0.6002199130135214, 'colsample_bytree': 0.9085842711759772, 'reg_alpha': 0.5772652842361204, 'reg_lambda': 0.5819268543333256}. Best is trial 6 with value: 2.4910318851470947.
[I 2025-08-19 19:45:30,096] Trial 23 finished with value: 2.900452423095703 and parameters: {'n_estimators': 391, 'max_depth': 4, 'learning_rate': 0.20966271694740848, 'subsample': 0.7404285488824995, 'colsample_bytree': 0.9596881472922838, 'reg_alpha': 0.8018020247683433, 'reg_lambda': 0.8388803278553382}. Best is trial 6 with value: 2.4910318851470947.
[I 2025-08-19 19:45:31,450] Trial 24 finished with value: 3.658786487579346 and parameters: {'n_estimators': 361, 'max_depth': 6, 'learning_rate': 0.1401931714897132, 'subsample': 0.6728446716627942, 'colsample_bytree': 0.8867751569716263, 'reg_alpha': 0.6549839608752842, 'reg_lambda': 0.40266840927112424}. Best is trial 6 with value: 2.4910318851470947.
[I 2025-08-19 19:45:33,204] Trial 25 finished with value: 10.767817258834839 and parameters: {'n_estimators': 296, 'max_depth': 5, 'learning_rate': 0.062058970705219915, 'subsample': 0.7587863636009409, 'colsample_bytree': 0.841853620626139, 'reg_alpha': 0.480208020511903, 'reg_lambda': 0.27761016505268005}. Best is trial 6 with value: 2.4910318851470947.
[I 2025-08-19 19:45:34,983] Trial 26 finished with value: 3.861306381225586 and parameters: {'n_estimators': 498, 'max_depth': 4, 'learning_rate': 0.16978271827073435, 'subsample': 0.7133757647153857, 'colsample_bytree': 0.9204550355779071, 'reg_alpha': 0.7910379863684125, 'reg_lambda': 0.07957037078231391}. Best is trial 6 with value: 2.4910318851470947.
[I 2025-08-19 19:45:35,765] Trial 27 finished with value: 2.801666498184204 and parameters: {'n_estimators': 241, 'max_depth': 3, 'learning_rate': 0.12108298493013595, 'subsample': 0.6748811892682826, 'colsample_bytree': 0.965726896112331, 'reg_alpha': 0.5993601988934734, 'reg_lambda': 0.15927809734463486}. Best is trial 6 with value: 2.4910318851470947.
[I 2025-08-19 19:45:36,342] Trial 28 finished with value: 2.4081191778182984 and parameters: {'n_estimators': 115, 'max_depth': 3, 'learning_rate': 0.05378268037822029, 'subsample': 0.670795719200294, 'colsample_bytree': 0.9702829746051818, 'reg_alpha': 0.444931041715044, 'reg_lambda': 0.15656424893917797}. Best is trial 28 with value: 2.4081191778182984.
[I 2025-08-19 19:45:36,948] Trial 29 finished with value: 4.5006420612335205 and parameters: {'n_estimators': 110, 'max_depth': 3, 'learning_rate': 0.08153590615051204, 'subsample': 0.6296556543943342, 'colsample_bytree': 0.8903385118027727, 'reg_alpha': 0.4377849275663126, 'reg_lambda': 0.07751782772214225}. Best is trial 28 with value: 2.4081191778182984.
[I 2025-08-19 19:45:38,540] Trial 30 finished with value: 38.794683837890624 and parameters: {'n_estimators': 143, 'max_depth': 8, 'learning_rate': 0.011723183223308509, 'subsample': 0.7696195793316621, 'colsample_bytree': 0.9747795919220251, 'reg_alpha': 0.2734885303068865, 'reg_lambda': 0.1681793426646703}. Best is trial 28 with value: 2.4081191778182984.
[I 2025-08-19 19:45:39,354] Trial 31 finished with value: 2.5938191413879395 and parameters: {'n_estimators': 189, 'max_depth': 3, 'learning_rate': 0.05567803292722889, 'subsample': 0.6700649789778904, 'colsample_bytree': 0.9718704879908334, 'reg_alpha': 0.5858624954649325, 'reg_lambda': 0.1404780434613973}. Best is trial 28 with value: 2.4081191778182984.
[I 2025-08-19 19:45:40,100] Trial 32 finished with value: 3.0881933689117433 and parameters: {'n_estimators': 198, 'max_depth': 3, 'learning_rate': 0.048512009878613635, 'subsample': 0.6635216069044072, 'colsample_bytree': 0.9276855559675874, 'reg_alpha': 0.4023054834036511, 'reg_lambda': 0.07469427393356626}. Best is trial 28 with value: 2.4081191778182984.
[I 2025-08-19 19:45:40,949] Trial 33 finished with value: 2.423803782463074 and parameters: {'n_estimators': 194, 'max_depth': 3, 'learning_rate': 0.05797142039464404, 'subsample': 0.81548942324481, 'colsample_bytree': 0.9723849262486023, 'reg_alpha': 0.47047504305563564, 'reg_lambda': 0.1171011372919841}. Best is trial 28 with value: 2.4081191778182984.
[I 2025-08-19 19:45:41,411] Trial 34 finished with value: 2.96784987449646 and parameters: {'n_estimators': 155, 'max_depth': 4, 'learning_rate': 0.26515321410473125, 'subsample': 0.8140071344364777, 'colsample_bytree': 0.8855154427269929, 'reg_alpha': 0.49272778659154254, 'reg_lambda': 0.00415089524100162}. Best is trial 28 with value: 2.4081191778182984.
[I 2025-08-19 19:45:42,123] Trial 35 finished with value: 3.6977799415588377 and parameters: {'n_estimators': 117, 'max_depth': 5, 'learning_rate': 0.09876799027243133, 'subsample': 0.8699561921365644, 'colsample_bytree': 0.9122379720104865, 'reg_alpha': 0.3507922574244524, 'reg_lambda': 0.5469468130851078}. Best is trial 28 with value: 2.4081191778182984.
[I 2025-08-19 19:45:43,596] Trial 36 finished with value: 14.502329444885254 and parameters: {'n_estimators': 255, 'max_depth': 6, 'learning_rate': 0.06981390389128417, 'subsample': 0.7972583099829345, 'colsample_bytree': 0.8311011867776573, 'reg_alpha': 0.45947728626388223, 'reg_lambda': 0.09878468368002744}. Best is trial 28 with value: 2.4081191778182984.
[I 2025-08-19 19:45:44,429] Trial 37 finished with value: 3.0233796358108522 and parameters: {'n_estimators': 199, 'max_depth': 3, 'learning_rate': 0.17790355536715213, 'subsample': 0.9295981596901602, 'colsample_bytree': 0.9818119986320818, 'reg_alpha': 0.537898314974543, 'reg_lambda': 0.04228589101851521}. Best is trial 28 with value: 2.4081191778182984.
[I 2025-08-19 19:45:44,996] Trial 38 finished with value: 10.119963932037354 and parameters: {'n_estimators': 59, 'max_depth': 4, 'learning_rate': 0.04318247759247105, 'subsample': 0.6239198686040841, 'colsample_bytree': 0.9390312046935365, 'reg_alpha': 0.2756679174143347, 'reg_lambda': 0.19283402866511695}. Best is trial 28 with value: 2.4081191778182984.
[I 2025-08-19 19:45:45,919] Trial 39 finished with value: 3.0235593795776365 and parameters: {'n_estimators': 173, 'max_depth': 5, 'learning_rate': 0.21007485757956856, 'subsample': 0.8325181861057475, 'colsample_bytree': 0.8682241829413957, 'reg_alpha': 0.14477232970308007, 'reg_lambda': 0.3009976545889324}. Best is trial 28 with value: 2.4081191778182984.
[I 2025-08-19 19:45:47,104] Trial 40 finished with value: 17.609120273590086 and parameters: {'n_estimators': 141, 'max_depth': 6, 'learning_rate': 0.030660574088461803, 'subsample': 0.7871053285006988, 'colsample_bytree': 0.783809562559825, 'reg_alpha': 0.3770203240847315, 'reg_lambda': 0.4282449884885852}. Best is trial 28 with value: 2.4081191778182984.
[I 2025-08-19 19:45:48,390] Trial 41 finished with value: 2.5622119665145875 and parameters: {'n_estimators': 193, 'max_depth': 3, 'learning_rate': 0.050247000682952535, 'subsample': 0.7436497080097482, 'colsample_bytree': 0.9764820090168326, 'reg_alpha': 0.5930211588364288, 'reg_lambda': 0.12272699346112188}. Best is trial 28 with value: 2.4081191778182984.
[I 2025-08-19 19:45:48,924] Trial 42 finished with value: 83.88790893554688 and parameters: {'n_estimators': 98, 'max_depth': 3, 'learning_rate': 0.012683768353332445, 'subsample': 0.7674607320292833, 'colsample_bytree': 0.9798494799744736, 'reg_alpha': 0.667266388537631, 'reg_lambda': 0.11819813501464244}. Best is trial 28 with value: 2.4081191778182984.
[I 2025-08-19 19:45:49,826] Trial 43 finished with value: 2.396112060546875 and parameters: {'n_estimators': 251, 'max_depth': 3, 'learning_rate': 0.06762821466662544, 'subsample': 0.7439460214143427, 'colsample_bytree': 0.9484038904283337, 'reg_alpha': 0.5334074468401178, 'reg_lambda': 0.044960630536021645}. Best is trial 43 with value: 2.396112060546875.
[I 2025-08-19 19:45:50,923] Trial 44 finished with value: 3.3155405044555666 and parameters: {'n_estimators': 250, 'max_depth': 4, 'learning_rate': 0.11787660188036671, 'subsample': 0.8481052606355057, 'colsample_bytree': 0.9027971025573914, 'reg_alpha': 0.5311251967496146, 'reg_lambda': 0.04631409626576305}. Best is trial 43 with value: 2.396112060546875.
[I 2025-08-19 19:45:52,118] Trial 45 finished with value: 2.5889156579971315 and parameters: {'n_estimators': 270, 'max_depth': 3, 'learning_rate': 0.076680776720709, 'subsample': 0.8101562792960546, 'colsample_bytree': 0.9477945793034597, 'reg_alpha': 0.28549792191351353, 'reg_lambda': 0.1942230977179075}. Best is trial 43 with value: 2.396112060546875.
[I 2025-08-19 19:45:52,976] Trial 46 finished with value: 33.028482818603514 and parameters: {'n_estimators': 288, 'max_depth': 4, 'learning_rate': 0.1953585535695972, 'subsample': 0.7140325442795399, 'colsample_bytree': 0.694801020497922, 'reg_alpha': 0.06082557031607605, 'reg_lambda': 0.04419359800851337}. Best is trial 43 with value: 2.396112060546875.
[I 2025-08-19 19:45:53,772] Trial 47 finished with value: 2.4817007064819334 and parameters: {'n_estimators': 217, 'max_depth': 3, 'learning_rate': 0.09747948795278155, 'subsample': 0.6825575215643488, 'colsample_bytree': 0.9961112761072018, 'reg_alpha': 0.45742291240952626, 'reg_lambda': 0.22102936815856078}. Best is trial 43 with value: 2.396112060546875.
[I 2025-08-19 19:45:54,938] Trial 48 finished with value: 2.699746537208557 and parameters: {'n_estimators': 321, 'max_depth': 3, 'learning_rate': 0.09109394092117695, 'subsample': 0.6878573652063523, 'colsample_bytree': 0.9995429022358846, 'reg_alpha': 0.4358689138401991, 'reg_lambda': 0.23011346963469445}. Best is trial 43 with value: 2.396112060546875.
[I 2025-08-19 19:45:55,571] Trial 49 finished with value: 2.6959598541259764 and parameters: {'n_estimators': 169, 'max_depth': 3, 'learning_rate': 0.06739125735203752, 'subsample': 0.6437021608782967, 'colsample_bytree': 0.9999747270693057, 'reg_alpha': 0.32787532379025264, 'reg_lambda': 0.19797365228255487}. Best is trial 43 with value: 2.396112060546875.
[I 2025-08-19 19:45:56,419] Trial 50 finished with value: 2.7685359716415405 and parameters: {'n_estimators': 234, 'max_depth': 3, 'learning_rate': 0.03829391611266973, 'subsample': 0.7136110773449336, 'colsample_bytree': 0.9558834528969209, 'reg_alpha': 0.5390788562523128, 'reg_lambda': 0.0051736043437088375}. Best is trial 43 with value: 2.396112060546875.
[I 2025-08-19 19:45:57,340] Trial 51 finished with value: 2.598139500617981 and parameters: {'n_estimators': 206, 'max_depth': 4, 'learning_rate': 0.12323221958585245, 'subsample': 0.7478691574115963, 'colsample_bytree': 0.9266653060088518, 'reg_alpha': 0.39265139175971453, 'reg_lambda': 0.2555230543474381}. Best is trial 43 with value: 2.396112060546875.
[I 2025-08-19 19:45:58,263] Trial 52 finished with value: 2.586411690711975 and parameters: {'n_estimators': 246, 'max_depth': 3, 'learning_rate': 0.10608092660284694, 'subsample': 0.6855824535295287, 'colsample_bytree': 0.9337789466060865, 'reg_alpha': 0.48968303127725316, 'reg_lambda': 0.3087128460782116}. Best is trial 43 with value: 2.396112060546875.
[I 2025-08-19 19:45:59,061] Trial 53 finished with value: 22.866852378845216 and parameters: {'n_estimators': 219, 'max_depth': 4, 'learning_rate': 0.23145459894740825, 'subsample': 0.7059152548599739, 'colsample_bytree': 0.7241698287560255, 'reg_alpha': 0.9300951342427359, 'reg_lambda': 0.04823059403669612}. Best is trial 43 with value: 2.396112060546875.
[I 2025-08-19 19:46:00,162] Trial 54 finished with value: 2.8006113052368162 and parameters: {'n_estimators': 264, 'max_depth': 3, 'learning_rate': 0.022409378322313538, 'subsample': 0.621370746858299, 'colsample_bytree': 0.9854005211453212, 'reg_alpha': 0.45331534076511837, 'reg_lambda': 0.3820770464214505}. Best is trial 43 with value: 2.396112060546875.

[I 2025-08-19 19:46:42,238] A new study created in memory with name: no-name-e02d8b70-5b2c-4f01-82d3-c104e87a790e

[I 2025-08-19 19:46:42,234] Trial 99 finished with value: 2.6559906005859375 and parameters: {'n_estimators': 93, 'max_depth': 4, 'learning_rate': 0.125928946149551, 'subsample': 0.8363421534808418, 'colsample_bytree': 0.9685050937581581, 'reg_alpha': 0.30526304314169384, 'reg_lambda': 0.0026216430872717245}. Best is trial 90 with value: 2.3400060415267943.
    Best XGBoost MSE: 2.340006

Optimizing for dataset: Si_TM
  Optimizing SVR...

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2025-08-19 19:46:42,280] Trial 0 finished with value: 920.0147927554865 and parameters: {'C': 0.7080166777372641, 'gamma': 0.03664288488964582, 'epsilon': 0.7303805334596838}. Best is trial 0 with value: 920.0147927554865.
[I 2025-08-19 19:46:42,306] Trial 1 finished with value: 918.3825678962836 and parameters: {'C': 0.716739811622706, 'gamma': 0.026605024569958235, 'epsilon': 0.009909020096150061}. Best is trial 1 with value: 918.3825678962836.
[I 2025-08-19 19:46:42,330] Trial 2 finished with value: 181.49422297966368 and parameters: {'C': 1.1072914768800126, 'gamma': 5.503780404533425e-05, 'epsilon': 0.3479369431596531}. Best is trial 2 with value: 181.49422297966368.
[I 2025-08-19 19:46:42,400] Trial 3 finished with value: 32.26421154019192 and parameters: {'C': 52.38270938257665, 'gamma': 0.0007953407290028804, 'epsilon': 0.0041235565070253995}. Best is trial 3 with value: 32.26421154019192.
[I 2025-08-19 19:46:42,434] Trial 4 finished with value: 923.1650401481568 and parameters: {'C': 0.011484946565558417, 'gamma': 3.3521156622013896e-06, 'epsilon': 0.005522897166504355}. Best is trial 3 with value: 32.26421154019192.
[I 2025-08-19 19:46:42,485] Trial 5 finished with value: 888.3589769692326 and parameters: {'C': 0.8238571129572483, 'gamma': 0.004792844142778419, 'epsilon': 0.15372812711578807}. Best is trial 3 with value: 32.26421154019192.
[I 2025-08-19 19:46:42,525] Trial 6 finished with value: 799.1635056537347 and parameters: {'C': 1.3286000153927777, 'gamma': 0.0016107068546676673, 'epsilon': 0.10201317075512983}. Best is trial 3 with value: 32.26421154019192.
[I 2025-08-19 19:46:42,565] Trial 7 finished with value: 1.629586009911004 and parameters: {'C': 16.855013503209154, 'gamma': 8.28218838461416e-05, 'epsilon': 0.0013728944900654164}. Best is trial 7 with value: 1.629586009911004.
[I 2025-08-19 19:46:42,600] Trial 8 finished with value: 900.5853414790596 and parameters: {'C': 0.024028914251212098, 'gamma': 4.2359234267462355e-05, 'epsilon': 0.12665147101972324}. Best is trial 7 with value: 1.629586009911004.
[I 2025-08-19 19:46:42,635] Trial 9 finished with value: 925.6362918753784 and parameters: {'C': 0.011027893465400396, 'gamma': 0.12079654162943208, 'epsilon': 0.019428094060121262}. Best is trial 7 with value: 1.629586009911004.
[I 2025-08-19 19:46:42,710] Trial 10 finished with value: 0.08531180480789917 and parameters: {'C': 51.70222977150333, 'gamma': 3.3292485699658947e-06, 'epsilon': 0.0010253718120924727}. Best is trial 10 with value: 0.08531180480789917.
[I 2025-08-19 19:46:42,773] Trial 11 finished with value: 0.09477882408191587 and parameters: {'C': 85.42348757968868, 'gamma': 1.1154406725445421e-06, 'epsilon': 0.0012795966681601113}. Best is trial 10 with value: 0.08531180480789917.
[I 2025-08-19 19:46:42,841] Trial 12 finished with value: 0.10218922647981617 and parameters: {'C': 48.46159798985091, 'gamma': 1.7476210261657477e-06, 'epsilon': 0.0012143194777005564}. Best is trial 10 with value: 0.08531180480789917.
[I 2025-08-19 19:46:42,910] Trial 13 finished with value: 2.2018883930073168 and parameters: {'C': 8.372649683289024, 'gamma': 8.770101098559268e-06, 'epsilon': 0.0026978741259317237}. Best is trial 10 with value: 0.08531180480789917.
[I 2025-08-19 19:46:42,973] Trial 14 finished with value: 0.0994312545239413 and parameters: {'C': 94.51679095184821, 'gamma': 1.0011144508177092e-06, 'epsilon': 0.03077770181525936}. Best is trial 10 with value: 0.08531180480789917.
[I 2025-08-19 19:46:43,031] Trial 15 finished with value: 919.8457942791413 and parameters: {'C': 5.447806224186973, 'gamma': 0.8460123301163074, 'epsilon': 0.0011497469005813871}. Best is trial 10 with value: 0.08531180480789917.
[I 2025-08-19 19:46:43,087] Trial 16 finished with value: 850.7397164070474 and parameters: {'C': 0.12070658333998723, 'gamma': 1.2887929196439626e-05, 'epsilon': 0.009785418062255599}. Best is trial 10 with value: 0.08531180480789917.
[I 2025-08-19 19:46:43,118] Trial 17 finished with value: 11.056210829879701 and parameters: {'C': 18.107629411127313, 'gamma': 0.0003089971118777482, 'epsilon': 0.0024358730538914294}. Best is trial 10 with value: 0.08531180480789917.
[I 2025-08-19 19:46:43,152] Trial 18 finished with value: 12.005253967283435 and parameters: {'C': 4.782787580041108, 'gamma': 7.112615784478215e-06, 'epsilon': 0.007004983162259309}. Best is trial 10 with value: 0.08531180480789917.
[I 2025-08-19 19:46:43,190] Trial 19 finished with value: 0.1201576184404847 and parameters: {'C': 27.98074681412481, 'gamma': 2.206845153450076e-05, 'epsilon': 0.002576914585412159}. Best is trial 10 with value: 0.08531180480789917.
[I 2025-08-19 19:46:43,228] Trial 20 finished with value: 2.7868602896547134 and parameters: {'C': 77.94811928360285, 'gamma': 0.00016063795460308455, 'epsilon': 0.053225876592921585}. Best is trial 10 with value: 0.08531180480789917.
[I 2025-08-19 19:46:43,270] Trial 21 finished with value: 0.11057862838856632 and parameters: {'C': 60.20961578639933, 'gamma': 1.257701346704906e-06, 'epsilon': 0.02630881227806544}. Best is trial 10 with value: 0.08531180480789917.
[I 2025-08-19 19:46:43,314] Trial 22 finished with value: 0.09837498921195867 and parameters: {'C': 98.75767389170873, 'gamma': 1.0340466790231899e-06, 'epsilon': 0.053244232522568685}. Best is trial 10 with value: 0.08531180480789917.
[I 2025-08-19 19:46:43,357] Trial 23 finished with value: 0.14980698590536454 and parameters: {'C': 25.097987020278982, 'gamma': 4.406167785687718e-06, 'epsilon': 0.059104025517829784}. Best is trial 10 with value: 0.08531180480789917.
[I 2025-08-19 19:46:43,380] Trial 24 finished with value: 5.150118478250785 and parameters: {'C': 9.97818604458505, 'gamma': 3.246442232397524e-06, 'epsilon': 0.014678728288027083}. Best is trial 10 with value: 0.08531180480789917.
[I 2025-08-19 19:46:43,428] Trial 25 finished with value: 42.93326400815636 and parameters: {'C': 2.253050815424222, 'gamma': 1.6317648450574937e-05, 'epsilon': 0.07067553208854192}. Best is trial 10 with value: 0.08531180480789917.
[I 2025-08-19 19:46:43,483] Trial 26 finished with value: 0.09452974967321244 and parameters: {'C': 98.39556131829022, 'gamma': 1.010543388727866e-06, 'epsilon': 0.002271875951695716}. Best is trial 10 with value: 0.08531180480789917.
[I 2025-08-19 19:46:43,527] Trial 27 finished with value: 0.09358722552461109 and parameters: {'C': 34.35055046170382, 'gamma': 3.7582455180378247e-06, 'epsilon': 0.0018355499687599654}. Best is trial 10 with value: 0.08531180480789917.
[I 2025-08-19 19:46:43,577] Trial 28 finished with value: 0.21673156639476693 and parameters: {'C': 32.24928399371116, 'gamma': 3.491478749788632e-05, 'epsilon': 0.0036847782809166485}. Best is trial 10 with value: 0.08531180480789917.
[I 2025-08-19 19:46:43,595] Trial 29 finished with value: 887.3273162441801 and parameters: {'C': 0.13466343815561957, 'gamma': 4.643199842993009e-06, 'epsilon': 0.0019153253367777887}. Best is trial 10 with value: 0.08531180480789917.
[I 2025-08-19 19:46:43,652] Trial 30 finished with value: 7.1497046716494355 and parameters: {'C': 12.698100508264119, 'gamma': 0.00017686897123425337, 'epsilon': 0.004380826604447414}. Best is trial 10 with value: 0.08531180480789917.
[I 2025-08-19 19:46:43,684] Trial 31 finished with value: 0.09901570082251805 and parameters: {'C': 35.23480833361882, 'gamma': 3.02976718833927e-06, 'epsilon': 0.0018021993507934537}. Best is trial 10 with value: 0.08531180480789917.
[I 2025-08-19 19:46:43,709] Trial 32 finished with value: 757.4563312406406 and parameters: {'C': 0.32515834224697054, 'gamma': 1.0301793720140955e-05, 'epsilon': 0.001090807187488278}. Best is trial 10 with value: 0.08531180480789917.
[I 2025-08-19 19:46:43,734] Trial 33 finished with value: 0.09036297298855353 and parameters: {'C': 49.1213540813394, 'gamma': 2.3435812281802117e-06, 'epsilon': 0.0019939846163386844}. Best is trial 10 with value: 0.08531180480789917.
[I 2025-08-19 19:46:43,761] Trial 34 finished with value: 833.1993394107858 and parameters: {'C': 3.479994703312082, 'gamma': 0.009958028869425926, 'epsilon': 0.5022992787069026}. Best is trial 10 with value: 0.08531180480789917.
[I 2025-08-19 19:46:43,792] Trial 35 finished with value: 0.09219308804441947 and parameters: {'C': 41.76570996852241, 'gamma': 2.7224239205725273e-06, 'epsilon': 0.008263392898208776}. Best is trial 10 with value: 0.08531180480789917.
[I 2025-08-19 19:46:43,825] Trial 36 finished with value: 0.08272359582355557 and parameters: {'C': 43.096651455132495, 'gamma': 2.3338809999826855e-05, 'epsilon': 0.008260472614324658}. Best is trial 36 with value: 0.08272359582355557.
[I 2025-08-19 19:46:43,875] Trial 37 finished with value: 0.3183073500001806 and parameters: {'C': 17.35303075163055, 'gamma': 2.27393120762395e-05, 'epsilon': 0.010218267030143887}. Best is trial 36 with value: 0.08272359582355557.
[I 2025-08-19 19:46:43,924] Trial 38 finished with value: 7.7737521895752595 and parameters: {'C': 6.526914987895097, 'gamma': 7.691892975972941e-05, 'epsilon': 0.006065893299955261}. Best is trial 36 with value: 0.08272359582355557.
[I 2025-08-19 19:46:43,977] Trial 39 finished with value: 57.60042935678216 and parameters: {'C': 46.96355993674929, 'gamma': 0.0011233702128300041, 'epsilon': 0.0037297486835977446}. Best is trial 36 with value: 0.08272359582355557.
[I 2025-08-19 19:46:44,023] Trial 40 finished with value: 595.5491201949413 and parameters: {'C': 2.1267058090215603, 'gamma': 2.6216340363763908e-06, 'epsilon': 0.008570767976547872}. Best is trial 36 with value: 0.08272359582355557.
[I 2025-08-19 19:46:44,080] Trial 41 finished with value: 0.07386130407670953 and parameters: {'C': 43.08726539922563, 'gamma': 6.295493808219505e-06, 'epsilon': 0.014172140491128674}. Best is trial 41 with value: 0.07386130407670953.
[I 2025-08-19 19:46:44,124] Trial 42 finished with value: 0.06762715422046102 and parameters: {'C': 50.985658347368684, 'gamma': 6.65711475911925e-06, 'epsilon': 0.01573771582116977}. Best is trial 42 with value: 0.06762715422046102.
[I 2025-08-19 19:46:44,162] Trial 43 finished with value: 0.1882508987675785 and parameters: {'C': 19.539626569247144, 'gamma': 7.862521998640476e-06, 'epsilon': 0.016312817533788406}. Best is trial 42 with value: 0.06762715422046102.
[I 2025-08-19 19:46:44,203] Trial 44 finished with value: 0.1388335308972043 and parameters: {'C': 56.45359429300581, 'gamma': 3.20702072757553e-05, 'epsilon': 0.013546243392511278}. Best is trial 42 with value: 0.06762715422046102.
[I 2025-08-19 19:46:44,237] Trial 45 finished with value: 1.6607961813207326 and parameters: {'C': 9.666685574615821, 'gamma': 6.987012946872499e-06, 'epsilon': 0.026703319622824805}. Best is trial 42 with value: 0.06762715422046102.
[I 2025-08-19 19:46:44,286] Trial 46 finished with value: 223.29282727766181 and parameters: {'C': 61.13533713425655, 'gamma': 0.0029496330470598795, 'epsilon': 0.004902915544835193}. Best is trial 42 with value: 0.06762715422046102.
[I 2025-08-19 19:46:44,327] Trial 47 finished with value: 0.6610170573459662 and parameters: {'C': 23.05959496085843, 'gamma': 4.9304178149394794e-05, 'epsilon': 0.1799752864497023}. Best is trial 42 with value: 0.06762715422046102.
[I 2025-08-19 19:46:44,368] Trial 48 finished with value: 783.6248421372214 and parameters: {'C': 0.42706690785406276, 'gamma': 0.00048651187757112885, 'epsilon': 0.023346903612982604}. Best is trial 42 with value: 0.06762715422046102.
[I 2025-08-19 19:46:44,398] Trial 49 finished with value: 9.656253225934012 and parameters: {'C': 13.24717979244108, 'gamma': 1.95089840504197e-06, 'epsilon': 0.0032506552302962875}. Best is trial 42 with value: 0.06762715422046102.
[I 2025-08-19 19:46:44,439] Trial 50 finished with value: 910.1106399959226 and parameters: {'C': 0.02232675805772785, 'gamma': 1.5035381196595742e-05, 'epsilon': 0.041055342308849885}. Best is trial 42 with value: 0.06762715422046102.
[I 2025-08-19 19:46:44,470] Trial 51 finished with value: 0.10171905688057821 and parameters: {'C': 46.924968397615814, 'gamma': 1.8973220889850418e-06, 'epsilon': 0.01151424394210798}. Best is trial 42 with value: 0.06762715422046102.
[I 2025-08-19 19:46:44,509] Trial 52 finished with value: 0.08682241612132913 and parameters: {'C': 39.470472295936055, 'gamma': 4.997471742573755e-06, 'epsilon': 0.0065672672380412975}. Best is trial 42 with value: 0.06762715422046102.
[I 2025-08-19 19:46:44,590] Trial 53 finished with value: 0.11380522495709718 and parameters: {'C': 26.191874945766795, 'gamma': 5.210991291248159e-06, 'epsilon': 0.0188627460736274}. Best is trial 42 with value: 0.06762715422046102.
[I 2025-08-19 19:46:44,664] Trial 54 finished with value: 0.05172921349943864 and parameters: {'C': 69.79916502236411, 'gamma': 1.0308112024770193e-05, 'epsilon': 0.006522279100695935}. Best is trial 54 with value: 0.05172921349943864.
[I 2025-08-19 19:46:44,707] Trial 55 finished with value: 1.2859522774781635 and parameters: {'C': 81.00736178687227, 'gamma': 0.00010794194245458231, 'epsilon': 0.0062715464415190785}. Best is trial 54 with value: 0.05172921349943864.
[I 2025-08-19 19:46:44,756] Trial 56 finished with value: 0.05236937435505631 and parameters: {'C': 66.65892567385566, 'gamma': 1.1344792653780234e-05, 'epsilon': 0.03697822995940356}. Best is trial 54 with value: 0.05172921349943864.
[I 2025-08-19 19:46:44,787] Trial 57 finished with value: 861.657646147647 and parameters: {'C': 61.248818769010555, 'gamma': 0.07864181764387616, 'epsilon': 0.034092660471322145}. Best is trial 54 with value: 0.05172921349943864.
[I 2025-08-19 19:46:44,841] Trial 58 finished with value: 0.07835075307384595 and parameters: {'C': 71.73252280273428, 'gamma': 2.4868915087153916e-05, 'epsilon': 0.012408098315261986}. Best is trial 54 with value: 0.05172921349943864.
[I 2025-08-19 19:46:44,881] Trial 59 finished with value: 0.5521084333933609 and parameters: {'C': 14.175710301382779, 'gamma': 2.7205523490853836e-05, 'epsilon': 0.02035918001992267}. Best is trial 54 with value: 0.05172921349943864.
[I 2025-08-19 19:46:44,929] Trial 60 finished with value: 0.050005964051739085 and parameters: {'C': 72.46649539817058, 'gamma': 1.4279160232289852e-05, 'epsilon': 0.01194286790418858}. Best is trial 60 with value: 0.050005964051739085.
[I 2025-08-19 19:46:44,998] Trial 61 finished with value: 0.04949581845198585 and parameters: {'C': 63.0288787680752, 'gamma': 1.3190023300413915e-05, 'epsilon': 0.015238357055431542}. Best is trial 61 with value: 0.04949581845198585.
[I 2025-08-19 19:46:45,067] Trial 62 finished with value: 0.0492740072925816 and parameters: {'C': 77.7788242562891, 'gamma': 1.496878816951302e-05, 'epsilon': 0.012875828802044093}. Best is trial 62 with value: 0.0492740072925816.
[I 2025-08-19 19:46:45,126] Trial 63 finished with value: 0.04657288167852589 and parameters: {'C': 99.76651558531621, 'gamma': 1.1563772199032788e-05, 'epsilon': 0.034642487494015675}. Best is trial 63 with value: 0.04657288167852589.
[I 2025-08-19 19:46:45,174] Trial 64 finished with value: 0.04535939259470547 and parameters: {'C': 97.94869610007794, 'gamma': 1.3368453743018332e-05, 'epsilon': 0.03627498896800837}. Best is trial 64 with value: 0.04535939259470547.
[I 2025-08-19 19:46:45,226] Trial 65 finished with value: 0.05120694573624409 and parameters: {'C': 79.60852883173999, 'gamma': 1.2741530906821175e-05, 'epsilon': 0.04187795300293473}. Best is trial 64 with value: 0.04535939259470547.
[I 2025-08-19 19:46:45,265] Trial 66 finished with value: 0.46296342215431185 and parameters: {'C': 97.52732712358055, 'gamma': 6.151295517236483e-05, 'epsilon': 0.08571857996601566}. Best is trial 64 with value: 0.04535939259470547.
[I 2025-08-19 19:46:45,321] Trial 67 finished with value: 0.05282484715508431 and parameters: {'C': 76.76089873483575, 'gamma': 1.2022491135732907e-05, 'epsilon': 0.046032159221919014}. Best is trial 64 with value: 0.04535939259470547.
[I 2025-08-19 19:46:45,363] Trial 68 finished with value: 3.356928953313642 and parameters: {'C': 30.321649934870194, 'gamma': 0.00015972458575538124, 'epsilon': 0.02933885941776601}. Best is trial 64 with value: 0.04535939259470547.
[I 2025-08-19 19:46:45,396] Trial 69 finished with value: 0.07419703872331838 and parameters: {'C': 77.24616048759763, 'gamma': 1.7370772395958263e-05, 'epsilon': 0.14033916852306744}. Best is trial 64 with value: 0.04535939259470547.
[I 2025-08-19 19:46:45,434] Trial 70 finished with value: 0.2872111929481605 and parameters: {'C': 99.519687290657, 'gamma': 4.722131292278756e-05, 'epsilon': 0.10516194160653151}. Best is trial 64 with value: 0.04535939259470547.
[I 2025-08-19 19:46:45,472] Trial 71 finished with value: 0.0527525544670737 and parameters: {'C': 67.39879896022009, 'gamma': 1.0957989186238825e-05, 'epsilon': 0.03928635431261063}. Best is trial 64 with value: 0.04535939259470547.
[I 2025-08-19 19:46:45,510] Trial 72 finished with value: 0.062189878754161834 and parameters: {'C': 64.36134316989458, 'gamma': 1.5711119193353523e-05, 'epsilon': 0.05772152908952879}. Best is trial 64 with value: 0.04535939259470547.
[I 2025-08-19 19:46:45,543] Trial 73 finished with value: 0.07981845307861299 and parameters: {'C': 32.591689890893356, 'gamma': 1.0303780355487996e-05, 'epsilon': 0.03452995818827391}. Best is trial 64 with value: 0.04535939259470547.
[I 2025-08-19 19:46:45,583] Trial 74 finished with value: 0.3728145576612878 and parameters: {'C': 22.90321355521709, 'gamma': 3.9457813530760476e-05, 'epsilon': 0.023789679982566682}. Best is trial 64 with value: 0.04535939259470547.
[I 2025-08-19 19:46:45,630] Trial 75 finished with value: 0.06358058337562755 and parameters: {'C': 77.08829321158738, 'gamma': 1.8403033761918418e-05, 'epsilon': 0.07691345586561946}. Best is trial 64 with value: 0.04535939259470547.
[I 2025-08-19 19:46:45,674] Trial 76 finished with value: 0.05598241264407992 and parameters: {'C': 57.984010098581635, 'gamma': 8.795639925680433e-06, 'epsilon': 0.018469183913738}. Best is trial 64 with value: 0.04535939259470547.
[I 2025-08-19 19:46:45,712] Trial 77 finished with value: 1.4864031551282366 and parameters: {'C': 38.38628821665586, 'gamma': 0.00010439590401623269, 'epsilon': 0.010700530449492783}. Best is trial 64 with value: 0.04535939259470547.
[I 2025-08-19 19:46:45,755] Trial 78 finished with value: 0.08001389841449633 and parameters: {'C': 99.17805656134448, 'gamma': 3.79559306214509e-06, 'epsilon': 0.048582231915327005}. Best is trial 64 with value: 0.04535939259470547.
[I 2025-08-19 19:46:45,826] Trial 79 finished with value: 0.7835460743843725 and parameters: {'C': 27.941929040838527, 'gamma': 6.796981850245918e-05, 'epsilon': 0.02151654718583991}. Best is trial 64 with value: 0.04535939259470547.
[I 2025-08-19 19:46:45,875] Trial 80 finished with value: 912.6011618851575 and parameters: {'C': 0.13598494537810774, 'gamma': 1.4117570160792263e-06, 'epsilon': 0.03897682569472185}. Best is trial 64 with value: 0.04535939259470547.
[I 2025-08-19 19:46:45,917] Trial 81 finished with value: 0.052206827243447676 and parameters: {'C': 71.11334309177862, 'gamma': 1.1880386146284983e-05, 'epsilon': 0.032814285737837956}. Best is trial 64 with value: 0.04535939259470547.
[I 2025-08-19 19:46:45,969] Trial 82 finished with value: 0.14220849870794783 and parameters: {'C': 53.76213566591351, 'gamma': 3.1594538710796386e-05, 'epsilon': 0.03000900709738083}. Best is trial 64 with value: 0.04535939259470547.
[I 2025-08-19 19:46:46,041] Trial 83 finished with value: 891.7561096013517 and parameters: {'C': 78.80623136872941, 'gamma': 0.790529537735397, 'epsilon': 0.05965654726643572}. Best is trial 64 with value: 0.04535939259470547.
[I 2025-08-19 19:46:46,104] Trial 84 finished with value: 0.07126047464498704 and parameters: {'C': 35.71220434200481, 'gamma': 9.358203169457231e-06, 'epsilon': 0.016367923414524314}. Best is trial 64 with value: 0.04535939259470547.

[I 2025-08-19 19:46:47,062] A new study created in memory with name: no-name-5a777656-147b-4bd1-99a3-c4958be71dc2

[I 2025-08-19 19:46:46,961] Trial 97 finished with value: 0.05139025651923458 and parameters: {'C': 53.621074602414055, 'gamma': 1.2052674589891942e-05, 'epsilon': 0.01738841564505691}. Best is trial 64 with value: 0.04535939259470547.
[I 2025-08-19 19:46:47,014] Trial 98 finished with value: 0.08612532340283226 and parameters: {'C': 49.79920404662978, 'gamma': 2.408451817169739e-05, 'epsilon': 0.017194785107956103}. Best is trial 64 with value: 0.04535939259470547.
[I 2025-08-19 19:46:47,060] Trial 99 finished with value: 0.1072348858638776 and parameters: {'C': 26.543412537552207, 'gamma': 5.34218865915201e-06, 'epsilon': 0.014276742979324356}. Best is trial 64 with value: 0.04535939259470547.
    Best SVR MSE: 0.045359
  Optimizing Neural Network...

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2025-08-19 19:46:49,294] Trial 0 finished with value: 3.0285128127919556 and parameters: {'n_layers': 2, 'hidden_size_0': 155, 'hidden_size_1': 192, 'alpha': 7.167398116227066e-05, 'learning_rate_init': 0.016311046738317646}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:46:50,091] Trial 1 finished with value: 6.018862591096555 and parameters: {'n_layers': 1, 'hidden_size_0': 107, 'alpha': 1.4469073799463473e-05, 'learning_rate_init': 0.03479369431596534}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:46:51,872] Trial 2 finished with value: 5.297614436256131 and parameters: {'n_layers': 3, 'hidden_size_0': 102, 'hidden_size_1': 49, 'hidden_size_2': 12, 'alpha': 2.239817654479077e-06, 'learning_rate_init': 0.0005522897166504359}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:46:52,535] Trial 3 finished with value: 14.991196454702086 and parameters: {'n_layers': 2, 'hidden_size_0': 127, 'hidden_size_1': 149, 'alpha': 0.00013286000153927766, 'learning_rate_init': 0.004013361252949541}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:46:55,168] Trial 4 finished with value: 6.793827872530831 and parameters: {'n_layers': 3, 'hidden_size_0': 164, 'hidden_size_1': 71, 'hidden_size_2': 18, 'alpha': 2.4028914251212117e-06, 'learning_rate_init': 0.0006508397211868865}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:46:56,357] Trial 5 finished with value: 180.69574674806566 and parameters: {'n_layers': 3, 'hidden_size_0': 12, 'hidden_size_1': 171, 'hidden_size_2': 92, 'alpha': 3.31245933388589e-05, 'learning_rate_init': 0.0475469046012784}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:46:57,369] Trial 6 finished with value: 25.481632760249358 and parameters: {'n_layers': 3, 'hidden_size_0': 149, 'hidden_size_1': 93, 'hidden_size_2': 62, 'alpha': 0.0008307038575919792, 'learning_rate_init': 0.0006247417454051523}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:46:58,755] Trial 7 finished with value: 245.66691871327666 and parameters: {'n_layers': 1, 'hidden_size_0': 42, 'alpha': 2.003017770189989e-05, 'learning_rate_init': 0.00010288226798899776}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:46:59,121] Trial 8 finished with value: 8.328846103069203 and parameters: {'n_layers': 2, 'hidden_size_0': 47, 'hidden_size_1': 133, 'alpha': 5.0121585016886075e-06, 'learning_rate_init': 0.029839538215823313}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:46:59,311] Trial 9 finished with value: 28.60087166565117 and parameters: {'n_layers': 2, 'hidden_size_0': 14, 'hidden_size_1': 133, 'alpha': 1.82655565832615e-06, 'learning_rate_init': 0.024608957414494176}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:46:59,818] Trial 10 finished with value: 38.584729843863116 and parameters: {'n_layers': 2, 'hidden_size_0': 194, 'hidden_size_1': 200, 'alpha': 0.0065217668437104175, 'learning_rate_init': 0.006687816511517105}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:00,253] Trial 11 finished with value: 26.73123027684315 and parameters: {'n_layers': 3, 'hidden_size_0': 72, 'hidden_size_1': 25, 'hidden_size_2': 197, 'alpha': 0.00045963918861741137, 'learning_rate_init': 0.0010080106607169676}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:03,023] Trial 12 finished with value: 8.66360197425515 and parameters: {'n_layers': 1, 'hidden_size_0': 97, 'alpha': 1.001309224646373e-06, 'learning_rate_init': 0.00014096777684006513}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:03,237] Trial 13 finished with value: 39.598551475844324 and parameters: {'n_layers': 2, 'hidden_size_0': 170, 'hidden_size_1': 36, 'alpha': 0.00013761910153993413, 'learning_rate_init': 0.0016139670772281898}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:03,944] Trial 14 finished with value: 6.4724170771395375 and parameters: {'n_layers': 3, 'hidden_size_0': 137, 'hidden_size_1': 67, 'hidden_size_2': 11, 'alpha': 0.004517966787619774, 'learning_rate_init': 0.0078079741943560075}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:05,461] Trial 15 finished with value: 11.321092524229362 and parameters: {'n_layers': 2, 'hidden_size_0': 111, 'hidden_size_1': 11, 'alpha': 7.3049423917735455e-06, 'learning_rate_init': 0.00024221706729181657}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:05,606] Trial 16 finished with value: 1824.2569869790077 and parameters: {'n_layers': 2, 'hidden_size_0': 200, 'hidden_size_1': 57, 'alpha': 4.598334297723421e-05, 'learning_rate_init': 0.08579700930740414}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:06,460] Trial 17 finished with value: 5.430503429685098 and parameters: {'n_layers': 3, 'hidden_size_0': 84, 'hidden_size_1': 102, 'hidden_size_2': 155, 'alpha': 0.0007884242742537955, 'learning_rate_init': 0.01387694236126796}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:06,689] Trial 18 finished with value: 9.900419535426256 and parameters: {'n_layers': 1, 'hidden_size_0': 127, 'alpha': 0.0003191388269377228, 'learning_rate_init': 0.0023136070188197982}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:09,968] Trial 19 finished with value: 5.961218542915259 and parameters: {'n_layers': 2, 'hidden_size_0': 173, 'hidden_size_1': 200, 'alpha': 0.0018662694616628285, 'learning_rate_init': 0.00028042618492804154}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:10,395] Trial 20 finished with value: 31.77263800658747 and parameters: {'n_layers': 3, 'hidden_size_0': 66, 'hidden_size_1': 162, 'hidden_size_2': 66, 'alpha': 6.9867015996405694e-06, 'learning_rate_init': 0.004405737123506074}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:11,739] Trial 21 finished with value: 8.217109055712061 and parameters: {'n_layers': 3, 'hidden_size_0': 83, 'hidden_size_1': 104, 'hidden_size_2': 164, 'alpha': 0.0023794663952669713, 'learning_rate_init': 0.014806384406953942}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:12,716] Trial 22 finished with value: 6.7070700829547905 and parameters: {'n_layers': 3, 'hidden_size_0': 92, 'hidden_size_1': 88, 'hidden_size_2': 138, 'alpha': 8.225734773176203e-05, 'learning_rate_init': 0.014398029992321279}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:14,183] Trial 23 finished with value: 3.9507955059880757 and parameters: {'n_layers': 3, 'hidden_size_0': 117, 'hidden_size_1': 127, 'hidden_size_2': 134, 'alpha': 0.0003174947670872759, 'learning_rate_init': 0.01136554427578182}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:15,828] Trial 24 finished with value: 5.614906505390512 and parameters: {'n_layers': 3, 'hidden_size_0': 124, 'hidden_size_1': 132, 'hidden_size_2': 120, 'alpha': 0.0003826924919631764, 'learning_rate_init': 0.008162857244667044}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:16,031] Trial 25 finished with value: 3497.5250021807033 and parameters: {'n_layers': 2, 'hidden_size_0': 149, 'hidden_size_1': 174, 'alpha': 0.00019469216059657892, 'learning_rate_init': 0.09994017866681287}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:16,906] Trial 26 finished with value: 7.51621848268861 and parameters: {'n_layers': 3, 'hidden_size_0': 144, 'hidden_size_1': 118, 'hidden_size_2': 94, 'alpha': 6.839288311713364e-05, 'learning_rate_init': 0.0020884059249589295}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:17,142] Trial 27 finished with value: 27.525787918392524 and parameters: {'n_layers': 2, 'hidden_size_0': 116, 'hidden_size_1': 45, 'alpha': 1.3201865963429346e-05, 'learning_rate_init': 0.04960861459251587}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:19,067] Trial 28 finished with value: 34.45115154026491 and parameters: {'n_layers': 3, 'hidden_size_0': 162, 'hidden_size_1': 183, 'hidden_size_2': 55, 'alpha': 0.0009848516768340134, 'learning_rate_init': 0.0004138497821507624}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:19,590] Trial 29 finished with value: 6.616426108225761 and parameters: {'n_layers': 1, 'hidden_size_0': 181, 'alpha': 3.9343764885174843e-05, 'learning_rate_init': 0.0013121274790308187}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:20,418] Trial 30 finished with value: 3.7007170524045527 and parameters: {'n_layers': 2, 'hidden_size_0': 106, 'hidden_size_1': 152, 'alpha': 1.4495047119142385e-05, 'learning_rate_init': 0.023819644385882795}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:21,229] Trial 31 finished with value: 8.362167334765966 and parameters: {'n_layers': 2, 'hidden_size_0': 104, 'hidden_size_1': 147, 'alpha': 1.7755745667081238e-05, 'learning_rate_init': 0.02214001539784248}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:22,241] Trial 32 finished with value: 7.07035216255222 and parameters: {'n_layers': 2, 'hidden_size_0': 118, 'hidden_size_1': 147, 'alpha': 3.2383084086901717e-06, 'learning_rate_init': 0.005029436074826121}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:22,941] Trial 33 finished with value: 9.451593053096346 and parameters: {'n_layers': 2, 'hidden_size_0': 134, 'hidden_size_1': 120, 'alpha': 1.1439328285521097e-05, 'learning_rate_init': 0.011256374688922967}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:23,362] Trial 34 finished with value: 690.90055128975 and parameters: {'n_layers': 2, 'hidden_size_0': 99, 'hidden_size_1': 159, 'alpha': 0.00017786690401617124, 'learning_rate_init': 0.04650818171998645}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:25,138] Trial 35 finished with value: 8.300938868401845 and parameters: {'n_layers': 3, 'hidden_size_0': 155, 'hidden_size_1': 184, 'hidden_size_2': 187, 'alpha': 1.1538228114102887e-06, 'learning_rate_init': 0.002861976285661548}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:25,429] Trial 36 finished with value: 9.987486494946841 and parameters: {'n_layers': 1, 'hidden_size_0': 57, 'alpha': 2.7690639272323985e-05, 'learning_rate_init': 0.019750255687369045}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:25,585] Trial 37 finished with value: 404.26794520886295 and parameters: {'n_layers': 2, 'hidden_size_0': 109, 'hidden_size_1': 122, 'alpha': 4.0527836377922894e-06, 'learning_rate_init': 0.043289577804246575}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:26,244] Trial 38 finished with value: 49.21517913941861 and parameters: {'n_layers': 3, 'hidden_size_0': 85, 'hidden_size_1': 79, 'hidden_size_2': 119, 'alpha': 1.9972755206345467e-06, 'learning_rate_init': 0.06725236588468458}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:27,347] Trial 39 finished with value: 11.403085167940157 and parameters: {'n_layers': 2, 'hidden_size_0': 134, 'hidden_size_1': 156, 'alpha': 6.761241165610078e-05, 'learning_rate_init': 0.0034619183763240293}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:28,325] Trial 40 finished with value: 13.594847961203167 and parameters: {'n_layers': 3, 'hidden_size_0': 70, 'hidden_size_1': 189, 'hidden_size_2': 37, 'alpha': 8.842318526024578e-06, 'learning_rate_init': 0.0007607356709298668}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:28,576] Trial 41 finished with value: 433.04539787889087 and parameters: {'n_layers': 3, 'hidden_size_0': 86, 'hidden_size_1': 105, 'hidden_size_2': 152, 'alpha': 0.0007075873911208279, 'learning_rate_init': 0.0335516970913165}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:29,364] Trial 42 finished with value: 6.017072178998646 and parameters: {'n_layers': 3, 'hidden_size_0': 75, 'hidden_size_1': 99, 'hidden_size_2': 170, 'alpha': 0.00026412849014509853, 'learning_rate_init': 0.011110592769342714}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:30,467] Trial 43 finished with value: 4.193554340297191 and parameters: {'n_layers': 3, 'hidden_size_0': 40, 'hidden_size_1': 137, 'hidden_size_2': 140, 'alpha': 0.0006257608306303418, 'learning_rate_init': 0.016963724154705817}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:31,719] Trial 44 finished with value: 25.647847299937798 and parameters: {'n_layers': 3, 'hidden_size_0': 34, 'hidden_size_1': 143, 'hidden_size_2': 131, 'alpha': 0.00048167547541814695, 'learning_rate_init': 0.019995697616034373}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:31,967] Trial 45 finished with value: 19.03885196238069 and parameters: {'n_layers': 2, 'hidden_size_0': 28, 'hidden_size_1': 170, 'alpha': 0.00011494628395414891, 'learning_rate_init': 0.006073763669904877}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:32,858] Trial 46 finished with value: 20.947845667683815 and parameters: {'n_layers': 3, 'hidden_size_0': 51, 'hidden_size_1': 132, 'hidden_size_2': 102, 'alpha': 0.0014206255429345127, 'learning_rate_init': 0.02951173367549767}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:33,414] Trial 47 finished with value: 15.665629232182544 and parameters: {'n_layers': 3, 'hidden_size_0': 19, 'hidden_size_1': 114, 'hidden_size_2': 80, 'alpha': 0.0002219307819176926, 'learning_rate_init': 0.007734647265735478}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:33,974] Trial 48 finished with value: 16.73463028936205 and parameters: {'n_layers': 2, 'hidden_size_0': 122, 'hidden_size_1': 137, 'alpha': 2.9919973416670676e-05, 'learning_rate_init': 0.011193670249974304}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:35,595] Trial 49 finished with value: 7.7815830322563695 and parameters: {'n_layers': 3, 'hidden_size_0': 61, 'hidden_size_1': 172, 'hidden_size_2': 137, 'alpha': 0.003461493654826076, 'learning_rate_init': 0.01877450712858525}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:36,206] Trial 50 finished with value: 7.471062739119586 and parameters: {'n_layers': 1, 'hidden_size_0': 183, 'alpha': 2.8530756208734993e-06, 'learning_rate_init': 0.027601579219079124}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:37,682] Trial 51 finished with value: 13.313133513200267 and parameters: {'n_layers': 3, 'hidden_size_0': 102, 'hidden_size_1': 124, 'hidden_size_2': 155, 'alpha': 0.000563131708405974, 'learning_rate_init': 0.015424107789928563}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:38,648] Trial 52 finished with value: 11.84613202236595 and parameters: {'n_layers': 3, 'hidden_size_0': 78, 'hidden_size_1': 65, 'hidden_size_2': 177, 'alpha': 0.0013249558454071265, 'learning_rate_init': 0.010077899584118267}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:38,929] Trial 53 finished with value: 848.2953905884036 and parameters: {'n_layers': 3, 'hidden_size_0': 92, 'hidden_size_1': 85, 'hidden_size_2': 152, 'alpha': 0.0007864163561294474, 'learning_rate_init': 0.038694744592480554}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:39,167] Trial 54 finished with value: 22.58274658945239 and parameters: {'n_layers': 3, 'hidden_size_0': 39, 'hidden_size_1': 18, 'hidden_size_2': 119, 'alpha': 0.0003234795938884057, 'learning_rate_init': 0.014790037572516757}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:39,948] Trial 55 finished with value: 9.847629162742837 and parameters: {'n_layers': 2, 'hidden_size_0': 112, 'hidden_size_1': 110, 'alpha': 0.00014022667745671927, 'learning_rate_init': 0.005861186255328923}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:40,395] Trial 56 finished with value: 11.82416622894593 and parameters: {'n_layers': 3, 'hidden_size_0': 94, 'hidden_size_1': 37, 'hidden_size_2': 145, 'alpha': 0.007541988722123544, 'learning_rate_init': 0.025873977940725223}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:40,681] Trial 57 finished with value: 1140.9713811487272 and parameters: {'n_layers': 2, 'hidden_size_0': 141, 'hidden_size_1': 153, 'alpha': 5.393695073618938e-05, 'learning_rate_init': 0.05985038928365559}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:47,962] Trial 58 finished with value: 5.162496339849665 and parameters: {'n_layers': 3, 'hidden_size_0': 126, 'hidden_size_1': 140, 'hidden_size_2': 120, 'alpha': 0.002639895771543362, 'learning_rate_init': 0.00011272520390606658}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:51,037] Trial 59 finished with value: 4.6621734353900255 and parameters: {'n_layers': 3, 'hidden_size_0': 133, 'hidden_size_1': 137, 'hidden_size_2': 33, 'alpha': 0.0032533221198759155, 'learning_rate_init': 0.0002938643247072396}. Best is trial 0 with value: 3.0285128127919556.
[I 2025-08-19 19:47:57,232] Trial 60 finished with value: 2.908523277827393 and parameters: {'n_layers': 3, 'hidden_size_0': 154, 'hidden_size_1': 140, 'hidden_size_2': 115, 'alpha': 0.004067461276918362, 'learning_rate_init': 0.00010868908368942051}. Best is trial 60 with value: 2.908523277827393.
[I 2025-08-19 19:48:04,823] Trial 61 finished with value: 6.369642416073681 and parameters: {'n_layers': 3, 'hidden_size_0': 128, 'hidden_size_1': 140, 'hidden_size_2': 112, 'alpha': 0.004537367823800924, 'learning_rate_init': 0.0001084953798726521}. Best is trial 60 with value: 2.908523277827393.
[I 2025-08-19 19:48:08,138] Trial 62 finished with value: 27.540063802171506 and parameters: {'n_layers': 3, 'hidden_size_0': 155, 'hidden_size_1': 164, 'hidden_size_2': 128, 'alpha': 0.002109680201611014, 'learning_rate_init': 0.00019765623402579133}. Best is trial 60 with value: 2.908523277827393.
[I 2025-08-19 19:48:13,204] Trial 63 finished with value: 8.193934987050902 and parameters: {'n_layers': 3, 'hidden_size_0': 147, 'hidden_size_1': 127, 'hidden_size_2': 105, 'alpha': 0.0035773835363428104, 'learning_rate_init': 0.00016789769931494902}. Best is trial 60 with value: 2.908523277827393.
[I 2025-08-19 19:48:15,773] Trial 64 finished with value: 17.474731772997206 and parameters: {'n_layers': 3, 'hidden_size_0': 164, 'hidden_size_1': 150, 'hidden_size_2': 83, 'alpha': 0.005367012747383242, 'learning_rate_init': 0.00033869320127637376}. Best is trial 60 with value: 2.908523277827393.
[I 2025-08-19 19:48:21,672] Trial 65 finished with value: 6.321842673292701 and parameters: {'n_layers': 3, 'hidden_size_0': 130, 'hidden_size_1': 138, 'hidden_size_2': 28, 'alpha': 0.009249075399350132, 'learning_rate_init': 0.000123825318906889}. Best is trial 60 with value: 2.908523277827393.
[I 2025-08-19 19:48:26,159] Trial 66 finished with value: 6.576137627862506 and parameters: {'n_layers': 2, 'hidden_size_0': 156, 'hidden_size_1': 130, 'alpha': 0.0029106907055425025, 'learning_rate_init': 0.000168178585619393}. Best is trial 60 with value: 2.908523277827393.
[I 2025-08-19 19:48:26,903] Trial 67 finished with value: 16.701064920680103 and parameters: {'n_layers': 3, 'hidden_size_0': 140, 'hidden_size_1': 165, 'hidden_size_2': 127, 'alpha': 0.001526374250513073, 'learning_rate_init': 0.0005310825889972795}. Best is trial 60 with value: 2.908523277827393.
[I 2025-08-19 19:48:32,438] Trial 68 finished with value: 5.469389089284865 and parameters: {'n_layers': 2, 'hidden_size_0': 119, 'hidden_size_1': 146, 'alpha': 0.0009704429430416368, 'learning_rate_init': 0.00010018796280110973}. Best is trial 60 with value: 2.908523277827393.

[I 2025-08-19 19:50:21,249] A new study created in memory with name: no-name-05b89089-27ff-4e40-a0bc-d2eddff09bbc

[I 2025-08-19 19:50:21,245] Trial 99 finished with value: 1.9821807076124525 and parameters: {'n_layers': 2, 'hidden_size_0': 166, 'hidden_size_1': 96, 'alpha': 3.7993438209779864e-05, 'learning_rate_init': 0.000143225728911114}. Best is trial 99 with value: 1.9821807076124525.
    Best NN MSE: 1.982181
  Optimizing XGBoost...

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2025-08-19 19:50:22,063] Trial 0 finished with value: 2.9828711986541747 and parameters: {'n_estimators': 258, 'max_depth': 9, 'learning_rate': 0.2868097549949875, 'subsample': 0.7855361528214284, 'colsample_bytree': 0.8949975776223627, 'reg_alpha': 0.3320102363966625, 'reg_lambda': 0.5110654892617195}. Best is trial 0 with value: 2.9828711986541747.
[I 2025-08-19 19:50:22,908] Trial 1 finished with value: 230.43722839355468 and parameters: {'n_estimators': 180, 'max_depth': 9, 'learning_rate': 0.2796411269270747, 'subsample': 0.7933702148684326, 'colsample_bytree': 0.6820362600374056, 'reg_alpha': 0.015032244738287792, 'reg_lambda': 0.08755316586959205}. Best is trial 0 with value: 2.9828711986541747.
[I 2025-08-19 19:50:23,954] Trial 2 finished with value: 41.51788845062256 and parameters: {'n_estimators': 161, 'max_depth': 6, 'learning_rate': 0.1878953431482189, 'subsample': 0.8915671114884505, 'colsample_bytree': 0.8123394253137142, 'reg_alpha': 0.5345027511515238, 'reg_lambda': 0.6695520821461635}. Best is trial 0 with value: 2.9828711986541747.
[I 2025-08-19 19:50:26,851] Trial 3 finished with value: 20.14504747390747 and parameters: {'n_estimators': 413, 'max_depth': 5, 'learning_rate': 0.02330492566401024, 'subsample': 0.6380734147609546, 'colsample_bytree': 0.7084632067144855, 'reg_alpha': 0.7008700794530022, 'reg_lambda': 0.010623140491635374}. Best is trial 0 with value: 2.9828711986541747.
[I 2025-08-19 19:50:28,208] Trial 4 finished with value: 3.3994152307510377 and parameters: {'n_estimators': 432, 'max_depth': 6, 'learning_rate': 0.12021091525697909, 'subsample': 0.9569496331670797, 'colsample_bytree': 0.870226990068316, 'reg_alpha': 0.7312240315039474, 'reg_lambda': 0.435093453351329}. Best is trial 0 with value: 2.9828711986541747.
[I 2025-08-19 19:50:29,391] Trial 5 finished with value: 96.7448715209961 and parameters: {'n_estimators': 173, 'max_depth': 8, 'learning_rate': 0.08691771756991429, 'subsample': 0.6088455034591104, 'colsample_bytree': 0.6681143463440867, 'reg_alpha': 0.32542120056118984, 'reg_lambda': 0.0041135098313099805}. Best is trial 0 with value: 2.9828711986541747.
[I 2025-08-19 19:50:30,384] Trial 6 finished with value: 1.8853012084960938 and parameters: {'n_estimators': 247, 'max_depth': 4, 'learning_rate': 0.19806639115434782, 'subsample': 0.6700024796424326, 'colsample_bytree': 0.9299722797191209, 'reg_alpha': 0.43794163794797203, 'reg_lambda': 0.02396063029390616}. Best is trial 6 with value: 1.8853012084960938.
[I 2025-08-19 19:50:31,042] Trial 7 finished with value: 32.88284149169922 and parameters: {'n_estimators': 342, 'max_depth': 3, 'learning_rate': 0.24113901075722252, 'subsample': 0.7850682737528474, 'colsample_bytree': 0.8073724882416142, 'reg_alpha': 0.01937463403047257, 'reg_lambda': 0.9363830553724265}. Best is trial 6 with value: 1.8853012084960938.
[I 2025-08-19 19:50:31,459] Trial 8 finished with value: 8.080628395080566 and parameters: {'n_estimators': 78, 'max_depth': 5, 'learning_rate': 0.2929950878885234, 'subsample': 0.8283459221308414, 'colsample_bytree': 0.8479684819767384, 'reg_alpha': 0.342864361117479, 'reg_lambda': 0.475341108248701}. Best is trial 6 with value: 1.8853012084960938.
[I 2025-08-19 19:50:33,851] Trial 9 finished with value: 20.043710136413573 and parameters: {'n_estimators': 472, 'max_depth': 4, 'learning_rate': 0.032558088778383364, 'subsample': 0.8489797501078457, 'colsample_bytree': 0.7548199148748489, 'reg_alpha': 0.5163822278837185, 'reg_lambda': 0.9659068497351706}. Best is trial 6 with value: 1.8853012084960938.
[I 2025-08-19 19:50:34,645] Trial 10 finished with value: 1.9287651300430297 and parameters: {'n_estimators': 335, 'max_depth': 3, 'learning_rate': 0.1872848218450139, 'subsample': 0.6993642643004209, 'colsample_bytree': 0.9981341962753011, 'reg_alpha': 0.9258835810465541, 'reg_lambda': 0.22988284856541494}. Best is trial 6 with value: 1.8853012084960938.
[I 2025-08-19 19:50:35,376] Trial 11 finished with value: 1.9394787073135376 and parameters: {'n_estimators': 309, 'max_depth': 3, 'learning_rate': 0.18997222684394377, 'subsample': 0.6929233501126211, 'colsample_bytree': 0.995825475924077, 'reg_alpha': 0.9938772419949407, 'reg_lambda': 0.2335631727203537}. Best is trial 6 with value: 1.8853012084960938.
[I 2025-08-19 19:50:36,123] Trial 12 finished with value: 1.8365922689437866 and parameters: {'n_estimators': 249, 'max_depth': 3, 'learning_rate': 0.19912928235442232, 'subsample': 0.6951200153014897, 'colsample_bytree': 0.9954960824170772, 'reg_alpha': 0.9859926578458946, 'reg_lambda': 0.24217586412147524}. Best is trial 12 with value: 1.8365922689437866.
[I 2025-08-19 19:50:37,020] Trial 13 finished with value: 1.9586422920227051 and parameters: {'n_estimators': 241, 'max_depth': 4, 'learning_rate': 0.22443310004350467, 'subsample': 0.6990065728721915, 'colsample_bytree': 0.9421485025788295, 'reg_alpha': 0.7661596842270053, 'reg_lambda': 0.27349321550692984}. Best is trial 12 with value: 1.8365922689437866.
[I 2025-08-19 19:50:37,681] Trial 14 finished with value: 1.697997236251831 and parameters: {'n_estimators': 84, 'max_depth': 7, 'learning_rate': 0.14380863867521615, 'subsample': 0.733412795749345, 'colsample_bytree': 0.940854634390738, 'reg_alpha': 0.20804353733041508, 'reg_lambda': 0.1641748422189292}. Best is trial 14 with value: 1.697997236251831.
[I 2025-08-19 19:50:38,331] Trial 15 finished with value: 105.52458801269532 and parameters: {'n_estimators': 75, 'max_depth': 7, 'learning_rate': 0.14227781962456257, 'subsample': 0.7451515388781427, 'colsample_bytree': 0.6073046007031884, 'reg_alpha': 0.16807464836035468, 'reg_lambda': 0.3287757190384332}. Best is trial 14 with value: 1.697997236251831.
[I 2025-08-19 19:50:39,282] Trial 16 finished with value: 1.7027443170547485 and parameters: {'n_estimators': 117, 'max_depth': 10, 'learning_rate': 0.09876984395944828, 'subsample': 0.7417480134012758, 'colsample_bytree': 0.9467061797726664, 'reg_alpha': 0.16632691318982473, 'reg_lambda': 0.1616023777328279}. Best is trial 14 with value: 1.697997236251831.
[I 2025-08-19 19:50:39,797] Trial 17 finished with value: 2.166817617416382 and parameters: {'n_estimators': 50, 'max_depth': 10, 'learning_rate': 0.08148289708558994, 'subsample': 0.735343058909741, 'colsample_bytree': 0.9337715105681443, 'reg_alpha': 0.17119959526059345, 'reg_lambda': 0.13076790862792764}. Best is trial 14 with value: 1.697997236251831.
[I 2025-08-19 19:50:41,228] Trial 18 finished with value: 3.15608286857605 and parameters: {'n_estimators': 128, 'max_depth': 10, 'learning_rate': 0.09697145582043809, 'subsample': 0.8991866927001761, 'colsample_bytree': 0.8990570984356122, 'reg_alpha': 0.1470361559218521, 'reg_lambda': 0.6545469075409602}. Best is trial 14 with value: 1.697997236251831.
[I 2025-08-19 19:50:42,126] Trial 19 finished with value: 1.9830702304840089 and parameters: {'n_estimators': 118, 'max_depth': 8, 'learning_rate': 0.14722498510713955, 'subsample': 0.7512094900725433, 'colsample_bytree': 0.9549149112136073, 'reg_alpha': 0.23579281004119973, 'reg_lambda': 0.38910530018102585}. Best is trial 14 with value: 1.697997236251831.
[I 2025-08-19 19:50:43,858] Trial 20 finished with value: 9.647187995910645 and parameters: {'n_estimators': 204, 'max_depth': 7, 'learning_rate': 0.0575437718239477, 'subsample': 0.9976484536230416, 'colsample_bytree': 0.8397399671147195, 'reg_alpha': 0.07845276088119749, 'reg_lambda': 0.14152206258955705}. Best is trial 14 with value: 1.697997236251831.
[I 2025-08-19 19:50:44,732] Trial 21 finished with value: 1.7338661909103394 and parameters: {'n_estimators': 110, 'max_depth': 8, 'learning_rate': 0.12595342115786515, 'subsample': 0.6621886648083691, 'colsample_bytree': 0.9798100719716025, 'reg_alpha': 0.8638174539492769, 'reg_lambda': 0.17091982306740744}. Best is trial 14 with value: 1.697997236251831.
[I 2025-08-19 19:50:45,600] Trial 22 finished with value: 2.0816378355026246 and parameters: {'n_estimators': 117, 'max_depth': 8, 'learning_rate': 0.12887707418519911, 'subsample': 0.6328234196558107, 'colsample_bytree': 0.895898282534993, 'reg_alpha': 0.5833019218585545, 'reg_lambda': 0.1609798571493391}. Best is trial 14 with value: 1.697997236251831.
[I 2025-08-19 19:50:47,187] Trial 23 finished with value: 1.8629860639572144 and parameters: {'n_estimators': 136, 'max_depth': 9, 'learning_rate': 0.10715455365952563, 'subsample': 0.6522537861495511, 'colsample_bytree': 0.9604934927566866, 'reg_alpha': 0.257263302233113, 'reg_lambda': 0.5648867412392831}. Best is trial 14 with value: 1.697997236251831.
[I 2025-08-19 19:50:47,875] Trial 24 finished with value: 1.998898410797119 and parameters: {'n_estimators': 81, 'max_depth': 7, 'learning_rate': 0.1641600559474421, 'subsample': 0.733569846086311, 'colsample_bytree': 0.964497458695751, 'reg_alpha': 0.8456167640195719, 'reg_lambda': 0.33530246278311865}. Best is trial 14 with value: 1.697997236251831.
[I 2025-08-19 19:50:49,495] Trial 25 finished with value: 3.0469281911849975 and parameters: {'n_estimators': 216, 'max_depth': 10, 'learning_rate': 0.056598140469286844, 'subsample': 0.762381974779447, 'colsample_bytree': 0.9136705497202976, 'reg_alpha': 0.6406287630968879, 'reg_lambda': 0.186230520550685}. Best is trial 14 with value: 1.697997236251831.
[I 2025-08-19 19:50:50,198] Trial 26 finished with value: 2.1130327939987184 and parameters: {'n_estimators': 53, 'max_depth': 8, 'learning_rate': 0.1638383218670515, 'subsample': 0.6021158404251465, 'colsample_bytree': 0.8618331653058513, 'reg_alpha': 0.3899025725778762, 'reg_lambda': 0.08060625093167956}. Best is trial 14 with value: 1.697997236251831.
[I 2025-08-19 19:50:51,173] Trial 27 finished with value: 2.069286894798279 and parameters: {'n_estimators': 101, 'max_depth': 9, 'learning_rate': 0.06535563765573175, 'subsample': 0.8192854608458275, 'colsample_bytree': 0.9707327830456236, 'reg_alpha': 0.25260636017551075, 'reg_lambda': 0.318472831747761}. Best is trial 14 with value: 1.697997236251831.
[I 2025-08-19 19:50:52,208] Trial 28 finished with value: 27.83642120361328 and parameters: {'n_estimators': 151, 'max_depth': 6, 'learning_rate': 0.12043873040256181, 'subsample': 0.7164595931070897, 'colsample_bytree': 0.7777464114851512, 'reg_alpha': 0.4531572772887892, 'reg_lambda': 0.7994949142971836}. Best is trial 14 with value: 1.697997236251831.
[I 2025-08-19 19:50:53,627] Trial 29 finished with value: 2.332877850532532 and parameters: {'n_estimators': 198, 'max_depth': 9, 'learning_rate': 0.13374832775876486, 'subsample': 0.6687666362498926, 'colsample_bytree': 0.8837880141008898, 'reg_alpha': 0.8311078272776653, 'reg_lambda': 0.55494837819219}. Best is trial 14 with value: 1.697997236251831.
[I 2025-08-19 19:50:55,659] Trial 30 finished with value: 2.2969474315643312 and parameters: {'n_estimators': 294, 'max_depth': 7, 'learning_rate': 0.1652373785500092, 'subsample': 0.7795175267603381, 'colsample_bytree': 0.9159153598752172, 'reg_alpha': 0.08443204859659792, 'reg_lambda': 0.07258366212014834}. Best is trial 14 with value: 1.697997236251831.
[I 2025-08-19 19:50:56,219] Trial 31 finished with value: 2.2851067543029786 and parameters: {'n_estimators': 92, 'max_depth': 5, 'learning_rate': 0.2243998038341167, 'subsample': 0.6897584034724586, 'colsample_bytree': 0.9837802856590954, 'reg_alpha': 0.9991764300206427, 'reg_lambda': 0.23024034610495112}. Best is trial 14 with value: 1.697997236251831.
[I 2025-08-19 19:50:58,089] Trial 32 finished with value: 1.8914424657821656 and parameters: {'n_estimators': 274, 'max_depth': 8, 'learning_rate': 0.11068823393398154, 'subsample': 0.7173410799856821, 'colsample_bytree': 0.9997977916577813, 'reg_alpha': 0.9200493699022946, 'reg_lambda': 0.18515725216767862}. Best is trial 14 with value: 1.697997236251831.
[I 2025-08-19 19:50:58,986] Trial 33 finished with value: 1.7437103986740112 and parameters: {'n_estimators': 145, 'max_depth': 6, 'learning_rate': 0.1538795212358098, 'subsample': 0.6601512141195779, 'colsample_bytree': 0.9458961058349362, 'reg_alpha': 0.882711347834703, 'reg_lambda': 0.09207713531965532}. Best is trial 14 with value: 1.697997236251831.
[I 2025-08-19 19:50:59,882] Trial 34 finished with value: 1.6971583724021913 and parameters: {'n_estimators': 155, 'max_depth': 6, 'learning_rate': 0.15114071553845726, 'subsample': 0.6289247136463533, 'colsample_bytree': 0.9434725824053044, 'reg_alpha': 0.8496649818235984, 'reg_lambda': 0.09520043627401667}. Best is trial 34 with value: 1.6971583724021913.
[I 2025-08-19 19:51:00,968] Trial 35 finished with value: 2.119280242919922 and parameters: {'n_estimators': 175, 'max_depth': 9, 'learning_rate': 0.17457170737476285, 'subsample': 0.6437126082995652, 'colsample_bytree': 0.9172790034888265, 'reg_alpha': 0.6445444671004358, 'reg_lambda': 0.38065539983646307}. Best is trial 34 with value: 1.6971583724021913.
[I 2025-08-19 19:51:01,734] Trial 36 finished with value: 29.30788631439209 and parameters: {'n_estimators': 105, 'max_depth': 6, 'learning_rate': 0.09932772375241393, 'subsample': 0.6234955509340032, 'colsample_bytree': 0.8281278926214904, 'reg_alpha': 0.774045398360506, 'reg_lambda': 0.059309797848743906}. Best is trial 34 with value: 1.6971583724021913.
[I 2025-08-19 19:51:02,893] Trial 37 finished with value: 2.954250144958496 and parameters: {'n_estimators': 158, 'max_depth': 7, 'learning_rate': 0.07973702833847202, 'subsample': 0.7693081175268812, 'colsample_bytree': 0.8790292661794332, 'reg_alpha': 0.30544165812197255, 'reg_lambda': 0.11227157543112097}. Best is trial 34 with value: 1.6971583724021913.
[I 2025-08-19 19:51:03,617] Trial 38 finished with value: 2.0299549102783203 and parameters: {'n_estimators': 66, 'max_depth': 5, 'learning_rate': 0.1330276353384194, 'subsample': 0.8104600077210253, 'colsample_bytree': 0.9708073808389244, 'reg_alpha': 0.661180425306854, 'reg_lambda': 0.2818829680434388}. Best is trial 34 with value: 1.6971583724021913.
[I 2025-08-19 19:51:05,247] Trial 39 finished with value: 43.67351722717285 and parameters: {'n_estimators': 190, 'max_depth': 8, 'learning_rate': 0.11344295052975437, 'subsample': 0.6177047948510264, 'colsample_bytree': 0.7386023338282484, 'reg_alpha': 0.5682379725646033, 'reg_lambda': 0.17888236016719453}. Best is trial 34 with value: 1.6971583724021913.
[I 2025-08-19 19:51:06,914] Trial 40 finished with value: 2.9963382482528687 and parameters: {'n_estimators': 100, 'max_depth': 7, 'learning_rate': 0.042048540158932834, 'subsample': 0.6730204510326669, 'colsample_bytree': 0.9243777157607065, 'reg_alpha': 0.0017944308920977148, 'reg_lambda': 0.001149767461993717}. Best is trial 34 with value: 1.6971583724021913.
[I 2025-08-19 19:51:07,808] Trial 41 finished with value: 2.020021688938141 and parameters: {'n_estimators': 143, 'max_depth': 6, 'learning_rate': 0.1509045075892139, 'subsample': 0.6547427338115458, 'colsample_bytree': 0.9495335574301377, 'reg_alpha': 0.8787503974337287, 'reg_lambda': 0.05106387120287004}. Best is trial 34 with value: 1.6971583724021913.
[I 2025-08-19 19:51:08,729] Trial 42 finished with value: 1.7805968523025513 and parameters: {'n_estimators': 167, 'max_depth': 6, 'learning_rate': 0.14514863113935028, 'subsample': 0.6699502974177629, 'colsample_bytree': 0.9332906573077707, 'reg_alpha': 0.8180218845001908, 'reg_lambda': 0.09563832698365046}. Best is trial 34 with value: 1.6971583724021913.
[I 2025-08-19 19:51:09,873] Trial 43 finished with value: 1.9510333299636842 and parameters: {'n_estimators': 396, 'max_depth': 5, 'learning_rate': 0.18142369645157014, 'subsample': 0.7217354599594615, 'colsample_bytree': 0.980691470103101, 'reg_alpha': 0.9193654279304183, 'reg_lambda': 0.1309598411238071}. Best is trial 34 with value: 1.6971583724021913.
[I 2025-08-19 19:51:11,294] Trial 44 finished with value: 3.1599401235580444 and parameters: {'n_estimators': 219, 'max_depth': 6, 'learning_rate': 0.12872939642026923, 'subsample': 0.7948851364266971, 'colsample_bytree': 0.9030241172830928, 'reg_alpha': 0.7790327468199996, 'reg_lambda': 0.20901306351239526}. Best is trial 34 with value: 1.6971583724021913.
[I 2025-08-19 19:51:12,208] Trial 45 finished with value: 2.022776484489441 and parameters: {'n_estimators': 128, 'max_depth': 6, 'learning_rate': 0.09159902738911105, 'subsample': 0.8466340746486711, 'colsample_bytree': 0.9447766513659482, 'reg_alpha': 0.7286510025397884, 'reg_lambda': 0.03422907283148274}. Best is trial 34 with value: 1.6971583724021913.
[I 2025-08-19 19:51:12,869] Trial 46 finished with value: 2.8692382335662843 and parameters: {'n_estimators': 158, 'max_depth': 7, 'learning_rate': 0.26629040637845325, 'subsample': 0.6829991419916838, 'colsample_bytree': 0.8541405976663214, 'reg_alpha': 0.886042140819902, 'reg_lambda': 0.10878293681431889}. Best is trial 34 with value: 1.6971583724021913.
[I 2025-08-19 19:51:13,432] Trial 47 finished with value: 1.6997641801834107 and parameters: {'n_estimators': 88, 'max_depth': 4, 'learning_rate': 0.15468705242604658, 'subsample': 0.6355083423758091, 'colsample_bytree': 0.9782035269463413, 'reg_alpha': 0.10622242443557385, 'reg_lambda': 0.2828030122916506}. Best is trial 34 with value: 1.6971583724021913.
[I 2025-08-19 19:51:13,947] Trial 48 finished with value: 1.89209144115448 and parameters: {'n_estimators': 68, 'max_depth': 4, 'learning_rate': 0.2025102736536464, 'subsample': 0.629589574314773, 'colsample_bytree': 0.9695367427662667, 'reg_alpha': 0.1313433203348286, 'reg_lambda': 0.2849464598589005}. Best is trial 34 with value: 1.6971583724021913.
[I 2025-08-19 19:51:14,393] Trial 49 finished with value: 147.70938720703126 and parameters: {'n_estimators': 89, 'max_depth': 4, 'learning_rate': 0.20901423261908023, 'subsample': 0.6051789672464047, 'colsample_bytree': 0.673174279142153, 'reg_alpha': 0.2110957662551094, 'reg_lambda': 0.4216863865989033}. Best is trial 34 with value: 1.6971583724021913.
[I 2025-08-19 19:51:15,044] Trial 50 finished with value: 205.21090087890624 and parameters: {'n_estimators': 62, 'max_depth': 10, 'learning_rate': 0.012936087001846092, 'subsample': 0.7062541022474115, 'colsample_bytree': 0.9830977287400519, 'reg_alpha': 0.11992966738412918, 'reg_lambda': 0.4709467775673074}. Best is trial 34 with value: 1.6971583724021913.
[I 2025-08-19 19:51:15,815] Trial 51 finished with value: 1.7230761528015137 and parameters: {'n_estimators': 113, 'max_depth': 5, 'learning_rate': 0.15703726149873573, 'subsample': 0.654973330631344, 'colsample_bytree': 0.9524092110602861, 'reg_alpha': 0.08737594468615903, 'reg_lambda': 0.14753011383283582}. Best is trial 34 with value: 1.6971583724021913.
[I 2025-08-19 19:51:16,562] Trial 52 finished with value: 1.649848186969757 and parameters: {'n_estimators': 112, 'max_depth': 5, 'learning_rate': 0.1388540652666889, 'subsample': 0.638057170038058, 'colsample_bytree': 0.9343943394294899, 'reg_alpha': 0.07698022390156456, 'reg_lambda': 0.258162973778877}. Best is trial 52 with value: 1.649848186969757.
[I 2025-08-19 19:51:17,602] Trial 53 finished with value: 1.90559983253479 and parameters: {'n_estimators': 123, 'max_depth': 5, 'learning_rate': 0.17477830170813025, 'subsample': 0.6441426985324993, 'colsample_bytree': 0.8848383833273625, 'reg_alpha': 0.0688677905059019, 'reg_lambda': 0.2655529796252729}. Best is trial 52 with value: 1.649848186969757.
[I 2025-08-19 19:51:18,234] Trial 54 finished with value: 1.6054603338241578 and parameters: {'n_estimators': 82, 'max_depth': 4, 'learning_rate': 0.1418989241795294, 'subsample': 0.6227210481437138, 'colsample_bytree': 0.9326303435238218, 'reg_alpha': 0.037045584030686876, 'reg_lambda': 0.21330248847607453}. Best is trial 54 with value: 1.6054603338241578.

In [28]:
# Print comparison between default and optimized models
print("\n" + "="*80)
print("COMPARISON: DEFAULT vs OPTIMIZED MODELS")
print("="*80)

for dat in ["Ti_TM", "Ti_TE", "Si_TE", "Si_TM"]:
    print(f"\n{dat} Dataset:")
    print(f"Linear Regression    - Mean MSE: {results_entire_wave_dfs[dat]['mse'].mean():.6f}")
    print(f"SVR (default)        - Mean MSE: {results_svr_dfs[dat]['mse'].mean():.6f}")
    print(f"SVR (optimized)      - Mean MSE: {results_svr_optimized_dfs[dat]['mse'].mean():.6f}")
    print(f"Neural Net (default) - Mean MSE: {results_nn_dfs[dat]['mse'].mean():.6f}")
    print(f"Neural Net (optimized) - Mean MSE: {results_nn_optimized_dfs[dat]['mse'].mean():.6f}")
    print(f"XGBoost (default)    - Mean MSE: {results_xgb_dfs[dat]['mse'].mean():.6f}")
    print(f"XGBoost (optimized)  - Mean MSE: {results_xgb_optimized_dfs[dat]['mse'].mean():.6f}")

# Print best parameters found
print("\n" + "="*80)
print("BEST PARAMETERS FOUND")
print("="*80)

for dat in ["Ti_TM", "Ti_TE", "Si_TE", "Si_TM"]:
    print(f"\n{dat}:")
    print(f"  SVR: {best_params[dat]['svr']}")
    print(f"  Neural Network: {best_params[dat]['nn']}")
    print(f"  XGBoost: {best_params[dat]['xgb']}")

print("\nOptimization complete!")
print("New result dataframes available:")
print("- results_svr_optimized_dfs")
print("- results_nn_optimized_dfs") 
print("- results_xgb_optimized_dfs")

whecho_simple("Optimization complete!")

================================================================================
COMPARISON: DEFAULT vs OPTIMIZED MODELS
================================================================================

Ti_TM Dataset:
Linear Regression    - Mean MSE: 0.000066
SVR (default)        - Mean MSE: 231.650468
SVR (optimized)      - Mean MSE: 0.003867
Neural Net (default) - Mean MSE: 0.801461
Neural Net (optimized) - Mean MSE: 0.288452
XGBoost (default)    - Mean MSE: 3.065881
XGBoost (optimized)  - Mean MSE: 1.457998

Ti_TE Dataset:
Linear Regression    - Mean MSE: 0.000105
SVR (default)        - Mean MSE: 207.143654
SVR (optimized)      - Mean MSE: 0.007182
Neural Net (default) - Mean MSE: 0.434624
Neural Net (optimized) - Mean MSE: 0.091043
XGBoost (default)    - Mean MSE: 2.557486
XGBoost (optimized)  - Mean MSE: 1.552502

Si_TE Dataset:
Linear Regression    - Mean MSE: 0.024732
SVR (default)        - Mean MSE: 294.984277
SVR (optimized)      - Mean MSE: 0.034510
Neural Net (default) - Mean MSE: 13.062227
Neural Net (optimized) - Mean MSE: 2.805551
XGBoost (default)    - Mean MSE: 3.950529
XGBoost (optimized)  - Mean MSE: 2.340006

Si_TM Dataset:
Linear Regression    - Mean MSE: 0.103450
SVR (default)        - Mean MSE: 278.013369
SVR (optimized)      - Mean MSE: 0.045359
Neural Net (default) - Mean MSE: 8.041610
Neural Net (optimized) - Mean MSE: 1.982181
XGBoost (default)    - Mean MSE: 3.379713
XGBoost (optimized)  - Mean MSE: 1.527163

================================================================================
BEST PARAMETERS FOUND
================================================================================

Ti_TM:
  SVR: {'C': 84.54788530010002, 'gamma': 2.0522492088685758e-06, 'epsilon': 0.002196186971712145}
  Neural Network: {'n_layers': 3, 'hidden_size_0': 195, 'hidden_size_1': 55, 'hidden_size_2': 107, 'alpha': 4.059251991197128e-06, 'learning_rate_init': 0.0005378315209447669}
  XGBoost: {'n_estimators': 394, 'max_depth': 8, 'learning_rate': 0.2197431953834002, 'subsample': 0.7876663385639157, 'colsample_bytree': 0.8901295380641869, 'reg_alpha': 0.06952659713942783, 'reg_lambda': 0.4295665114667916}

Ti_TE:
  SVR: {'C': 99.31927645418497, 'gamma': 1.6130696521046082e-06, 'epsilon': 0.015822532271820122}
  Neural Network: {'n_layers': 2, 'hidden_size_0': 189, 'hidden_size_1': 86, 'alpha': 1.9358820336624017e-06, 'learning_rate_init': 0.0005460713456989244}
  XGBoost: {'n_estimators': 497, 'max_depth': 9, 'learning_rate': 0.030616039646095248, 'subsample': 0.6086454800124534, 'colsample_bytree': 0.9334602635627671, 'reg_alpha': 0.7077919174123913, 'reg_lambda': 0.416299934480547}

Si_TE:
  SVR: {'C': 98.39556131829022, 'gamma': 3.5192320328699353e-06, 'epsilon': 0.003084683544165717}
  Neural Network: {'n_layers': 3, 'hidden_size_0': 200, 'hidden_size_1': 165, 'hidden_size_2': 185, 'alpha': 0.006657414520749798, 'learning_rate_init': 0.0012587698689381554}
  XGBoost: {'n_estimators': 51, 'max_depth': 3, 'learning_rate': 0.11205167224345752, 'subsample': 0.8602025987229485, 'colsample_bytree': 0.9756220949039995, 'reg_alpha': 0.3417181895008865, 'reg_lambda': 0.13992848588481702}

Si_TM:
  SVR: {'C': 97.94869610007794, 'gamma': 1.3368453743018332e-05, 'epsilon': 0.03627498896800837}
  Neural Network: {'n_layers': 2, 'hidden_size_0': 166, 'hidden_size_1': 96, 'alpha': 3.7993438209779864e-05, 'learning_rate_init': 0.000143225728911114}
  XGBoost: {'n_estimators': 196, 'max_depth': 4, 'learning_rate': 0.10504431659408346, 'subsample': 0.6626736865257269, 'colsample_bytree': 0.97513641824964, 'reg_alpha': 0.33238622896043324, 'reg_lambda': 0.16890320348902174}

Optimization complete!
New result dataframes available:
- results_svr_optimized_dfs
- results_nn_optimized_dfs
- results_xgb_optimized_dfs

In [ ]:
# Create Excel file with model comparison and hyperparameters
def create_results_excel(results_entire_wave_dfs, results_svr_dfs, results_nn_dfs, results_xgb_dfs,
                        results_svr_optimized_dfs, results_nn_optimized_dfs, results_xgb_optimized_dfs,
                        best_params, filename='model_results.xlsx'):
    """
    Create an Excel file with model comparison and hyperparameters
    """
    
    # Sheet 1: Model Comparison
    datasets = ["Ti_TM", "Ti_TE", "Si_TE", "Si_TM"]
    
    comparison_data = {
        'Dataset': datasets,
        'Linear Regression': [results_entire_wave_dfs[dat]['mse'].mean() for dat in datasets],
        'SVR (default)': [results_svr_dfs[dat]['mse'].mean() for dat in datasets],
        'SVR (optimized)': [results_svr_optimized_dfs[dat]['mse'].mean() for dat in datasets],
        'Neural Net (default)': [results_nn_dfs[dat]['mse'].mean() for dat in datasets],
        'Neural Net (optimized)': [results_nn_optimized_dfs[dat]['mse'].mean() for dat in datasets],
        'XGBoost (default)': [results_xgb_dfs[dat]['mse'].mean() for dat in datasets],
        'XGBoost (optimized)': [results_xgb_optimized_dfs[dat]['mse'].mean() for dat in datasets]
    }
    
    comparison_df = pd.DataFrame(comparison_data)
    
    # Sheet 2: Optimal Hyperparameters
    hyperparams_data = []
    
    for dataset in datasets:
        # SVR parameters
        svr_params = best_params[dataset]['svr']
        hyperparams_data.append({
            'Dataset': dataset,
            'Model': 'SVR',
            'Parameter': 'C',
            'Value': svr_params['C']
        })
        hyperparams_data.append({
            'Dataset': dataset,
            'Model': 'SVR',
            'Parameter': 'gamma',
            'Value': svr_params['gamma']
        })
        hyperparams_data.append({
            'Dataset': dataset,
            'Model': 'SVR',
            'Parameter': 'epsilon',
            'Value': svr_params['epsilon']
        })
        
        # Neural Network parameters
        nn_params = best_params[dataset]['nn']
        hyperparams_data.append({
            'Dataset': dataset,
            'Model': 'Neural Network',
            'Parameter': 'n_layers',
            'Value': nn_params['n_layers']
        })
        
        # Hidden layer sizes
        for i in range(nn_params['n_layers']):
            hyperparams_data.append({
                'Dataset': dataset,
                'Model': 'Neural Network',
                'Parameter': f'hidden_size_{i}',
                'Value': nn_params[f'hidden_size_{i}']
            })
        
        hyperparams_data.append({
            'Dataset': dataset,
            'Model': 'Neural Network',
            'Parameter': 'alpha',
            'Value': nn_params['alpha']
        })
        hyperparams_data.append({
            'Dataset': dataset,
            'Model': 'Neural Network',
            'Parameter': 'learning_rate_init',
            'Value': nn_params['learning_rate_init']
        })
        
        # XGBoost parameters
        xgb_params = best_params[dataset]['xgb']
        xgb_param_names = ['n_estimators', 'max_depth', 'learning_rate', 'subsample', 
                          'colsample_bytree', 'reg_alpha', 'reg_lambda']
        
        for param_name in xgb_param_names:
            hyperparams_data.append({
                'Dataset': dataset,
                'Model': 'XGBoost',
                'Parameter': param_name,
                'Value': xgb_params[param_name]
            })
    
    hyperparams_df = pd.DataFrame(hyperparams_data)
    
    # Create Excel writer and save both sheets
    with pd.ExcelWriter(filename, engine='openpyxl') as writer:
        # Sheet 1: Model Comparison
        comparison_df.to_excel(writer, sheet_name='Model Comparison', index=False)
        
        # Format the comparison sheet
        workbook = writer.book
        comparison_sheet = writer.sheets['Model Comparison']
        
        # Auto-adjust column widths
        for column in comparison_sheet.columns:
            max_length = 0
            column_letter = column[0].column_letter
            for cell in column:
                try:
                    if len(str(cell.value)) > max_length:
                        max_length = len(str(cell.value))
                except:
                    pass
            adjusted_width = min(max_length + 2, 20)
            comparison_sheet.column_dimensions[column_letter].width = adjusted_width
        
        # Sheet 2: Hyperparameters
        hyperparams_df.to_excel(writer, sheet_name='Optimal Hyperparameters', index=False)
        
        # Format the hyperparameters sheet
        hyperparams_sheet = writer.sheets['Optimal Hyperparameters']
        
        # Auto-adjust column widths
        for column in hyperparams_sheet.columns:
            max_length = 0
            column_letter = column[0].column_letter
            for cell in column:
                try:
                    if len(str(cell.value)) > max_length:
                        max_length = len(str(cell.value))
                except:
                    pass
            adjusted_width = min(max_length + 2, 25)
            hyperparams_sheet.column_dimensions[column_letter].width = adjusted_width
    
    print(f"Excel file '{filename}' created successfully!")
    print("Sheet 1: Model Comparison - Mean MSE values for all models")
    print("Sheet 2: Optimal Hyperparameters - Best parameters found by Optuna")
    
    return comparison_df, hyperparams_df

# Call the function to create the Excel file
comparison_df, hyperparams_df = create_results_excel(
    results_entire_wave_dfs, results_svr_dfs, results_nn_dfs, results_xgb_dfs,
    results_svr_optimized_dfs, results_nn_optimized_dfs, results_xgb_optimized_dfs,
    best_params, filename='suppl_table4.xlsx'
)

# # Display the dataframes for preview
# print("\nPreview of Model Comparison sheet:")
# print(comparison_df.to_string(index=False))

# print("\nPreview of Optimal Hyperparameters sheet (first 10 rows):")
# print(hyperparams_df.head(10).to_string(index=False))

Excel file 'suppl_table4.xlsx' created successfully!
Sheet 1: Model Comparison - Mean MSE values for all models
Sheet 2: Optimal Hyperparameters - Best parameters found by Optuna

Preview of Model Comparison sheet:
Dataset  Linear Regression  SVR (default)  SVR (optimized)  Neural Net (default)  Neural Net (optimized)  XGBoost (default)  XGBoost (optimized)
  Ti_TM           0.000066     231.650468         0.003867              0.801461                0.288452           3.065881             1.457998
  Ti_TE           0.000105     207.143654         0.007182              0.434624                0.091043           2.557486             1.552502
  Si_TE           0.024732     294.984277         0.034510             13.062227                2.805551           3.950529             2.340006
  Si_TM           0.103450     278.013369         0.045359              8.041610                1.982181           3.379713             1.527163

Preview of Optimal Hyperparameters sheet (first 10 rows):
Dataset          Model          Parameter      Value
  Ti_TM            SVR                  C  84.547885
  Ti_TM            SVR              gamma   0.000002
  Ti_TM            SVR            epsilon   0.002196
  Ti_TM Neural Network           n_layers   3.000000
  Ti_TM Neural Network      hidden_size_0 195.000000
  Ti_TM Neural Network      hidden_size_1  55.000000
  Ti_TM Neural Network      hidden_size_2 107.000000
  Ti_TM Neural Network              alpha   0.000004
  Ti_TM Neural Network learning_rate_init   0.000538
  Ti_TM        XGBoost       n_estimators 394.000000